SELECT *
FROM all_scheduler_running_jobs;
--
SELECT
	JOB_NAME,
	STATE,
	LAST_START_DATE,
	LAST_RUN_DURATION,
	NEXT_RUN_DATE,
	REPEAT_INTERVAL
FROM DBA_SCHEDULER_JOBS
WHERE STATE = 'RUNNING';
--
EXEC dbms_scheduler.run_job('USER.JOB');
--
BEGIN
	DBMS_SCHEDULER.run_job('COBRA1.CARGAICS');
END;