DECLARE
	CURSOR CUR_TABLAS
	IS
	SELECT * FROM EQ_TABLAS
	WHERE table_name IN (
		'HJPF01','HJPF205','HJPF71','MCPF01','FNPF01',
		'FNPF02','FNPF03','ORDENE','ORPF06','SIPF05',
		'CLPF05','CLPF07','IMPF01'
	);
BEGIN
	FOR I IN CUR_TABLAS
	LOOP
		EXECUTE IMMEDIATE 'DROP TABLE   ' || I.table_name;
		EXECUTE IMMEDIATE 'CREATE TABLE ' ||I.table_name||' AS (SELECT * from '||I.table_name||'@sqldesarrollodsn)';
	END LOOP;
END;