SELECT *
FROM MIGCARTEI_NM A
WHERE RAMO IN (33, 34, 35)
AND EXISTS(
	SELECT 1 FROM MIGCARTEI_NM B
	WHERE B.RAMO = 32
	AND A.POLIZA = B.POLIZA
	AND A.NUMREC = B.NUMREC
	AND B.MIGRA = 'S'
)
AND OBSERV IN ('COBERTURA NO CONSUMIDA', 'FUERA DE VIGENCIA')
AND POLIZA = 1202556;
--
SELECT * FROM MIGCARTEI_NM WHERE NUMREC = 13811243;
SELECT * FROM POLIZAS_MIGRA_REN WHERE POLIZA = 1202556;
SELECT * FROM EQ_POLIZA_NO_MIGRADO WHERE POLIZA = 1202556;
SELECT * FROM SINIESTROS_MIGRA_REN;