DECLARE
	CURSOR CUR
	IS
	SELECT DISTINCT UN.*, RC.FE_EFECTIVA, RC.SUMAASEGURADA, RC.RECIBO
	FROM AF_RIESGOS_CUBIERTOS RC,(
		SELECT CODPOL, NUMPOL, P.IDEPOL, STSPOL, FECINIVIG, FECFINVIG,
			CODOFIEMI, NUMCERT, CODRAMOCERT, SUMAASEGMONEDA
		FROM POLIZA P, COBERT_CERT CC
		WHERE P.IDEPOL = CC.IDEPOL
		AND CC.CODRAMOCERT IN ('0104', '0115')
	) UN
	WHERE RC.CD_SUCURSAL = UN.CODOFIEMI
	AND RC.NU_POLIZA = UN.NUMPOL
	AND RC.NU_CERTIFICADO = UN.NUMCERT
	AND RC.CD_RAMO = UN.CODRAMOCERT
	AND RC.COD_PRODUCTO = UN.CODPOL
	AND RC.FE_EFECTIVA = UN.FECINIVIG
	AND UN.SUMAASEGMONEDA <> RC.SUMAASEGURADA
	AND UN.SUMAASEGMONEDA = 1000
	AND UN.STSPOL NOT IN ('ANU');
BEGIN
	FOR I IN CUR
	LOOP
		UPDATE AF_RIESGOS_CUBIERTOS
		SET SUMAASEGURADA = I.SUMAASEGMONEDA
		WHERE COD_PRODUCTO = I.CODPOL
		AND NU_POLIZA = I.NUMPOL
		AND CD_SUCURSAL = I.CODOFIEMI
		AND NU_CERTIFICADO = I.NUMCERT
		AND CD_RAMO = I.CODRAMOCERT
		AND FE_EFECTIVA = I.FE_EFECTIVA;
	END LOOP;
END;
--
SELECT * FROM RECIBO R, COBERT_CERT CC
WHERE R.IDEPOL = CC.IDEPOL
AND R.CODRAMOCERT = CC.CODRAMOCERT
AND R.IDEPOL IN (11772)
AND CC.CODRAMOCERT IN ('0104', '0115');