SELECT * FROM MIGCARTEI_NM A
WHERE NOT EXISTS (
	SELECT *
	FROM MIGCARTEI B
	WHERE B.RAMO = A.RAMO
	AND B.POLIZA = A.POLIZA
	AND B.NUMREC = A.NUMREC
	AND B.OBSERV = 'COBERTURA NO CONSUMIDA'
)
AND A.OBSERV = 'COBERTURA NO CONSUMIDA';
--
SELECT COUNT (*) FROM MIGCARTEI WHERE OBSERV = 'COBERTURA NO CONSUMIDA'
UNION ALL
SELECT COUNT (*) FROM MIGCARTEI_NM WHERE OBSERV = 'COBERTURA NO CONSUMIDA';