BEGIN
	EXECUTE IMMEDIATE 'TRUNCATE TABLE RECIBOS_SIN_ALL';

	INSERT INTO RECIBOS_SIN_ALL(
		SELECT DISTINCT RAMO, POLIZA, NUMREC, NUMCERT, 
				SUBSTR(PM.BUSCA_PRODUCTO_PLAN(RAMO,POLIZA,NUMCERT),1,4) PRODUCTO
		FROM SINIESTROS_MIGRA_REN
	);
	COMMIT;

	EXECUTE IMMEDIATE 'TRUNCATE TABLE SINIESTROS_RECIBO_MULTIRAMO';
	FOR I IN (SELECT DISTINCT POLIZA, NUMREC, 1 NUMCERT, PRODUCTO FROM RECIBOS_SIN_ALL WHERE PRODUCTO = 'AUTI')
	LOOP
		FOR J IN (SELECT * FROM (
					SELECT 32 RAMO FROM DUAL UNION
					SELECT 33 RAMO FROM DUAL UNION
					SELECT 34 RAMO FROM DUAL UNION
					SELECT 35 RAMO FROM DUAL))
		LOOP
			INSERT INTO SINIESTROS_RECIBO_MULTIRAMO
			VALUES (J.RAMO, I.POLIZA, I.NUMREC, I.NUMCERT, I.PRODUCTO);
		END LOOP;
		COMMIT;
	END LOOP;

	FOR I IN (SELECT DISTINCT POLIZA, NUMREC, 1 NUMCERT, PRODUCTO FROM RECIBOS_SIN_ALL WHERE PRODUCTO = 'AERO')
	LOOP
		FOR J IN (SELECT * FROM (
					SELECT 36 RAMO FROM DUAL UNION
					SELECT 37 RAMO FROM DUAL UNION
					SELECT 38 RAMO FROM DUAL))
		LOOP
			INSERT INTO SINIESTROS_RECIBO_MULTIRAMO
			VALUES (J.RAMO,I.POLIZA,I.NUMREC,I.NUMCERT,I.PRODUCTO);
		END LOOP;
		COMMIT;
	END LOOP;

	FOR I IN (SELECT DISTINCT RAMO,POLIZA,NUMREC,NUMCERT,PRODUCTO FROM RECIBOS_SIN_ALL WHERE PRODUCTO NOT IN ('AUTI', 'AERO'))
	LOOP
		INSERT INTO SINIESTROS_RECIBO_MULTIRAMO
		VALUES (I.RAMO, I.POLIZA, I.NUMREC, I.NUMCERT, I.PRODUCTO);
		COMMIT;
	END LOOP;
END;