SELECT 'EQ_SINIESTRO_REN', COUNT (*) FROM EQ_SINIESTRO_REN
UNION ALL
SELECT 'EQ_POLIZA_NO_MIGRADO', COUNT (*) FROM EQ_POLIZA_NO_MIGRADO
UNION ALL
SELECT 'POLIZA', COUNT (*) FROM ACSMIGRE.VIG_POLIZA@DESA
UNION ALL
SELECT 'RECIBO', COUNT (*) FROM ACSMIGRE.VIG_RECIBO@DESA
UNION ALL
SELECT 'CERTIFICADO', COUNT (*) FROM ACSMIGRE.VIG_CERTIFICADO@DESA
UNION ALL
SELECT 'COBERT_CERT', COUNT (*) FROM ACSMIGRE.VIG_COBERT_CERT@DESA
UNION ALL
SELECT 'COBERT_CERT_REC', COUNT (*) FROM ACSMIGRE.VIG_COBERT_CERT_REC@DESA
UNION ALL
SELECT 'ASEGURADO', COUNT (*) FROM ACSMIGRE.VIG_ASEGURADO@DESA
UNION ALL
SELECT 'ASEGURADO_REC', COUNT (*) FROM ACSMIGRE.VIG_ASEGURADO_REC@DESA
UNION ALL
SELECT 'COBERT_ASEG', COUNT (*) FROM ACSMIGRE.VIG_COBERT_ASEG@DESA
UNION ALL
SELECT 'COBERT_ASEG_REC', COUNT (*) FROM ACSMIGRE.VIG_COBERT_ASEG_REC@DESA
UNION ALL
SELECT 'BIEN_CERT', COUNT (*) FROM ACSMIGRE.VIG_BIEN_CERT@DESA
UNION ALL
SELECT 'COBERT_BIEN', COUNT (*) FROM ACSMIGRE.VIG_COBERT_BIEN@DESA
UNION ALL
SELECT 'COBERT_BIEN_REC', COUNT (*) FROM ACSMIGRE.VIG_COBERT_BIEN_REC@DESA
UNION ALL
SELECT 'GEN_REA', COUNT (*) FROM ACSMIGRE.VIG_GEN_REA@DESA
UNION ALL
SELECT 'DIST_REA', COUNT (*) FROM ACSMIGRE.VIG_DIST_REA@DESA
UNION ALL
SELECT 'DIST_FACULT', COUNT (*) FROM ACSMIGRE.VIG_DIST_FACULT@DESA
UNION ALL
SELECT 'DIAS_GAR_PAGO', COUNT (*) FROM ACSMIGRE.VIG_DIAS_GAR_PAGO@DESA
UNION ALL
SELECT 'CERT_VEH', COUNT (*) FROM ACSMIGRE.VIG_CERT_VEH@DESA
UNION ALL
SELECT 'COND_VEH', COUNT (*) FROM ACSMIGRE.VIG_COND_VEH@DESA
UNION ALL
SELECT 'DIREC_COBROPOLIZA', COUNT (*) FROM ACSMIGRE.VIG_DIREC_COBROPOLIZA@DESA;