DECLARE
	CURSOR CUR_ACTUALIZA
	IS
	SELECT DISTINCT A.*
	FROM AF_RIESGOS_CUBIERTOS A,(
		SELECT DISTINCT NUMREC, NUMCERT FROM RECIBO
		WHERE IDEPOL = 9566
		AND STSREC <> 'ANU'
		AND TIPOOPE NOT IN ('MIG', 'DEV')
	) B
	WHERE A.RECIBO = B.NUMREC
	AND A.NU_CERTIFICADO = B.NUMCERT
	AND A.STATUS_COBERTURA = '*';
BEGIN
	FOR I IN CUR_ACTUALIZA
	LOOP
		UPDATE AF_RIESGOS_CUBIERTOS
		SET STATUS_COBERTURA = ' '
		WHERE CD_SUCURSAL = I.CD_SUCURSAL
		AND CD_RAMO = I.CD_RAMO
		AND NU_POLIZA = I.NU_POLIZA
		AND NU_CERTIFICADO = I.NU_CERTIFICADO
		AND CD_COBERTURA = I.CD_COBERTURA
		AND RECIBO = I.RECIBO;
	END LOOP;
END;