SELECT RAMO, POLIZA, CCLI1, CCLI2, NOMTABLA FROM (
	SELECT RAMO, POLIZA, CCLI1, CCLI2, 'EQ_HJPF01' NOMTABL
	FROM EQ_HJPF01
	WHERE TRIM (TIPOID) IS NULL
	OR TRIM (NUMID) IS NULL
	OR TRIM (DVID) IS NULL
	OR TRIM (CODCLI) IS NULL
	OR TRIM (INDNACIONAL) IS NULL
	UNION ALL
	SELECT RAMO, POLIZA, CCLI1, CCLI2, 'EQ_HJPF205'
	FROM EQ_HJPF205
	WHERE TRIM (TIPOID) IS NULL
	OR TRIM (NUMID) IS NULL
	OR TRIM (DVID) IS NULL
	OR TRIM (CODCLI) IS NULL
	OR TRIM (INDNACIONAL) IS NULL
	UNION ALL
	SELECT 0, 0, CCLI1, CCLI2, 'EQ_FNPF01'
	FROM EQ_FNPF01
	WHERE TRIM (TIPOID) IS NULL
	OR TRIM (NUMID) IS NULL
	OR TRIM (DVID) IS NULL
	OR TRIM (CODCLI) IS NULL
	OR TRIM (INDNACIONAL) IS NULL
	UNION ALL
	SELECT 0, 0, '0', RIF, 'EQ_ORDENE'
	FROM EQ_ORDENE
	WHERE TRIM (TIPOID) IS NULL
	OR TRIM (NUMID) IS NULL
	OR TRIM (DVID) IS NULL
	OR TRIM (CODCLI) IS NULL
	OR TRIM (INDNACIONAL) IS NULL
	UNION ALL
	SELECT 0, 0, TIPIDE, RIF, 'EQ_ORPF06'
	FROM EQ_ORPF06
	WHERE TRIM (TIPOID) IS NULL
	OR TRIM (NUMID) IS NULL
	OR TRIM (DVID) IS NULL
	OR TRIM (CODCLI) IS NULL
	OR TRIM (INDNACIONAL) IS NULL
	UNION ALL
	SELECT RAMO,POLIZA,'0', CEDBEN, 'EQ_CLPF07' FROM EQ_CLPF07
	WHERE TRIM (TIPOID) IS NULL
	OR TRIM (NUMID) IS NULL
	OR TRIM (DVID) IS NULL
	OR TRIM (CODCLI) IS NULL
	OR TRIM (INDNACIONAL) IS NULL
	UNION ALL
	SELECT RAMO, POLIZA, '0', CEDBEN, 'EQ_HJPF06' FROM EQ_HJPF06
	WHERE TRIM (TIPOID) IS NULL
	OR TRIM (NUMID) IS NULL
	OR TRIM (DVID) IS NULL
	OR TRIM (CODCLI) IS NULL
	OR TRIM (INDNACIONAL) IS NULL
)
GROUP BY RAMO, POLIZA, CCLI1, CCLI2, NOMTABLA
ORDER BY RAMO, POLIZA, CCLI1, CCLI2, NOMTABLA;