DROP TABLE HJPF01_NM2;
CREATE TABLE HJPF01_NM2 AS (SELECT * FROM HJPF01_NM2@SQLDESARROLLODSN);
--
DROP TABLE HJPF02_NM2;
CREATE TABLE HJPF02_NM2 AS (SELECT * FROM HJPF02_NM2@SQLDESARROLLODSN);
--
DROP TABLE HJPF05_NM2;
CREATE TABLE HJPF05_NM2 AS (SELECT * FROM HJPF05_NM2@SQLDESARROLLODSN);
--
DROP TABLE CLPF40_NM2;
CREATE TABLE CLPF40_NM2 AS (SELECT * FROM CLPF40_NM2@SQLDESARROLLODSN);
--
DROP TABLE REPF14_NM2;
CREATE TABLE REPF14_NM2 AS (SELECT * FROM REPF14_NM2@SQLDESARROLLODSN);
--
DROP TABLE REPF15_NM2;
CREATE TABLE REPF15_NM2 AS (SELECT * FROM REPF15_NM2@SQLDESARROLLODSN);
--
DROP TABLE MIGCARTEI_NM;
CREATE TABLE MIGCARTEI_NM AS (SELECT * FROM MIGCARTEI_NM@SQLDESARROLLODSN);
--
DROP TABLE HJPF01_NM;
CREATE TABLE HJPF01_NM AS (SELECT * FROM HJPF01_NM@SQLDESARROLLODSN);
--
DROP TABLE HJPF02_NM;
CREATE TABLE HJPF02_NM AS (SELECT * FROM HJPF02_NM@SQLDESARROLLODSN);
--
DROP TABLE HJPF05_NM;
CREATE TABLE HJPF05_NM AS (SELECT * FROM HJPF05_NM@SQLDESARROLLODSN);
--
DROP TABLE CLPF40_NM;
CREATE TABLE CLPF40_NM AS (SELECT * FROM CLPF40_NM@SQLDESARROLLODSN);