DROP TABLE HJPF01_REN;
CREATE TABLE HJPF01_REN AS (SELECT * FROM HJPF01_REN@SQLDESARROLLODSN);
--
DROP TABLE HJPF02_REN;
CREATE TABLE HJPF02_REN AS (SELECT * FROM HJPF02_REN@SQLDESARROLLODSN);
--
DROP TABLE HJPF05_REN;
CREATE TABLE HJPF05_REN AS (SELECT * FROM HJPF05_REN@SQLDESARROLLODSN);
--
DROP TABLE SIPF01_REN;
CREATE TABLE SIPF01_REN AS (SELECT * FROM SIPF01_REN@SQLDESARROLLODSN);
--
DROP TABLE SIPF07_REN;
CREATE TABLE SIPF07_REN AS (SELECT * FROM SIPF07_REN@SQLDESARROLLODSN);
--
DROP TABLE CLPF05_REN;
CREATE TABLE CLPF05_REN AS (SELECT * FROM CLPF05_REN@SQLDESARROLLODSN);
--
DROP TABLE CLPF07_REN;
CREATE TABLE CLPF07_REN AS (SELECT * FROM CLPF07_REN@SQLDESARROLLODSN);
--
DROP TABLE CLPF08_REN;
CREATE TABLE CLPF08_REN AS (SELECT * FROM CLPF08_REN@SQLDESARROLLODSN);
--
CREATE INDEX MIGRA.IDX_CLPF05_REN_02 ON MIGRA.CLPF05_REN (
	RAMO, POLIZA, CODPLA
)
	LOGGING
	TABLESPACE AS400_DAT
	PCTFREE 10
	INITRANS 2
	MAXTRANS 255
	STORAGE (
		INITIAL 64 K
		MINEXTENTS 1
		MAXEXTENTS UNLIMITED
		PCTINCREASE 0
		BUFFER_POOL DEFAULT
	)
	NOPARALLEL;
--	
CREATE INDEX MIGRA.PK_CLPF05_REN ON MIGRA.CLPF05_REN (
	TIPOPR, RAMO, POLIZA, NUMCER, CORRE, COFAAM
)
	LOGGING
	TABLESPACE AS400_INDEX
	PCTFREE 10
	INITRANS 2
	MAXTRANS 255
	STORAGE (
		INITIAL 64 K
		MINEXTENTS 1
		MAXEXTENTS UNLIMITED
		PCTINCREASE 0
		BUFFER_POOL DEFAULT
	)
	NOPARALLEL;
--
CREATE INDEX MIGRA.PK_CLPF05_REN_1 ON MIGRA.CLPF05_REN (
	RAMO, POLIZA, NUMCER, COFAAM
)
	LOGGING
	TABLESPACE AS400_INDEX
	PCTFREE 10
	INITRANS 2
	MAXTRANS 255
	STORAGE (
		INITIAL 64 K
		MINEXTENTS 1
		MAXEXTENTS UNLIMITED
		PCTINCREASE 0
		BUFFER_POOL DEFAULT
	)
	NOPARALLEL;
--
CREATE INDEX MIGRA.PK_CLPF05_REN_2 ON MIGRA.CLPF05_REN (RAMO, POLIZA, NUMCER)
	LOGGING
	TABLESPACE AS400_INDEX
	PCTFREE 10
	INITRANS 2
	MAXTRANS 255
	STORAGE (
		INITIAL 64 K
		MINEXTENTS 1
		MAXEXTENTS UNLIMITED
		PCTINCREASE 0
		BUFFER_POOL DEFAULT
	)
	NOPARALLEL;
--
CREATE INDEX MIGRA.PK_CLPF05_REN_3 ON MIGRA.CLPF05_REN (RAMO, POLIZA)
	LOGGING
	TABLESPACE AS400_INDEX
	PCTFREE 10
	INITRANS 2
	MAXTRANS 255
	STORAGE (
		INITIAL 64 K
		MINEXTENTS 1
		MAXEXTENTS UNLIMITED
		PCTINCREASE 0
		BUFFER_POOL DEFAULT
	)
	NOPARALLEL;
--
CREATE INDEX MIGRA.PK_CLPF05_REN_4 ON MIGRA.CLPF05_REN (RAMO, POLIZA, COFAAM)
	LOGGING
	TABLESPACE AS400_INDEX
	PCTFREE 10
	INITRANS 2
	MAXTRANS 255
	STORAGE (
		INITIAL 64 K
		MINEXTENTS 1
		MAXEXTENTS UNLIMITED
		PCTINCREASE 0
		BUFFER_POOL DEFAULT
	)
	NOPARALLEL;