SELECT * FROM error_transferencia_totalfast WHERE descerror || referencia LIKE '%32937421%';
SELECT * FROM siniestro WHERE numsin = 32937421;
SELECT * FROM SINT_SINIESTROS WHERE sisi_nu_siniestro =  32937421;
--
SELECT * FROM SINT_LIQUIDACIONES WHERE SILI_NU_CONTROL_FACTURA IS NULL AND SILI_FE_FACTURA IS NULL AND AVISO_CIA = 1;
SELECT * FROM SINT_LIQUIDACIONES WHERE SILI_SISI_NU_SINIESTRO = 32945051  AND AVISO_CIA = 1;
SELECT * FROM AF_CTRL_LIQUIDACIONES WHERE AF_SILI_SISI_NU_SINIESTRO = 32952334;
SELECT * FROM SINT_CERTIFICADOS_SINIESTROS WHERE SICE_SISI_NU_SINIESTRO =32934294;
--
SELECT * FROM SINT_RESERVA_COBERTURA_CERTIFI WHERE SICC_SICO_SISI_NU_SINIESTRO = 32945367;
SELECT * FROM SINT_LIQUIDACION_COBERTURAS_CE WHERE SLCC_SILI_SISI_NU_SINIESTRO = 32945367;
SELECT * FROM SINT_MOVIMIENTOS_COBERTURAS_CE WHERE SMCC_SIMS_SISI_NU_SINIESTRO = 32945367;
SELECT AF_CJEG_ST_EGRESO, COUNT (*) FROM AF_CTRL_LIQUIDACIONES GROUP BY AF_CJEG_ST_EGRESO;
--
SELECT B.* FROM AF_CTRL_LIQUIDACIONES A, SINT_SINIESTROS B 
WHERE AF_CJEG_ST_EGRESO = 6
AND A.AF_SILI_SISI_NU_SINIESTRO = 32946306
AND A.AF_SILI_SISI_NU_SINIESTRO = B.sisi_nu_siniestro
AND SISI_FE_OCURRENCIA > '01/06/2013';
--
SELECT * FROM AF_CTRL_RESERVA_COBERTURA_CERT WHERE AF_SICC_SICO_SISI_NU_SINIESTRO = 33910628;
--
UPDATE fact_iva
SET numero = numero || '-'
WHERE numoblig = (
	SELECT NUMOBLIG FROM APROB_SIN
	WHERE NUMAPROB = 1251241
);
--
SELECT * FROM FACT_IVA
WHERE NUMOBLIG = (
	SELECT NUMOBLIG FROM APROB_SIN 
	WHERE NUMAPROB = 1251241
);
--
SELECT * FROM aprob_sin
WHERE idesin = (
	SELECT idesin FROM siniestro 
	WHERE numsin =32948570
);
--
SELECT * FROM cob_res_gen
WHERE idesin = (
	SELECT idesin FROM siniestro 
	WHERE numsin = 32950602
);
--
SELECT * FROM COB_RES_MOD WHERE idesin = (SELECT idesin FROM siniestro WHERE numsin = 33910628);
SELECT * FROM tercero WHERE numid = 70116200;
SELECT * FROM det_aprob WHERE ideres IN (2961081, 2961082);
--
UPDATE SINT_LIQUIDACIONES
SET SILI_CD_NACIONALIDAD = 'J' 
WHERE SILI_NU_CEDULA = 7010936 
AND SILI_CD_NACIONALIDAD = 'V';