DECLARE
	CURSOR CUR
	IS
	SELECT DISTINCT
			NUMREC RECIBO_ASCEL,
			STSREC,
			RE.FECINIVIG FECINIVIG_R,
			RE.FECFINVIG FECFINVIG_R,
			TIPOOPE
		FROM RECIBO RE,
			(SELECT DISTINCT IT.*, PO.IDEPOL FROM POLIZA PO,
				(SELECT DISTINCT
						B.SICE_COD_PRODUCTO PROD,
						B.SICE_CACE_CAPO_NU_POLIZA POLIZA,
						B.SICE_CACE_NU_CERTIFICADO NUMCERT,
						B.SICE_CARE_CASU_CD_SUCURSAL SUCURSAL,
						B.SICE_SISI_NU_SINIESTRO SINIESTRO,
						TO_DATE (A.SISI_FE_OCURRENCIA, 'DD/MM/RRRR') FECOCURRE_S,
						B.SICE_CARE_NU_RECIBO RECIBO_INT
					FROM SINT_SINIESTROS A, SINT_CERTIFICADOS_SINIESTROS B, AF_CTRL_RESERVA_COBERTURA_CERT C
					WHERE A.SISI_CASU_CD_SUCURSAL = B.SICE_SISI_CASU_CD_SUCURSAL
					AND A.SISI_NU_SINIESTRO = B.SICE_SISI_NU_SINIESTRO
					AND A.SISI_CASU_CD_SUCURSAL = AF_SICC_SISI_CASU_CD_SUCURSAL
					AND A.SISI_NU_SINIESTRO = C.AF_SICC_SICO_SISI_NU_SINIESTRO
					AND B.SICE_CACE_NU_CERTIFICADO = C.AF_SICC_CACE_NU_CERTIFICADO
					AND B.SICE_CARE_NU_RECIBO = C.AF_RECIBO
				) IT
				WHERE PO.CODPOL = IT.PROD
				AND PO.NUMPOL = IT.POLIZA
				AND PO.CODOFIEMI = SUCURSAL
				AND IT.FECOCURRE_S >= PO.FECINIVIG
				AND IT.FECOCURRE_S <= PO.FECFINVIG
			) IT2
         WHERE RE.IDEPOL = IT2.IDEPOL
		 AND RE.NUMCERT = IT2.NUMCERT
		 AND STSREC <> 'MIG'
		 AND IT2.FECOCURRE_S >= RE.FECINIVIG
		 AND IT2.FECOCURRE_S <= RE.FECFINVIG
		 AND NUMREC <> IT2.RECIBO_INT
		 AND STSREC NOT IN ('ANU', 'GEN')
		 AND tipoope NOT IN ('DEV')
      ORDER BY 1,2,3,4,5,6,7,8,9,10,11,12,13;
BEGIN
	FOR I IN CUR
	LOOP
		UPDATE SINT_CERTIFICADOS_SINIESTROS
		SET SICE_CARE_NU_RECIBO = I.RECIBO_ASCEL
		WHERE SICE_CACE_CAPO_NU_POLIZA = I.POLIZA
		AND SICE_CACE_NU_CERTIFICADO = I.NUMCERT
		AND SICE_CARE_CASU_CD_SUCURSAL = I.SUCURSAL
		AND SICE_CARE_NU_RECIBO = I.RECIBO_INT
		AND SICE_COD_PRODUCTO = I.PROD;
   END LOOP;
END;