BEGIN
	PR_BANSEG.LOAD_FILE ('23092013');
	COMMIT;

	FOR I IN (
		SELECT DISTINCT CODPROVEEDOR, ARCHIVO
		FROM banca_seguro
		WHERE indicador = 'N'
	)
	LOOP
		PR_BANSEG.CREAR_POLIZA (I.CODPROVEEDOR, I.ARCHIVO);
		COMMIT;
	END LOOP;

	FOR I IN (
		SELECT DISTINCT CODPROVEEDOR, ARCHIVO
		FROM BANCA_SEGURO_COB_DEV
		WHERE indicador = 'N'
	)
	LOOP
		PR_BANSEG.COBRAR_DEVOLUCION_POLIZA (I.CODPROVEEDOR, I.ARCHIVO);
		COMMIT;
	END LOOP;
END;