DROP TABLE HJPF01_REN
SELECT A.* INTO HJPF01_REN FROM OPENQUERY(
	DB2400PROD, 'SELECT * FROM LSCADEA.HJPF01'
) A,(
	SELECT DISTINCT RAMO,POLIZA FROM ORAACSELMIGRA..MIGRA.SINIESTROS_MIGRA_REN
)B
WHERE A.RAMO = B.RAMO
AND A.POLIZA = B.POLIZA
--
DROP TABLE HJPF02_REN
SELECT A.* INTO HJPF02_REN FROM OPENQUERY(
	DB2400PROD, 'SELECT * FROM LSCADEA.HJPF02'
)A,(
	SELECT DISTINCT RAMO,POLIZA,NUMREC FROM ORAACSELMIGRA..MIGRA.SINIESTROS_MIGRA_REN
)B
WHERE A.RAMO = B.RAMO
AND A.POLIZA = B.POLIZA
AND A.NUMREC = B.NUMREC
--
DROP TABLE HJPF03_REN
SELECT A.* INTO HJPF03_REN FROM OPENQUERY(
	DB2400PROD, 'SELECT * FROM LSCADEA.HJPF03'
)A,(
	SELECT DISTINCT RAMO,POLIZA,NUMREC FROM ORAACSELMIGRA..MIGRA.SINIESTROS_MIGRA_REN
)B
WHERE A.RAMO = B.RAMO
AND A.POLIZA = B.POLIZA
AND A.NUMREC = B.NUMREC
--
DROP TABLE HJPF05_REN
SELECT A.* INTO HJPF05_REN FROM OPENQUERY(
	DB2400PROD, 'SELECT * FROM LSCADEA.HJPF05'
) A,(
	SELECT DISTINCT RAMO,POLIZA,NUMREC,CODCOB FROM ORAACSELMIGRA..MIGRA.SINIESTROS_MIGRA_REN
)B
WHERE A.RAMO = B.RAMO
AND A.POLIZA = B.POLIZA
AND A.NUMREC = B.NUMREC
AND A.CODCOB = B.CODCOB
--
DROP TABLE SIPF01_REN
SELECT A.* INTO SIPF01_REN FROM OPENQUERY(
	DB2400PROD, 'SELECT * FROM LSCADEA.SIPF01'
) A,(
	SELECT DISTINCT RAMO,POLIZA,SERIE,RECLAM FROM ORAACSELMIGRA..MIGRA.SINIESTROS_MIGRA_REN
) B
WHERE A.RAMO = B.RAMO
AND A.POLIZA = B.POLIZA
AND A.SERIE  = B.SERIE
AND A.RECLAM = B.RECLAM
--
DROP TABLE SIPF07_REN
SELECT A.* INTO SIPF07_REN FROM OPENQUERY(
	DB2400PROD, 'SELECT * FROM LSCADEA.SIPF07'
) A, (
	SELECT DISTINCT RAMO,POLIZA,SERIE,RECLAM,CODCOB FROM ORAACSELMIGRA..MIGRA.SINIESTROS_MIGRA_REN
) B
WHERE A.RAMO = B.RAMO
AND A.POLIZA = B.POLIZA
AND A.SERIE  = B.SERIE
AND A.RECLAM = B.RECLAM
AND A.CODCOB = B.CODCOB
--
SELECT * INTO CLPF05_REN FROM OPENQUERY(DB2400PROD, 'SELECT * FROM LSCADEA.CLPF05')
--
SELECT * INTO CLPF07_REN FROM OPENQUERY(DB2400PROD, 'SELECT * FROM LSCADEA.CLPF07')
--
SELECT * INTO CLPF08_REN FROM OPENQUERY(DB2400PROD, 'SELECT * FROM LSCADEA.CLPF08')
--
SELECT * INTO CLPF53_REN FROM OPENQUERY(DB2400PROD,'SELECT * FROM LSCADEA.CLPF53')
--
SELECT * INTO CLPF08N_REN FROM OPENQUERY(DB2400PROD, 'SELECT * FROM LSCADEA.CLPF08N WHERE CERVEH <> '' ''')
--
DROP TABLE REPF14_REN
SELECT A.* INTO REPF14_REN FROM OPENQUERY(
	DB2400PROD, 'SELECT * FROM LSCADEA.REPF14'
) A, (
	SELECT DISTINCT RAMO,POLIZA,NUMREC FROM ORAACSELMIGRA..MIGRA.SINIESTROS_MIGRA_REN
) B
WHERE A.RAMO = B.RAMO
AND A.POLIZA = B.POLIZA
AND A.STSREC = B.STSREC
AND A.NUMREC = B.NUMREC
--
DROP TABLE REPF15_REN
SELECT A.* INTO REPF15_REN FROM OPENQUERY(
	DB2400PROD, 'SELECT * FROM LSCADEA.REPF15'
) A, (
	SELECT DISTINCT RAMO,POLIZA,NUMREC FROM ORAACSELMIGRA..MIGRA.SINIESTROS_MIGRA_REN
) B
WHERE A.RAMO = B.RAMO
AND A.POLIZA = B.POLIZA
AND A.STSREC = B.STSREC
AND A.NUMREC = B.NUMREC