SELECT COUNT(*) FROM HJPF01_REN
UNION ALL
SELECT COUNT(*) FROM HJPF02_REN
UNION ALL
SELECT COUNT(*) FROM HJPF03_REN
UNION ALL
SELECT COUNT(*) FROM HJPF05_REN
UNION ALL
SELECT COUNT(*) FROM SIPF01_REN
UNION ALL
SELECT COUNT(*) FROM SIPF07_REN
UNION ALL
SELECT COUNT(*) FROM REPF14_REN
UNION ALL
SELECT COUNT(*) FROM REPF15_REN
UNION ALL
SELECT COUNT(*) FROM HJPF01_NM2
UNION ALL
SELECT COUNT(*) FROM HJPF02_NM2
UNION ALL
SELECT COUNT(*) FROM HJPF03_NM2
UNION ALL
SELECT COUNT(*) FROM HJPF05_NM2
UNION ALL
SELECT COUNT(*) FROM CLPF40_NM2
UNION ALL
SELECT COUNT(*) FROM REPF14_NM2
UNION ALL
SELECT COUNT(*) FROM REPF15_NM2