CREATE OR REPLACE PACKAGE MIGRA.MIG_POLIZA_REN
IS
	PROCEDURE GEN_SINIESTRO_MIGRA;
	PROCEDURE GEN_SINIESTRO_MIGRA_DEF;
	PROCEDURE ASIGNA_ERRORES;
	PROCEDURE GEN_EQ_SINIESTRO_REN;
	PROCEDURE GEN_CODCLI;
	PROCEDURE INS_TABLAS_EQ;
	PROCEDURE GEN_EQ_REPF14_REN;
	PROCEDURE INSERTAR_DAT_EQ_REASEGURO_R;
	PROCEDURE MIG_REASEGURO_EG;
	PROCEDURE CERT_VEH_APEP_MIG;
	PROCEDURE COND_VEH_APEP_MIG;
	PROCEDURE DIREC_COBROPOLIZA_MIG;
END MIG_POLIZA_REN;
--
CREATE OR REPLACE PACKAGE BODY MIGRA.MIG_POLIZA_REN
AS
	PROCEDURE GEN_SINIESTRO_MIGRA
	IS
		CURSOR CUR_GENERA
		IS
		SELECT * FROM (
			SELECT DISTINCT
				C.RAMOAS RAMO,C.POLIZAAS POLIZA,C.SERIE SERIE,C.RECLAMAS RECLAM,C.NUMCERTAS NUMCERT,
				C.NUMRECAS NUMREC,C.CODCOBAS CODCOB,'CURSOR_1' "CURSOR",PM.TB_REF_TIPO_SUSCRIPCION (C.RAMOAS) TIPOSUSC
			FROM LOG_SINIESTRO_MIG_EG A,ERR_MIG_SINIESTRO_EG B,EQ_SINIESTRO_EG C
			WHERE A.RAMOAS = B.RAMO
			AND A.POLIZAAS = B.POLIZA
			AND A.SERIE = B.SERIE
			AND A.RECLAMAS = B.RECLAM
			AND A.RAMOAS = C.RAMOAS
			AND A.POLIZAAS = C.POLIZAAS
			AND A.SERIE = C.SERIE
			AND A.RECLAMAS = C.RECLAMAS
			AND B.SERIE <= 2011
			AND A.MIGRA = 'N'
			AND A.ESTATUS = 'REC'
			AND B.TIPOERROR = 'ERR-COMP-SIN'
			AND B.CODERROR IN ('001','002')
		) A
		WHERE EXISTS (
			SELECT DISTINCT RAMO,POLIZA
			FROM HJPF01 B
			WHERE A.RAMO = B.RAMO
			AND A.POLIZA = B.POLIZA
		)
		UNION ALL
		SELECT DISTINCT
			C.RAMO,C.POLIZA,A.SERIE,A.RECLAMAS,A.NUMCERTAS NUMCERT,C.NUMREC,A.CODCOBAS CODCOB,
			'CURSOR_2' "CURSOR",PM.TB_REF_TIPO_SUSCRIPCION (C.RAMO) TIPOSUSC
		FROM EQ_SINIESTRO_EG A,LOG_SINIESTRO_MIG_EG B,MIGCARTEI C
		WHERE A.RAMOAS = B.RAMOAS(+)
		AND A.POLIZAAS = B.POLIZAAS(+)
		AND A.SERIE = B.SERIE(+)
		AND A.RECLAMAS = B.RECLAMAS(+)
		AND A.RAMOAS = C.RAMO(+)
		AND A.POLIZAAS = C.POLIZA(+)
		AND A.NUMRECAS = C.NUMREC(+)
		AND B.MIGRA = 'N'
		AND C.MIGRA = 'N'
		AND A.SERIE >= 2012
		AND C.OBSERV != 'POLIZAS DE BANCA SEGUROS'
		UNION ALL
		SELECT DISTINCT
			A.RAMOAS RAMO,A.POLIZAAS POLIZA,A.SERIE SERIE,A.RECLAMAS RECLAM,A.NUMCERTAS NUMCERT,
			A.NUMRECAS NUMREC,A.CODCOBAS CODCOB,'CURSOR_3' "CURSOR",PM.TB_REF_TIPO_SUSCRIPCION (A.RAMOAS) TIPOSUSC
		FROM EQ_SINIESTRO_EG A,LOG_SINIESTRO_MIG_EG B
		WHERE A.RAMOAS = B.RAMOAS(+)
		AND A.POLIZAAS = B.POLIZAAS(+)
		AND A.SERIE = B.SERIE(+)
		AND A.RECLAMAS = B.RECLAMAS(+)
		AND A.NUMRECAS = B.NUMRECAS(+)
		AND A.SERIE <= 2011
		AND B.MIGRA = 'N';
		--
		INDEXISTE	NUMBER;
	BEGIN
		EXECUTE IMMEDIATE 'TRUNCATE TABLE SINIESTROS_MIGRA_REN';

		FOR I IN CUR_GENERA
		LOOP
			IF I.RAMO NOT IN (1,21,24,26) THEN
				INSERT INTO SINIESTROS_MIGRA_REN (
					RAMO,POLIZA,SERIE,RECLAM,NUMCERT,NUMREC,CODCOB,CURSOR,TIPOSUSC,APTO,RAZONAPTO
				)
				VALUES (
					I.RAMO,I.POLIZA,I.SERIE,I.RECLAM,I.NUMCERT,I.NUMREC,I.CODCOB,I.CURSOR,I.TIPOSUSC,'S','N/A'
				);
				COMMIT;
			END IF;
		END LOOP;
		--
		FOR I IN (
			SELECT DISTINCT RAMO,POLIZA,NUMREC,NUMCERT
			FROM SINIESTROS_MIGRA_REN
		)
		LOOP
			UPDATE SINIESTROS_MIGRA_REN
			SET
			FECINIVIG = PM.CONVIERTE_DIAMESANO_FECHA (
				(SELECT DIADES FROM HJPF02_REN WHERE RAMO = I.RAMO AND POLIZA = I.POLIZA AND NUMREC = I.NUMREC),
				(SELECT MESDES FROM HJPF02_REN WHERE RAMO = I.RAMO AND POLIZA = I.POLIZA AND NUMREC = I.NUMREC),
				(SELECT ANODES FROM HJPF02_REN WHERE RAMO = I.RAMO AND POLIZA = I.POLIZAAND NUMREC = I.NUMREC)
			),
			FECFINVIG = PM.CONVIERTE_DIAMESANO_FECHA (
				(SELECT DIAHAS FROM HJPF02_REN WHERE RAMO = I.RAMO AND POLIZA = I.POLIZA AND NUMREC = I.NUMREC),
				(SELECT MESHAS FROM HJPF02_REN WHERE RAMO = I.RAMO AND POLIZA = I.POLIZA AND NUMREC = I.NUMREC),
				(SELECT ANOHAS FROM HJPF02_REN WHERE RAMO = I.RAMO AND POLIZA = I.POLIZA AND NUMREC = I.NUMREC)
			),
			FECEMI = PM.CONVIERTE_DIAMESANO_FECHA (
				(SELECT DIAEMI FROM HJPF02_REN WHERE RAMO = I.RAMO AND POLIZA = I.POLIZA AND NUMREC = I.NUMREC),
				(SELECT MESEMI FROM HJPF02_REN WHERE RAMO = I.RAMO AND POLIZA = I.POLIZA AND NUMREC = I.NUMREC),
				(SELECT ANOEMI FROM HJPF02_REN WHERE RAMO = I.RAMO AND POLIZA = I.POLIZA AND NUMREC = I.NUMREC)
			),
			FECINIVALID = PM.CONVIERTE_DIAMESANO_FECHA (
				(SELECT DIADES FROM HJPF02_REN WHERE RAMO = I.RAMO AND POLIZA = I.POLIZA AND NUMREC = I.NUMREC),
				(SELECT MESDES FROM HJPF02_REN WHERE RAMO = I.RAMO AND POLIZA = I.POLIZA AND NUMREC = I.NUMREC),
				(SELECT ANODES FROM HJPF02_REN WHERE RAMO = I.RAMO AND POLIZA = I.POLIZA AND NUMREC = I.NUMREC)
			),
			FECFINVALID = PM.CONVIERTE_DIAMESANO_FECHA (
				(SELECT DIAHAS FROM HJPF02_REN WHERE RAMO = I.RAMO AND POLIZA = I.POLIZA AND NUMREC = I.NUMREC),
				(SELECT MESHAS FROM HJPF02_REN WHERE RAMO = I.RAMO AND POLIZA = I.POLIZA AND NUMREC = I.NUMREC),
				(SELECT ANOHAS FROM HJPF02_REN WHERE RAMO = I.RAMO AND POLIZA = I.POLIZA AND NUMREC = I.NUMREC)
			),
			NUMREN = PM.calcula_numero_renovaciones ( PM.CONVIERTE_DIAMESANO_FECHA (
				(SELECT DIADES FROM HJPF02_REN WHERE RAMO = I.RAMO AND POLIZA = I.POLIZA AND NUMREC = I.NUMREC),
				(SELECT MESDES FROM HJPF02_REN WHERE RAMO = I.RAMO AND POLIZA = I.POLIZA AND NUMREC = I.NUMREC),
				(SELECT ANODES FROM HJPF02_REN WHERE RAMO = I.RAMO AND POLIZA = I.POLIZA AND NUMREC = I.NUMREC)
			),(SELECT PM.CONVIERTE_DIAMESANO_FECHA (DIACOM,MESCOM,ANOCOM)
				FROM HJPF01_REN
				WHERE RAMO = I.RAMO
				AND POLIZA = I.POLIZA)
			)
			WHERE RAMO = I.RAMO
			AND POLIZA = I.POLIZA
			AND NUMREC = I.NUMREC;
			COMMIT;
			--
			UPDATE SINIESTROS_MIGRA_REN
			SET FECING = (
				SELECT PM.CONVIERTE_DIAMESANO_FECHA (DIAING,MESING,ANOING)
				FROM CLPF05_REN
				WHERE RAMO = I.RAMO
				AND POLIZA = I.POLIZA
				AND NUMCER = LPAD (I.NUMCERT,10,0)
				UNION ALL
				SELECT PM.CONVIERTE_DIAMESANO_FECHA (DIAING,MESING,ANOING)
				FROM CLPF07_REN
				WHERE RAMO = I.RAMO
				AND POLIZA = I.POLIZA
				AND CERVEH = I.NUMCERT
			)
			WHERE RAMO = I.RAMO
			AND POLIZA = I.POLIZA
			AND NUMCERT = I.NUMCERT;
			COMMIT;
		END LOOP;
		--
		FOR I IN (
			SELECT ROWID FROM SINIESTROS_MIGRA_REN
			WHERE FECING IS NULL
			AND TIPOSUSC = 'I'
		)
		LOOP
			UPDATE SINIESTROS_MIGRA_REN
			SET FECING = FECEMI
			WHERE ROWID = I.ROWID;
			COMMIT;
			--
			UPDATE SINIESTROS_MIGRA_REN
			SET NUMCERT = 1
			WHERE ROWID = I.ROWID
			AND NUMCERT IS NULL;
		END LOOP;
		--
		UPDATE SINIESTROS_MIGRA_REN A
		SET CODCOB = (
			SELECT DISTINCT CODCOB
			FROM SIPF07_REN B
			WHERE A.RAMO = B.RAMO
			AND A.POLIZA = B.POLIZA
			AND A.SERIE = B.SERIE
			AND A.RECLAM = B.RECLAM
		)
		WHERE CODCOB = 0;
		COMMIT;
		--
		UPDATE SINIESTROS_MIGRA_REN
		SET APTO = 'N',RAZONAPTO = 'No tiene NUMCERT'
		WHERE APTO = 'S'
		AND NUMCERT IS NULL;
		COMMIT;
		--
		UPDATE SINIESTROS_MIGRA_REN
		SET APTO = 'N',RAZONAPTO = 'CODCOB en Cero(0)'
		WHERE APTO = 'S' AND CODCOB = 0;
		COMMIT;
		--
		UPDATE SINIESTROS_MIGRA_REN
		SET APTO = 'N',RAZONAPTO = 'NO tiene Fechas o Fechas Erronea'
		WHERE APTO = 'S'
		AND (
			FECEMI IS NULL OR 
			FECINIVALID IS NULL OR
			FECFINVALID IS NULL OR
			FECINIVIG IS NULL OR
			FECFINVIG IS NULL OR
			FECING IS NULL
		);
		COMMIT;
	END GEN_SINIESTRO_MIGRA;
	--
	PROCEDURE GEN_SINIESTRO_MIGRA_DEF
	IS
		CURSOR CUR_GENERA_TAB
		IS
		SELECT
			A.RAMO,A.POLIZA,A.SERIE,A.RECLAM,A.CODCOB,A.CODBE,'S' MIGRA,'N/A' RAZONMIGRA,B.NUMCERT NUMCERT,
			B.NUMREC NUMREC,MAX (B.FECEMI) FECEMI,MAX (B.FECINIVALID) FECINIVALID,MAX (B.FECFINVALID) FECFINVALID,
			MAX (B.FECINIVIG) FECINIVIG,MAX (B.FECFINVIG) FECFINVIG,MAX (FECING) FECING,B.NUMREN,MAX (B.TIPOSUSC) TIPOSUSC
		FROM SIPF07_REN A,SINIESTROS_MIGRA_REN B
		WHERE A.RAMO = B.RAMO
		AND A.POLIZA = B.POLIZA
		AND A.SERIE = B.SERIE
		AND A.RECLAM = B.RECLAM
		AND A.CODCOB = B.CODCOB
		AND B.APTO = 'S'
		GROUP BY A.RAMO,A.POLIZA,A.SERIE,A.RECLAC,A.RECLAM,A.CODCOB,A.CODBE,B.NUMCERT,B.NUMREC,B.NUMREN;
		--
	BEGIN
		EXECUTE IMMEDIATE 'TRUNCATE TABLE EQ_SINIESTRO_REN';
		--
		FOR I IN CUR_GENERA_TAB
		LOOP
			INSERT INTO EQ_SINIESTRO_REN (
				RAMO,POLIZA,SERIE,RECLAM,CODCOB,CODBE,MIGRA,RAZONMIGRA,NUMCERT,NUMREC,
				FECEMI,FECINIVALID,FECFINVALID,FECINIVIG,FECFINVIG,FECING,NUMREN,TIPOSUSC
			)
			VALUES (
				I.RAMO,I.POLIZA,I.SERIE,I.RECLAM,I.CODCOB,I.CODBE,I.MIGRA,I.RAZONMIGRA,I.NUMCERT,I.NUMREC,
				I.FECEMI,I.FECINIVALID,I.FECFINVALID,I.FECINIVIG,I.FECFINVIG,I.FECING,I.NUMREN,I.TIPOSUSC
			);
			COMMIT;
		END LOOP;
	END GEN_SINIESTRO_MIGRA_DEF;
	--
	PROCEDURE ASIGNA_ERRORES
	IS
		V_CODRAMOCERT 	EQ_SINIESTRO_REN.CODRAMOCERT%TYPE;
		V_CODCOBERT		EQ_SINIESTRO_REN.CODCOBERT%TYPE;
		V_CLASEBIEN		EQ_SINIESTRO_REN.CLASEBIEN%TYPE;
		V_CODBIEN		EQ_SINIESTRO_REN.CODBIEN%TYPE;
		V_BIECOB		EQ_SINIESTRO_REN.BIECOB%TYPE;
	BEGIN
		FOR I IN (
			SELECT DISTINCT RAMO,POLIZA,NUMREC,CODCOB,CODBE
			FROM EQ_SINIESTRO_REN
			WHERE MIGRA = 'S'
		)
		LOOP
			BEGIN
				SELECT BIECOB INTO V_BIECOB
				FROM HJPF05_REN
				WHERE RAMO = I.RAMO
				AND POLIZA = I.POLIZA
				AND NUMREC = I.NUMREC
				AND CODCOB = I.CODCOB;
				--
				UPDATE EQ_SINIESTRO_REN
				SET BIECOB = V_BIECOB
				WHERE MIGRA = 'S'
				AND RAMO = I.RAMO
				AND POLIZA = I.POLIZA
				AND NUMREC = I.NUMREC
				AND CODCOB = I.CODCOB;
			EXCEPTION WHEN OTHERS THEN
				BEGIN
					SELECT BIECOB INTO V_BIECOB
					FROM HJPF05_REN
					WHERE RAMO = I.RAMO
					AND POLIZA = I.POLIZA
					AND NUMREC = I.NUMREC
					AND CODCOB = I.CODCOB
					AND BIECOB = I.CODBE;
				EXCEPTION WHEN OTHERS THEN
					UPDATE EQ_SINIESTRO_REN
					SET BIECOB = V_BIECOB
					WHERE MIGRA = 'S'
					AND RAMO = I.RAMO
					AND POLIZA = I.POLIZA
					AND NUMREC = I.NUMREC
					AND CODCOB = I.CODCOB
					AND CODBE = I.CODBE;
					COMMIT;
				END;
			END;
		END LOOP;
		--
		FOR I IN (
			SELECT DISTINCT RAMO,POLIZA,CODCOB,BIECOB
			FROM EQ_SINIESTRO_REN
			WHERE MIGRA = 'S'
		)
		LOOP
			BEGIN
				SELECT CODRAMO,CODCOBERT,CODBIEN INTO V_CODRAMOCERT,V_CODCOBERT,V_CLASEBIEN
				FROM ACSEL.BIENES_MIG@CERT
				WHERE RAMO = I.RAMO
				AND TO_NUMBER (BIEN) = TO_NUMBER (I.BIECOB)
				AND CODCOB = I.CODCOB;
			EXCEPTION WHEN NO_DATA_FOUND THEN
				BEGIN
					SELECT CODRAMO,CODCOBERT INTO V_CODRAMOCERT,V_CODCOBERT
					FROM ACSEL.RAMOS_MIG@CERT
					WHERE RAMO = I.RAMO
					AND CODCOB = I.CODCOB;
				EXCEPTION WHEN NO_DATA_FOUND THEN
					V_CODRAMOCERT := NULL;
					V_CODCOBERT := NULL;
				END;
			END;
			--
			IF V_CLASEBIEN IS NULL THEN
				V_CLASEBIEN := '000';
			END IF;
			--
			UPDATE EQ_SINIESTRO_REN
			SET CODRAMOCERT = V_CODRAMOCERT,
				CODCOBERT = V_CODCOBERT,
				CLASEBIEN = V_CLASEBIEN,
				CODBIEN = '000'
			WHERE MIGRA = 'S'
			AND RAMO = I.RAMO
			AND POLIZA = I.POLIZA
			AND CODCOB = I.CODCOB
			AND BIECOB = I.BIECOB;
			COMMIT;
			--
		END LOOP;
		--
		UPDATE EQ_SINIESTRO_REN
		SET MIGRA = 'N',RAZONMIGRA = 'No tiene CODRAMOCERT'
		WHERE MIGRA = 'S' AND CODRAMOCERT IS NULL;
		COMMIT;
		--
		UPDATE EQ_SINIESTRO_REN
		SET MIGRA = 'N',RAZONMIGRA = 'No tiene CODCOBERT'
		WHERE MIGRA = 'S' AND CODCOBERT IS NULL;
		COMMIT;
		--
		UPDATE EQ_SINIESTRO_REN
		SET MIGRA = 'N',RAZONMIGRA = 'No tiene CLASEBIEN'
		WHERE MIGRA = 'S'
		AND CLASEBIEN = '000'
		AND RAMO IN (
			SELECT TO_NUMBER (ACARGU) FROM CTRALTAB
			WHERE ACTIAR = 4852 AND TRIM (ACARGU) <> '**'
		);
		COMMIT;
	END ASIGNA_ERRORES;
	--
	PROCEDURE GEN_EQ_SINIESTRO_REN
	IS
		V_CODPROD 			EQ_SINIESTRO_REN.CODPROD%TYPE;
		V_CODPLAN 			EQ_SINIESTRO_REN.CODPLAN%TYPE;
		V_REVPLAN			EQ_SINIESTRO_REN.REVPLAN%TYPE;
		V_PRIMAMONEDA		EQ_SINIESTRO_REN.PRIMAMONEDA%TYPE;
		V_SUMAASEGMONEDA	EQ_SINIESTRO_REN.SUMAASEGMONEDA%TYPE;
		V_STSREC			EQ_SINIESTRO_REN.STSREC%TYPE;
		V_TIPOMOV			ACSMIGRE.VIG_RECIBO.TIPOMOV@DESA%TYPE;
	BEGIN
		FOR I IN (
			SELECT DISTINCT RAMO,POLIZA FROM EQ_SINIESTRO_REN
			WHERE MIGRA = 'S'
		)
		LOOP
			v_CODPROD := NULL;
			V_CODPLAN := NULL;
			V_REVPLAN := NULL;
			--
			PM.ASIGNA_PRODUCTO_PLAN (
				nRamo		=> I.RAMO,
				nPoliza		=> I.POLIZA,
				nNumCer		=> NULL,
				cCodProd	=> v_CODPROD,
				cCodPlan	=> V_CODPLAN,
				cRevPlan	=> V_REVPLAN
			);
			--
			UPDATE EQ_SINIESTRO_REN
			SET CODPLAN = '999',
				REVPLAN = '999',
				STSPOL = 'REN',
				CLASERIESGO = '01',
				STSCOBERT = 'ACT',
				CODPARENT = '0001',
				DESCCERT = 'ACTIVO',
				STSBIEN = 'ACT',
				STSCERT = 'REN',
				CODPROD = V_CODPROD,
				TIPOVIG = PM.TB_REF_TIPOVIG (
					(SELECT FORPAG FROM HJPF01_REN WHERE RAMO = I.RAMO AND POLIZA = I.POLIZA)
				),
				TIPOPDCION = PM.TB_REF_TIPOPDCION (
					(SELECT TIPPRO FROM HJPF01_REN WHERE RAMO = I.RAMO AND POLIZA = I.POLIZA)
				),
				TIPOFACT = DECODE (PM_AL.TB_REF_TIPOVIG (
					(SELECT FORPAG FROM HJPF01_REN WHERE RAMO = I.RAMO AND POLIZA = I.POLIZA)),'C','C','P'
				),
				INDCOA = DECODE (
					(SELECT CODCOA FROM HJPF01_REN WHERE RAMO = I.RAMO AND POLIZA = I.POLIZA),0,'N','S'
				),
				CODFORMFCION = DECODE (PM.TB_REF_TIPO_SUSCRIPCION (RAMO),'C','C','P'),
				CODOFISUSC = PM.CONVIERTE_ZONCOB_CODOFI (
					(SELECT ZONCOB FROM HJPF01_REN WHERE RAMO = I.RAMO AND POLIZA = I.POLIZA)
				),
				CODINTER = PM.BUSCA_PRODUCTOR (
					(SELECT CODPRD FROM HJPF01_REN WHERE RAMO = I.RAMO AND POLIZA = I.POLIZA)
				),
				CODMONEDA = (
					SELECT DECODE (TRIM (MAX (TIPMON)),'DO','DL','BS')
					FROM HJPF02_REN
					WHERE RAMO = I.RAMO AND POLIZA = I.RAMO
				),
				CODOFIEMI = (
					SELECT PM.BUSCA_DEPARTAMENTO (ZONCOB)
					FROM HJPF01_REN
					WHERE RAMO = I.RAMO AND POLIZA = I.POLIZA
				),
				CODFORMPAGO = (
					SELECT SUBSTR (ACFUNC,1,1) FROM CTRALTAB
					WHERE ACTIAR = 272
					AND TO_NUMBER (ACARGU) = (
						SELECT FORPAG FROM HJPF01_REN
						WHERE RAMO = I.RAMO AND POLIZA = I.POLIZA
					)
				),
				INDASEGTITULAR = DECODE (CODBE,0,'S',99,'S','N'),CODGRP = (
					SELECT PM.TB_REF_GRUPO_EMPRESARIAL (CDTCBR)
					FROM HJPF01_REN
					WHERE RAMO = I.RAMO AND POLIZA = I.POLIZA
				),
				PORCCOM = 0
			WHERE MIGRA = 'S'
			AND RAMO = I.RAMO
			AND POLIZA = I.POLIZA;
			COMMIT;
		END LOOP;
		--
		FOR I IN (
			SELECT DISTINCT RAMO,POLIZA,NUMREC FROM EQ_SINIESTRO_REN
			WHERE MIGRA = 'S'
		)
		LOOP
			UPDATE EQ_SINIESTRO_REN
			SET STSSIT = (
				SELECT NVL (TRIM (STSSIT),'0') FROM HJPF02_REN
				WHERE RAMO = I.RAMO
				AND POLIZA = I.POLIZA
				AND NUMREC = I.NUMREC
			),
			SUMAASEG = (
				SELECT DECODE (TOTSAS,0,1,TOTSAS) FROM HJPF02_REN
				WHERE RAMO = I.RAMO
				AND POLIZA = I.POLIZA
				AND NUMREC = I.NUMREC
			),
			MONTOPRIMA = (
				SELECT DECODE (TOTPRI,0,1,TOTPRI)
				FROM HJPF02_REN
				WHERE RAMO = I.RAMO
				AND POLIZA = I.POLIZA
				AND NUMREC = I.NUMREC
			),
			TASACAMBIO = (
				SELECT DECODE (TIPCAM,0,1,TIPCAM) FROM HJPF02_REN
				WHERE RAMO = I.RAMO
				AND POLIZA = I.POLIZA
				AND NUMREC = I.NUMREC
			)
			WHERE MIGRA = 'S'
			AND RAMO = I.RAMO
			AND POLIZA = I.POLIZA
			AND NUMREC = I.NUMREC;
		END LOOP;
		--			
		FOR I IN (
			SELECT DISTINCT RAMO,POLIZA,NUMREC,CODCOB,CODBE FROM EQ_SINIESTRO_REN
			WHERE MIGRA = 'S'
		)
		LOOP
			BEGIN
				SELECT DECODE (NVL (PRIMAR,1),0,1,NVL (PRIMAR,1)) INTO V_PRIMAMONEDA
				FROM HJPF05_REN
				WHERE RAMO = I.RAMO
				AND POLIZA = I.POLIZA
				AND NUMREC = I.NUMREC
				AND CODCOB = I.CODCOB;
				--
				SELECT DECODE (NVL (SUMASE,1),0,1,NVL (SUMASE,1)) INTO V_SUMAASEGMONEDA
				FROM HJPF05_REN
				WHERE RAMO = I.RAMO
				AND POLIZA = I.POLIZA
				AND NUMREC = I.NUMREC
				AND CODCOB = I.CODCOB;
				--
				UPDATE EQ_SINIESTRO_REN
				SET PRIMAMONEDA = V_PRIMAMONEDA,
					SUMAASEGMONEDA = V_SUMAASEGMONEDA
				WHERE MIGRA = 'S'
				AND RAMO = I.RAMO
				AND POLIZA = I.POLIZA
				AND NUMREC = I.NUMREC
				AND CODCOB = I.CODCOB;
				COMMIT;
			EXCEPTION WHEN OTHERS THEN
				BEGIN
					SELECT DECODE (NVL (PRIMAR,1),0,1,NVL (PRIMAR,1)) INTO V_PRIMAMONEDA
					FROM HJPF05_REN
					WHERE RAMO = I.RAMO
					AND POLIZA = I.POLIZA
					AND NUMREC = I.NUMREC
					AND CODCOB = I.CODCOB
					AND BIECOB = I.CODBE;
					--
					SELECT DECODE (NVL (SUMASE,1),0,1,NVL (SUMASE,1)) INTO V_SUMAASEGMONEDA
					FROM HJPF05_REN
					WHERE RAMO = I.RAMO
					AND POLIZA = I.POLIZA
					AND NUMREC = I.NUMREC
					AND CODCOB = I.CODCOB
					AND BIECOB = I.CODBE;
					--
					UPDATE EQ_SINIESTRO_REN
					SET PRIMAMONEDA = V_PRIMAMONEDA,
						SUMAASEGMONEDA = V_SUMAASEGMONEDA
					WHERE MIGRA = 'S'
					AND RAMO = I.RAMO
					AND POLIZA = I.POLIZA
					AND NUMREC = I.NUMREC
					AND CODCOB = I.CODCOB
					AND CODBE = I.CODBE;
					COMMIT;
				EXCEPTION WHEN OTHERS THEN
					V_PRIMAMONEDA := 1;
					V_SUMAASEGMONEDA := 1;
					--
					UPDATE EQ_SINIESTRO_REN
					SET PRIMAMONEDA = V_PRIMAMONEDA,
						SUMAASEGMONEDA = V_SUMAASEGMONEDA
					WHERE MIGRA = 'S'
					AND RAMO = I.RAMO
					AND POLIZA = I.POLIZA
					AND NUMREC = I.NUMREC
					AND CODCOB = I.CODCOB
					AND CODBE = I.CODBE;
					COMMIT;
				END;
			END;
		END LOOP;
		--
		FOR I IN (
			SELECT DISTINCT RAMO,POLIZA,NUMREC,STSSIT,PRIMAMONEDA FROM EQ_SINIESTRO_REN
			WHERE MIGRA = 'S'
		)
		LOOP
			BEGIN
				SELECT 
					(CASE
						WHEN CODOPE IN ('05','25','01') THEN 'EMI'
						WHEN CODOPE IN ('04','90') THEN 'REN'
						WHEN CODOPE IN ('97','33') THEN 'DEV'
						ELSE 'MOD'
					END)
				INTO V_TIPOMOV
				FROM HJPF02_REN
				WHERE RAMO = I.RAMO
				AND POLIZA = I.POLIZA
				AND NUMREC = I.NUMREC;
			EXCEPTION WHEN NO_DATA_FOUND THEN
				UPDATE EQ_SINIESTRO_REN
				SET MIGRA = 'N',RAZONMIGRA = 'No existe en HJPF02_REN'
				WHERE RAMO = I.RAMO
				AND POLIZA = I.POLIZA
				AND NUMREC = I.NUMREC;
				COMMIT;
			END;
			--
			IF NVL (TRIM (I.STSSIT),'0') = '0' AND I.PRIMAMONEDA >= 0 THEN
				V_STSREC := 'ACT';
			ELSIF NVL (TRIM (I.STSSIT),'0') = '0' AND I.PRIMAMONEDA < 0 THEN
				V_STSREC := 'ACT';
			ELSIF TRIM (I.STSSIT) = '1' AND I.PRIMAMONEDA >= 0 THEN
				V_STSREC := 'COB';
			ELSIF TRIM (I.STSSIT) = '1' AND I.PRIMAMONEDA < 0 THEN
				V_STSREC := 'PAG';
			ELSIF TRIM (I.STSSIT) = '2' AND I.PRIMAMONEDA >= 0 THEN
				V_STSREC := 'COB';
			ELSIF TRIM (I.STSSIT) = '2' AND I.PRIMAMONEDA < 0 THEN
				V_STSREC := 'PAG';
			ELSIF TRIM (I.STSSIT) = '3' AND I.PRIMAMONEDA < 0 THEN
				V_STSREC := 'ANU';
			ELSE
				V_STSREC := 'ACT';
			END IF;
			--
			UPDATE EQ_SINIESTRO_REN
			SET TIPOMOV = V_TIPOMOV,STSREC = V_STSREC
			WHERE MIGRA = 'S'
			AND RAMO = I.RAMO
			AND POLIZA = I.POLIZA
			AND NUMREC = I.NUMREC;
			COMMIT;
		END LOOP;
		--
		FOR I IN (
			SELECT DISTINCT CODPROD,CODPLAN,REVPLAN,CODRAMOCERT,CODCOBERT
			FROM EQ_SINIESTRO_REN
			WHERE MIGRA = 'S'
		)
		LOOP
			UPDATE EQ_SINIESTRO_REN
			SET CODRAMOREA = (
				SELECT CODRAMOREA FROM COBERT_PLAN_PROD@PROD
				WHERE CODPROD = I.CODPROD
				AND CODPLAN = I.CODPLAN
				AND REVPLAN = I.REVPLAN
				AND CODRAMOPLAN = I.CODRAMOCERT
				AND CODCOBERT = I.CODCOBERT
			),
			TIPOCOBERT = (
				SELECT TIPOCOBERT FROM COBERT_PLAN_PROD@PROD
				WHERE CODPROD = I.CODPROD
				AND CODPLAN = I.CODPLAN
				AND REVPLAN = I.REVPLAN
				AND CODRAMOPLAN = I.CODRAMOCERT
				AND CODCOBERT = I.CODCOBERT
			),
			INDACUMULASUMA = (
				SELECT INDACUMULASUMA FROM COBERT_PLAN_PROD@PROD
				WHERE CODPROD = I.CODPROD
				AND CODPLAN = I.CODPLAN
				AND REVPLAN = I.REVPLAN
				AND CODRAMOPLAN = I.CODRAMOCERT
				AND CODCOBERT = I.CODCOBERT
			),
			INDACUMULAPRIMA = (
				SELECT INDACUMULAPRIMA FROM COBERT_PLAN_PROD@PROD
				WHERE CODPROD = I.CODPROD
				AND CODPLAN = I.CODPLAN
				AND REVPLAN = I.REVPLAN
				AND CODRAMOPLAN = I.CODRAMOCERT
				AND CODCOBERT = I.CODCOBERT
			),
			MIGRAREA = 'S'
			WHERE MIGRA = 'S'
			AND CODPROD = I.CODPROD
			AND CODPLAN = I.CODPLAN
			AND REVPLAN = I.REVPLAN
			AND CODRAMOCERT = I.CODRAMOCERT
			AND CODCOBERT = I.CODCOBERT;
			COMMIT;
		END LOOP;
		--
		UPDATE EQ_SINIESTRO_REN A
		SET ZMCPA = (
			SELECT ZMCPA FROM HJPF02_REN I
			WHERE A.RAMO = I.RAMO
			AND A.POLIZA = I.POLIZA
			AND A.NUMREC = I.NUMREC
		);
		COMMIT;
		--
		UPDATE EQ_SINIESTRO_REN
		SET MIGRAREA = 'N'
		WHERE MIGRA = 'S'
		AND CODRAMOREA IS NULL
		AND TIPOCOBERT IS NULL;
		--
		UPDATE EQ_SINIESTRO_REN
		SET MIGRAREA = 'N'
		WHERE MIGRA = 'N';
		COMMIT;
		--
		UPDATE EQ_SINIESTRO_REN
		SET MIGRA = 'N',RAZONMIGRA = 'SUMAASEG demasiado largo'
		WHERE MIGRA = 'S'
		AND LENGTH (SUMAASEG) > 12;
		COMMIT;
		--
	END GEN_EQ_SINIESTRO_REN;
	--
	PROCEDURE GEN_CODCLI
	IS
		V_TIPOID 		ACSMIGRE.VIG_POLIZA.TIPOID@DESA%TYPE;
		V_NUMID			ACSMIGRE.VIG_POLIZA.NUMID@DESA%TYPE;
		V_DVID			ACSMIGRE.VIG_POLIZA.DVID@DESA%TYPE;
		V_CODCLIFACT	ACSMIGRE.VIG_CERTIFICADO.CODCLIFACT@DESA%TYPE;
		vDUMMY			NUMBER;
	BEGIN
		FOR I IN (
			SELECT DISTINCT RAMO,POLIZA,CODPROD FROM EQ_SINIESTRO_REN
			WHERE MIGRA = 'S'
		)
		LOOP
			vDUMMY := 0;
			V_TIPOID := NULL;
			V_NUMID := NULL;
			V_DVID := NULL;
			V_CODCLIFACT := NULL;
			--
			BEGIN
				SELECT TIPOID,NUMID,DVID INTO V_TIPOID,V_NUMID,V_DVID
				FROM EQ_HJPF01
				WHERE RAMO = I.RAMO
				AND POLIZA = I.POLIZA;
			EXCEPTION WHEN NO_DATA_FOUND THEN
				BEGIN
					SELECT TIPOID,NUMID,DVID INTO V_TIPOID,V_NUMID,V_DVID
					FROM ACSEL.CLIENTE@CERT
					WHERE CODCLI IN (
						SELECT CODCLI FROM ACSEL.POLIZA@CERT
						WHERE CODPOL = I.CODPROD AND NUMPOL = I.POLIZA
					);
				EXCEPTION WHEN NO_DATA_FOUND THEN
					BEGIN	
						SELECT TIPOID,NUMID,DVID INTO V_TIPOID,V_NUMID,V_DVID
						FROM HJPF01_SINIESTRO
						WHERE RAMO = I.RAMO AND POLIZA = I.POLIZA;
					EXCEPTION WHEN NO_DATA_FOUND THEN
						V_TIPOID := 'V';
						V_NUMID := 9999999;
						V_DVID := '0';
					END;
				END;
			END;
			--
			BEGIN
				SELECT 1 INTO vDUMMY FROM CTRALTAB
				WHERE ACTIAR = 101
				AND SUBSTR (ACFUNC,50,1) = 'C'
				AND ACARGU = I.RAMO;
				--
				BEGIN
					SELECT TIPOID,NUMID,DVID INTO V_TIPOID,V_NUMID,V_DVID
					FROM EQ_CLPF05_FAM
					WHERE RAMO = I.RAMO
					AND POLIZA = I.POLIZA
					AND NUMCER = I.NUMCERT
					AND COFAAM = I.CODBE;
					--
					SELECT TIPOID,NUMID,DVID INTO V_TIPOID,V_NUMID,V_DVID
					FROM EQ_CLPF07
					WHERE RAMO = I.RAMO
					AND POLIZA = I.POLIZA
					AND CERVEH = I.NUMCERT;
				EXCEPTION WHEN NO_DATA_FOUND THEN
					V_TIPOID := NULL;
					V_NUMID := NULL;
					V_DVID := NULL;
					V_CODCLIFACT := NULL;
				END;
			EXCEPTION WHEN NO_DATA_FOUND THEN
				BEGIN
					SELECT TIPOID,NUMID,DVID INTO V_TIPOID,V_NUMID,V_DVID
					FROM EQ_HJPF01
					WHERE RAMO = I.RAMO AND POLIZA = I.POLIZA;
				EXCEPTION WHEN NO_DATA_FOUND THEN
					BEGIN
						SELECT TIPOID,NUMID,DVID INTO V_TIPOID,V_NUMID,V_DVID
						FROM ACSEL.CLIENTE@CERT
						WHERE CODCLI IN (
							SELECT CODCLI FROM ACSEL.POLIZA@CERT
							WHERE CODPOL = I.CODPROD
							AND NUMPOL = I.POLIZA
						);
					EXCEPTION WHEN NO_DATA_FOUND THEN
						BEGIN
							SELECT TIPOID,NUMID,DVID INTO V_TIPOID,V_NUMID,V_DVID
							FROM HJPF01_SINIESTRO
							WHERE RAMO = I.RAMO
							AND POLIZA = I.POLIZA;
						EXCEPTION WHEN NO_DATA_FOUND THEN
							V_TIPOID := 9;
							V_NUMID := 99999999999999;
							V_DVID := '9';
						END;
					END;
				END;
			END;
			--
			V_CODCLIFACT := PM.GENERA_CODCLI (V_TIPOID,V_NUMID,V_DVID);
			--
			UPDATE EQ_SINIESTRO_REN
			SET TIPOID = V_TIPOID,NUMID = V_NUMID,DVID = V_DVID,CODCLI = V_CODCLIFACT
			WHERE RAMO = I.RAMO
			AND POLIZA = I.POLIZA
			AND MIGRA = 'S';
			COMMIT;
		END LOOP;
		--
		FOR I IN (
			SELECT RAMO,POLIZA,NUMCERT FROM EQ_SINIESTRO_REN
			WHERE CODCLI IS NULL AND MIGRA = 'S'
			GROUP BY RAMO,POLIZA,NUMCERT
		)
		LOOP
			V_TIPOID := 'V';
			V_NUMID := 9999999;
			V_DVID := '0';
			--
			UPDATE EQ_SINIESTRO_REN
			SET TIPOID = V_TIPOID,
				NUMID = V_NUMID,
				DVID = V_DVID,
				CODCLI = PM.GENERA_CODCLI (V_TIPOID,V_NUMID,V_DVID)
			WHERE RAMO = I.RAMO
			AND POLIZA = I.POLIZA
			AND NUMCERT = I.NUMCERT
			AND CODCLI IS NULL
			AND MIGRA = 'S';
			COMMIT;
		END LOOP;
	END GEN_CODCLI;
	--
	PROCEDURE INS_TABLAS_EQ
	IS
		CURSOR CUR_VIG_POLIZA (
			pRAMO 	ACSMIGRE.VIG_POLIZA.RAMO_AS@DESA%TYPE,
			pPOLIZA	ACSMIGRE.VIG_POLIZA.POLIZA_AS@DESA%TYPE
		)
		IS
		SELECT * FROM ACSMIGRE.VIG_POLIZA@DESA
		WHERE RAMO_AS = pRamo
		AND POLIZA_AS = pPOLIZA;
		--
		RT_CUR_VIG_POLIZA 	CUR_VIG_POLIZA%ROWTYPE;
		--
		CURSOR CUR_VIG_RECIBO (
			pRAMO			ACSMIGRE.VIG_RECIBO.RAMO_AS@DESA%TYPE,
			pPOLIZA			ACSMIGRE.VIG_RECIBO.POLIZA_AS@DESA%TYPE,
			pNUMCERT 		ACSMIGRE.VIG_RECIBO.NUMCERT@DESA%TYPE,
			pCODRAMOCERT 	ACSMIGRE.VIG_RECIBO.CODRAMOCERT@DESA%TYPE,
			pNUMREC 		ACSMIGRE.VIG_RECIBO.NUMREC@DESA%TYPE
		)
		IS
		SELECT * FROM ACSMIGRE.VIG_RECIBO@DESA
		WHERE RAMO_AS = pRamo
		AND POLIZA_AS = pPOLIZA
		AND NUMCERT = pNUMCERT
		AND CODRAMOCERT = pCODRAMOCERT
		AND NUMREC = pNUMREC;
		--
		RT_CUR_VIG_RECIBO	CUR_VIG_RECIBO%ROWTYPE;
		--
		CURSOR CUR_VIG_CERTIFICADO (
			pRAMO 			ACSMIGRE.VIG_CERTIFICADO.RAMO_AS@DESA%TYPE,
			pPOLIZA 		ACSMIGRE.VIG_CERTIFICADO.POLIZA_AS@DESA%TYPE,
			pNUMCERT 		ACSMIGRE.VIG_CERTIFICADO.NUMCERT@DESA%TYPE,
			pCODRAMOCERT	ACSMIGRE.VIG_CERTIFICADO.CODRAMOCERT@DESA%TYPE
		)
		IS
		SELECT * FROM ACSMIGRE.VIG_CERTIFICADO@DESA
		WHERE RAMO_AS = pRamo
		AND POLIZA_AS = pPOLIZA
		AND NUMCERT = pNUMCERT
		AND CODRAMOCERT = pCODRAMOCERT;
		--
		RT_CUR_VIG_CERTIFICADO	CUR_VIG_CERTIFICADO%ROWTYPE;
		--
		CURSOR CUR_VIG_COBERT_CERT (
			pRAMO 			ACSMIGRE.VIG_COBERT_CERT.RAMO_AS@DESA%TYPE,
			pPOLIZA			ACSMIGRE.VIG_COBERT_CERT.POLIZA_AS@DESA%TYPE,
			pNUMCERT 		ACSMIGRE.VIG_COBERT_CERT.NUMCERT@DESA%TYPE,
			pCODRAMOCERT	ACSMIGRE.VIG_COBERT_CERT.CODRAMOCERT@DESA%TYPE,
			pCODCOBERT		ACSMIGRE.VIG_COBERT_CERT.CODCOBERT@DESA%TYPE
		)
		IS
		SELECT * FROM ACSMIGRE.VIG_COBERT_CERT@DESA
		WHERE RAMO_AS = pRamo
		AND POLIZA_AS = pPOLIZA
		AND NUMCERT = pNUMCERT
		AND CODRAMOCERT = pCODRAMOCERT
		AND CODCOBERT = pCODCOBERT;
		--
		RT_CUR_VIG_COBERT_CERT 	CUR_VIG_COBERT_CERT%ROWTYPE;
		--
		CURSOR CUR_VIG_COBERT_CERT_REC (
			pRAMO 			ACSMIGRE.VIG_COBERT_CERT_REC.RAMO_AS@DESA%TYPE,
			pPOLIZA			ACSMIGRE.VIG_COBERT_CERT_REC.POLIZA_AS@DESA%TYPE,
			pNUMCERT 		ACSMIGRE.VIG_COBERT_CERT_REC.NUMCERT@DESA%TYPE,
			pCODRAMOCERT	ACSMIGRE.VIG_COBERT_CERT_REC.CODRAMOCERT@DESA%TYPE,
			pCODCOBERT		ACSMIGRE.VIG_COBERT_CERT_REC.CODCOBERT@DESA%TYPE,
			pNUMREC			ACSMIGRE.VIG_COBERT_CERT_REC.NUMREC@DESA%TYPE
		)
		IS
		SELECT * FROM ACSMIGRE.VIG_COBERT_CERT_REC@DESA
		WHERE RAMO_AS = pRamo
		AND POLIZA_AS = pPOLIZA
		AND NUMCERT = pNUMCERT
		AND CODRAMOCERT = pCODRAMOCERT
		AND CODCOBERT = pCODCOBERT
		AND NUMREC = pNUMREC;
		--
		RT_CUR_VIG_COBERT_CERT_REC	CUR_VIG_COBERT_CERT_REC%ROWTYPE;
		--
		CURSOR CUR_VIG_ASEGURADO (
			pRAMO 			ACSMIGRE.VIG_ASEGURADO.RAMO_AS@DESA%TYPE,
			pPOLIZA 		ACSMIGRE.VIG_ASEGURADO.POLIZA_AS@DESA%TYPE,
			pNUMCERT 		ACSMIGRE.VIG_ASEGURADO.NUMCERT@DESA%TYPE,
			pCODRAMOCERT 	ACSMIGRE.VIG_ASEGURADO.CODRAMOCERT@DESA%TYPE,
			pTIPOID			ACSMIGRE.VIG_ASEGURADO.TIPOID@DESA%TYPE,
			pNUMID 			ACSMIGRE.VIG_ASEGURADO.NUMID@DESA%TYPE,
			pDVID 			ACSMIGRE.VIG_ASEGURADO.DVID@DESA%TYPE
		)
		IS
		SELECT * FROM ACSMIGRE.VIG_ASEGURADO@DESA
		WHERE RAMO_AS = pRAMO
		AND POLIZA_AS = pPOLIZA
		AND NUMCERT = pNUMCERT
		AND CODRAMOCERT = pCODRAMOCERT
		AND TIPOID = pTIPOID
		AND NUMID = pNUMID
		AND DVID = pDVID;
		--
		RT_CUR_VIG_ASEGURADO 	CUR_VIG_ASEGURADO%ROWTYPE;
		--
		CURSOR CUR_VIG_ASEGURADO_REC (
			pRAMO 			ACSMIGRE.VIG_ASEGURADO_REC.RAMO_AS@DESA%TYPE,
			pPOLIZA 		ACSMIGRE.VIG_ASEGURADO_REC.POLIZA_AS@DESA%TYPE,
			pNUMCERT 		ACSMIGRE.VIG_ASEGURADO_REC.NUMCERT@DESA%TYPE,
			pCODRAMOCERT	ACSMIGRE.VIG_ASEGURADO_REC.CODRAMOCERT@DESA%TYPE,
			pTIPOID			ACSMIGRE.VIG_ASEGURADO_REC.TIPOID@DESA%TYPE,
			pNUMID 			ACSMIGRE.VIG_ASEGURADO_REC.NUMID@DESA%TYPE,
			pDVID 			ACSMIGRE.VIG_ASEGURADO_REC.DVID@DESA%TYPE,
			pNUMREC 		ACSMIGRE.VIG_ASEGURADO_REC.NUMREC@DESA%TYPE
		)
		IS
		SELECT * FROM ACSMIGRE.VIG_ASEGURADO_REC@DESA
		WHERE RAMO_AS = pRAMO
		AND POLIZA_AS = pPOLIZA
		AND NUMCERT = pNUMCERT
		AND CODRAMOCERT = pCODRAMOCERT
		AND TIPOID = pTIPOID
		AND NUMID = pNUMID
		AND DVID = pDVID
		AND NUMREC = pNUMREC;
		--
		RT_CUR_VIG_ASEGURADO_REC	CUR_VIG_ASEGURADO_REC%ROWTYPE;
		--
		CURSOR CUR_VIG_COBERT_ASEG (
			pRAMO 			ACSMIGRE.VIG_COBERT_ASEG.RAMO_AS@DESA%TYPE,
			pPOLIZA 		ACSMIGRE.VIG_COBERT_ASEG.POLIZA_AS@DESA%TYPE,
			pNUMCERT 		ACSMIGRE.VIG_COBERT_ASEG.NUMCERT@DESA%TYPE,
			pCODRAMOCERT 	ACSMIGRE.VIG_COBERT_ASEG.CODRAMOCERT@DESA%TYPE,
			pTIPOID 		ACSMIGRE.VIG_COBERT_ASEG.TIPOID@DESA%TYPE,
			pNUMID 			ACSMIGRE.VIG_COBERT_ASEG.NUMID@DESA%TYPE,
			pDVID 			ACSMIGRE.VIG_COBERT_ASEG.DVID@DESA%TYPE,
			pCODCOBERT 		ACSMIGRE.VIG_COBERT_ASEG.CODCOBERT@DESA%TYPE
		)
		IS
		SELECT * FROM ACSMIGRE.VIG_COBERT_ASEG@DESA
		WHERE RAMO_AS = pRAMO
		AND POLIZA_AS = pPOLIZA
		AND NUMCERT = pNUMCERT
		AND CODRAMOCERT = pCODRAMOCERT
		AND TIPOID = pTIPOID
		AND NUMID = pNUMID
		AND DVID = pDVID
		AND CODCOBERT = pCODCOBERT;
		--
		RT_CUR_VIG_COBERT_ASEG 		CUR_VIG_COBERT_ASEG%ROWTYPE;
		--
		CURSOR CUR_VIG_COBERT_ASEG_REC (
			pRAMO			ACSMIGRE.VIG_COBERT_ASEG_REC.RAMO_AS@DESA%TYPE,
			pPOLIZA			ACSMIGRE.VIG_COBERT_ASEG_REC.POLIZA_AS@DESA%TYPE,
			pNUMCERT 		ACSMIGRE.VIG_COBERT_ASEG_REC.NUMCERT@DESA%TYPE,
			pCODRAMOCERT 	ACSMIGRE.VIG_COBERT_ASEG_REC.CODRAMOCERT@DESA%TYPE,
			pTIPOID			ACSMIGRE.VIG_COBERT_ASEG_REC.TIPOID@DESA%TYPE,
			pNUMID 			ACSMIGRE.VIG_COBERT_ASEG_REC.NUMID@DESA%TYPE
			pDVID			ACSMIGRE.VIG_COBERT_ASEG_REC.DVID@DESA%TYPE,
			pCODCOBERT		ACSMIGRE.VIG_COBERT_ASEG_REC.CODCOBERT@DESA%TYPE,
			pNUMREC			ACSMIGRE.VIG_COBERT_ASEG_REC.NUMREC@DESA%TYPE
		)
		IS
		SELECT * FROM ACSMIGRE.VIG_COBERT_ASEG_REC@DESA
		WHERE RAMO_AS = pRAMO
		AND POLIZA_AS = pPOLIZA
		AND NUMCERT = pNUMCERT
		AND CODRAMOCERT = pCODRAMOCERT
		AND TIPOID = pTIPOID
		AND NUMID = pNUMID
		AND DVID = pDVID
		AND CODCOBERT = pCODCOBERT
		AND NUMREC = pNUMREC;
		--
		RT_CUR_VIG_COBERT_ASEG_REC	CUR_VIG_COBERT_ASEG_REC%ROWTYPE;
		--
		CURSOR CUR_VIG_BIEN_CERT (
			pRAMO 			ACSMIGRE.VIG_BIEN_CERT.RAMO_AS@DESA%TYPE,
			pPOLIZA			ACSMIGRE.VIG_BIEN_CERT.POLIZA_AS@DESA%TYPE,
			pNUMCERT 		ACSMIGRE.VIG_BIEN_CERT.NUMCERT@DESA%TYPE,
			pCODRAMOCERT	ACSMIGRE.VIG_BIEN_CERT.CODRAMOCERT@DESA%TYPE,
			pCODBIEN		ACSMIGRE.VIG_BIEN_CERT.CODBIEN@DESA%TYPE
		)
		IS
		SELECT * FROM ACSMIGRE.VIG_BIEN_CERT@DESA
		WHERE RAMO_AS = pRAMO
		AND POLIZA_AS = pPOLIZA
		AND NUMCERT = pNUMCERT
		AND CODRAMOCERT = pCODRAMOCERT
		AND CODBIEN = pCODBIEN;
		--
		RT_CUR_VIG_BIEN_CERT	CUR_VIG_BIEN_CERT%ROWTYPE;
		--
		CURSOR CUR_VIG_COBERT_BIEN (
			pRAMO 			ACSMIGRE.VIG_COBERT_BIEN.RAMO_AS@DESA%TYPE,
			pPOLIZA 		ACSMIGRE.VIG_COBERT_BIEN.POLIZA_AS@DESA%TYPE,
			pNUMCERT 		ACSMIGRE.VIG_COBERT_BIEN.NUMCERT@DESA%TYPE,
			pCODRAMOCERT 	ACSMIGRE.VIG_COBERT_BIEN.CODRAMOCERT@DESA%TYPE,
			pCODBIEN 		ACSMIGRE.VIG_COBERT_BIEN.CODBIEN@DESA%TYPE,
			pCODCOBERT 		ACSMIGRE.VIG_COBERT_BIEN.CODCOBERT@DESA%TYPE
		)
		IS
		SELECT * FROM ACSMIGRE.VIG_COBERT_BIEN@DESA
		WHERE RAMO_AS = pRAMO
		AND POLIZA_AS = pPOLIZA
		AND NUMCERT = pNUMCERT
		AND CODRAMOCERT = pCODRAMOCERT
		AND CODBIEN = pCODBIEN
		AND CODCOBERT = pCODCOBERT;
		--
		RT_CUR_VIG_COBERT_BIEN 	CUR_VIG_COBERT_BIEN%ROWTYPE;
		--
		CURSOR CUR_VIG_COBERT_BIEN_REC (
			pRAMO 			ACSMIGRE.VIG_COBERT_BIEN_REC.RAMO_AS@DESA%TYPE,
			pPOLIZA 		ACSMIGRE.VIG_COBERT_BIEN_REC.POLIZA_AS@DESA%TYPE,
			pNUMCERT 		ACSMIGRE.VIG_COBERT_BIEN_REC.NUMCERT@DESA%TYPE,
			pCODRAMOCERT 	ACSMIGRE.VIG_COBERT_BIEN_REC.CODRAMOCERT@DESA%TYPE,
			pCODBIEN 		ACSMIGRE.VIG_COBERT_BIEN_REC.CODBIEN@DESA%TYPE,
			pCODCOBERT 		ACSMIGRE.VIG_COBERT_BIEN_REC.CODCOBERT@DESA%TYPE,
			pNUMREC 		ACSMIGRE.VIG_COBERT_BIEN_REC.NUMREC@DESA%TYPE
		)
		IS
		SELECT * FROM ACSMIGRE.VIG_COBERT_BIEN_REC@DESA
		WHERE RAMO_AS = pRAMO
		AND POLIZA_AS = pPOLIZA
		AND NUMCERT = pNUMCERT
		AND CODRAMOCERT = pCODRAMOCERT
		AND CODBIEN = pCODBIEN
		AND CODCOBERT = pCODCOBERT
		AND NUMREC = pNUMREC;
		--
		RT_CUR_VIG_COBERT_BIEN_REC 	CUR_VIG_COBERT_BIEN_REC%ROWTYPE;
		--
		CURSOR CUR_POLIZA
		IS
		SELECT
			CODPROD CODPOL,POLIZA NUMPOL,NUMREN NUMREN,RAMO RAMO_AS,POLIZA POLIZA_AS,CODPROD CODPROD,STSPOL STSPOL,
			TIPOID TIPOID,NUMID NUMID,DVID DVID,FECFINVIG FECREN,FECINIVIG FECINIVIG,FECFINVIG FECFINVIG,TIPOVIG TIPOVIG,
			TIPOPDCION TIPOPDCION,TIPOFACT TIPOFACT,INDCOA INDCOA,CODFORMFCION CODFORMFCION,CODOFIEMI CODOFIEMI,
			CODOFISUSC CODOFISUSC,CODMONEDA CODMONEDA,TIPOSUSC TIPOSUSC,CODFORMPAGO CODFORMPAGO,NULL FECULTFACT,
			NULL INDRENOVLOTE,NULL CODCONDCOBRO,NULL RESPCOB,CODGRP CODGRP,NULL FECINGPOL,FECEMI FECEMI,CODINTER CODINTER
		FROM EQ_SINIESTRO_REN
		WHERE MIGRA = 'S';
		--
		CURSOR CUR_RECIBO
		IS
		SELECT 
			RAMO RAMO_AS,POLIZA POLIZA_AS,NUMCERT NUMCERT,CODRAMOCERT CODRAMOCERT,NUMREC NUMREC,TIPOID TIPOID,NUMID NUMID,
			DVID DVID,CODMONEDA CODMONEDA,FECEMI FECEMI,FECINIVALID FECINIVALID,FECFINVALID FECFINVALID,CODOFIEMI CODOFIEMI,
			TIPOMOV TIPOMOV,MONTOPRIMA MONTOPRIMA,TASACAMBIO TASACAMBIO,PORCCOM PORCCOM,ZMCPA MTOCOMISION,STSREC STSREC,
			NULL STSRECFIN,PRIMAMONEDA MONTOPRIMAMON,ZMCPA MTOCOMISIONMON,NULL CODOFICOB,NULL FECCOBRO
		FROM EQ_SINIESTRO_REN
		WHERE MIGRA = 'S';
		--
		CURSOR CUR_CERTIFICADO
		IS
		SELECT
			RAMO RAMO_AS,POLIZA POLIZA_AS,NUMCERT NUMCERT,STSCERT STSCERT,DESCCERT DESCCERT,FECING FECING,TIPOID,NUMID,
			DVID,TIPOID TIPOIDFACT,NUMID NUMIDFACT,DVID DVIDFACT,CODCLI CODCLIFACT,CLASERIESGO CLASERIESGO,NULL CODEXTERNO,
			NULL FECEMP,NULL FECANTCERT,CODRAMOCERT,FECINIVALID,FECFINVALID,NULL CODCUMULO,CODPLAN,REVPLAN
		FROM EQ_SINIESTRO_REN
		WHERE MIGRA = 'S';
		--
		CURSOR CUR_COBERT_CERT
		IS
		SELECT
			RAMO RAMO_AS,POLIZA POLIZA_AS,NUMCERT NUMCERT,CODRAMOCERT CODRAMOCERT,CODPLAN CODPLAN,REVPLAN REVPLAN,CODCOBERT CODCOBERT,
			STSCOBERT STSCOBERT,SUMAASEGMONEDA SUMAASEGMONEDA,TASACAMBIO TASA,PRIMAMONEDA PRIMAMONEDA,CODMONEDA CODMONEDA,SUMAASEG SUMAASEG,
			PRIMAMONEDA PRIMA,FECINIVALID FECINIVALID,FECFINVALID FECFINVALID,NULL INDSUMADED,NULL PORCDED,NULL MTODEDMIN,NULL BASEDED,
			NULL PORCDESC,NULL ORDEN,NULL PORCREEMB,NULL PORCMINASEG
		FROM EQ_SINIESTRO_REN
		WHERE MIGRA = 'S';
		--
		CURSOR CUR_COBERT_CERT_REC
		IS
		SELECT
			RAMO RAMO_AS,POLIZA POLIZA_AS,NUMCERT NUMCERT,CODPLAN CODPLAN,REVPLAN REVPLAN,CODCOBERT CODCOBERT,TO_NUMBER (NUMREC) NUMREC,
			SUMAASEG SUMAASEG,TASACAMBIO TASA,PRIMAMONEDA PRIMA,FECINIVALID FECINIVALID,FECFINVALID FECFINVALID,PRIMAMONEDA PRIMAANUAL,
			CODRAMOCERT CODRAMOCERT,PRIMAMONEDA PRIMAMON
		FROM EQ_SINIESTRO_REN
		WHERE MIGRA = 'S';
		--
		CURSOR CUR_ASEGURADO
		IS
		SELECT
			RAMO RAMO_AS,POLIZA POLIZA_AS,NUMCERT NUMCERT,CODRAMOCERT CODRAMOCERT,TIPOID TIPOID,NUMID NUMID,DVID DVID,
			INDASEGTITULAR INDASEGTITULAR,NULL MTOTOTRECAMONEDA,NULL MTOTOTDCTOMONEDA,CODMONEDA CODMONEDA,PRIMAMONEDA PRIMA,
			FECING FECING,NULL FECEXC,CODPLAN CODPLAN,REVPLAN REVPLAN,CODPARENT CODPARENT,NULL FECANTASEG
		FROM EQ_SINIESTRO_REN
		WHERE MIGRA = 'S'
		AND RAMO IN (
			SELECT TO_NUMBER (ACARGU) FROM CTRALTAB
			WHERE ACTIAR = 4855 AND TRIM (ACARGU) <> '**'
		);
		--
		CURSOR CUR_ASEGURADO_REC
		IS
		SELECT
			RAMO RAMO_AS,POLIZA POLIZA_AS,TIPOID TIPOID,NUMID NUMID,DVID DVID,NUMCERT NUMCERT,CODRAMOCERT CODRAMOCERT,NUMREC NUMREC
		FROM EQ_SINIESTRO_REN
		WHERE MIGRA = 'S'
		AND RAMO IN (
			SELECT TO_NUMBER (ACARGU) FROM CTRALTAB
			WHERE ACTIAR = 4855 AND TRIM (ACARGU) <> '**'
		);
		--
		CURSOR CUR_COBERT_ASEG
		IS
		SELECT
			RAMO RAMO_AS,POLIZA POLIZA_AS,NUMCERT,CODRAMOCERT,TIPOID,NUMID,DVID,CODPLAN,REVPLAN,CODCOBERT,STSCOBERT,NUMREC,
			SUMAASEGMONEDA SUMAASEG,TASACAMBIO TASA,PRIMAMONEDA PRIMA,CODMONEDA,SUMAASEGMONEDA,PRIMAMONEDA,FECINIVALID,
			FECFINVALID,NULL INDINCREN,NULL ORDEN,NULL PORCREEMB
		FROM EQ_SINIESTRO_REN
		WHERE MIGRA = 'S'
		AND RAMO IN (
			SELECT TO_NUMBER (ACARGU) FROM CTRALTAB
			WHERE ACTIAR = 4855 AND TRIM (ACARGU) <> '**'
		);
		--
		CURSOR CUR_COBERT_ASEG_REC
		IS
		SELECT
			RAMO RAMO_AS,POLIZA POLIZA_AS,NUMCERT,CODRAMOCERT,TIPOID,NUMID,DVID,CODPLAN,REVPLAN,CODCOBERT,NUMREC,
			SUMAASEGMONEDA SUMAASEG,TASACAMBIO TASA,PRIMAMONEDA PRIMA,FECINIVALID,FECFINVALID,PRIMAMONEDA PRIMAANUAL
		FROM EQ_SINIESTRO_REN
		WHERE MIGRA = 'S'
		AND RAMO IN (
			SELECT TO_NUMBER (ACARGU) FROM CTRALTAB
			WHERE ACTIAR = 4855 AND TRIM (ACARGU) <> '**'
		);
		--
		CURSOR CUR_BIEN_CERT
		IS
		SELECT
			RAMO RAMO_AS,POLIZA POLIZA_AS,NUMCERT NUMCERT,CODRAMOCERT CODRAMOCERT,CODMONEDA CODMONEDA,CLASEBIEN CLASEBIEN,CODBIEN CODBIEN,
			STSBIEN STSBIEN,NULL MTOVALBIEN,NULL MTOVALBIENMONEDA,NULL PORCRIESGO,NULL TIPO1ERIESGO,NULL INDMEGARIESGO,NULL DESCBIEN,
			NULL PORCPERIND,NULL INDAUMVAL,SUMAASEG SUMAASEG,NULL IDEBIENPLNS,NULL IDEBIENCASLO
		FROM EQ_SINIESTRO_REN
		WHERE MIGRA = 'S'
		AND RAMO IN (
			SELECT TO_NUMBER (ACARGU) FROM CTRALTAB
			WHERE ACTIAR = 4852 AND TRIM (ACARGU) <> '**'
		);
		--
		CURSOR CUR_COBERT_BIEN
		IS
		SELECT
			CODPLAN,REVPLAN,CODCOBERT,RAMO RAMO_AS,POLIZA POLIZA_AS,NUMCERT,CODBIEN,CODRAMOCERT,STSCOBERT,SUMAASEG,TASACAMBIO TASA,
			MONTOPRIMA PRIMA,CODMONEDA,SUMAASEGMONEDA,PRIMAMONEDA,FECINIVALID,FECFINVALID,NULL PORCDED,NULL MTODEDMIN,NULL BASEDED,
			NULL PORCDESC,NULL INDSUMADED,NULL ORDEN,NULL PORCREEMB,NULL PORCMINASEG,TASACAMBIO TASABRUTA
		FROM EQ_SINIESTRO_REN
		WHERE MIGRA = 'S'
		AND RAMO IN (
			SELECT TO_NUMBER (ACARGU) FROM CTRALTAB
			WHERE ACTIAR = 4852 AND TRIM (ACARGU) <> '**'
		);
		--
		CURSOR CUR_COBERT_BIEN_REC
		IS
		SELECT 
			RAMO RAMO_AS,POLIZA POLIZA_AS,NUMCERT,CODRAMOCERT,CODBIEN,CODPLAN,REVPLAN,CODCOBERT,NUMREC,SUMAASEG,
			TASACAMBIO TASA,MONTOPRIMA PRIMA,FECINIVALID,FECFINVALID,MONTOPRIMA PRIMAANUAL,PRIMAMONEDA PRIMAMON
		FROM EQ_SINIESTRO_REN
		WHERE MIGRA = 'S'
		AND RAMO IN (
			SELECT TO_NUMBER (ACARGU) FROM CTRALTAB
			WHERE ACTIAR = 4852 AND TRIM (ACARGU) <> '**'
		);
	BEGIN
		FOR I IN CUR_POLIZA
		LOOP
			OPEN CUR_VIG_POLIZA (I.RAMO_AS,I.POLIZA_AS);
			FETCH CUR_VIG_POLIZA INTO RT_CUR_VIG_POLIZA;
			IF CUR_VIG_POLIZA%NOTFOUND THEN
				INSERT INTO ACSMIGRE.VIG_POLIZA@DESA
				VALUES (
					NULL,I.CODPOL,I.NUMPOL,I.NUMREN,I.RAMO_AS,I.POLIZA_AS,I.CODPROD,I.STSPOL,I.TIPOID,I.NUMID,I.DVID,I.FECREN,
					I.FECINIVIG,I.FECFINVIG,I.TIPOVIG,I.TIPOPDCION,I.TIPOFACT,I.INDCOA,I.CODFORMFCION,I.CODOFIEMI,I.CODOFISUSC,
					I.CODMONEDA,I.TIPOSUSC,I.CODFORMPAGO,I.FECULTFACT,I.INDRENOVLOTE,I.CODCONDCOBRO,I.RESPCOB,I.CODGRP,I.FECINGPOL,
					I.FECEMI,I.CODINTER,NULL,NULL
				);
				COMMIT;
			END IF;
			CLOSE CUR_VIG_POLIZA;
		END LOOP;
		--
		FOR I IN CUR_RECIBO
		LOOP
			OPEN CUR_VIG_RECIBO (I.RAMO_AS,I.POLIZA_AS,I.NUMCERT,I.CODRAMOCERT,I.NUMREC);
			FETCH CUR_VIG_RECIBO INTO RT_CUR_VIG_RECIBO;

			IF CUR_VIG_RECIBO%NOTFOUND THEN
				INSERT INTO ACSMIGRE.VIG_RECIBO@DESA
				VALUES (
					I.RAMO_AS,I.POLIZA_AS,I.NUMCERT,I.CODRAMOCERT,I.NUMREC,I.TIPOID,I.NUMID,I.DVID,I.CODMONEDA,I.FECEMI,
					I.FECINIVALID,I.FECFINVALID,I.CODOFIEMI,I.TIPOMOV,I.MONTOPRIMA,I.TASACAMBIO,I.PORCCOM,I.MTOCOMISION,
					I.STSREC,I.STSRECFIN,I.MONTOPRIMAMON,I.MTOCOMISIONMON,I.CODOFICOB,I.FECCOBRO
				);
				COMMIT;
			END IF;
			CLOSE CUR_VIG_RECIBO;
		END LOOP;
		--
		FOR I IN CUR_CERTIFICADO
		LOOP
			OPEN CUR_VIG_CERTIFICADO (I.RAMO_AS,I.POLIZA_AS,I.NUMCERT,I.CODRAMOCERT);
			FETCH CUR_VIG_CERTIFICADO INTO RT_CUR_VIG_CERTIFICADO;

			IF CUR_VIG_CERTIFICADO%NOTFOUND THEN
				INSERT INTO ACSMIGRE.VIG_CERTIFICADO@DESA
				VALUES (
					I.RAMO_AS,I.POLIZA_AS,I.NUMCERT,I.STSCERT,I.DESCCERT,I.FECING,I.TIPOID,I.NUMID,I.DVID,I.TIPOIDFACT,
					I.NUMIDFACT,I.DVIDFACT,I.CODCLIFACT,I.CLASERIESGO,I.CODEXTERNO,I.FECEMP,I.FECANTCERT,I.CODRAMOCERT,
					I.FECINIVALID,I.FECFINVALID,I.CODCUMULO,I.CODPLAN,I.REVPLAN,NULL,NULL
				);
				COMMIT;
			END IF;
			CLOSE CUR_VIG_CERTIFICADO;
		END LOOP;
		--
		FOR I IN CUR_COBERT_CERT
		LOOP
			OPEN CUR_VIG_COBERT_CERT (I.RAMO_AS,I.POLIZA_AS,I.NUMCERT,I.CODRAMOCERT,I.CODCOBERT);
			FETCH CUR_VIG_COBERT_CERT INTO RT_CUR_VIG_COBERT_CERT;

			IF CUR_VIG_COBERT_CERT%NOTFOUND THEN
				INSERT INTO ACSMIGRE.VIG_COBERT_CERT@DESA
				VALUES (
					I.RAMO_AS,I.POLIZA_AS,I.NUMCERT,I.CODRAMOCERT,I.CODPLAN,I.REVPLAN,I.CODCOBERT,I.STSCOBERT,I.SUMAASEGMONEDA,
					I.TASA,I.PRIMAMONEDA,I.CODMONEDA,I.SUMAASEG,I.PRIMA,I.FECINIVALID,I.FECFINVALID,I.INDSUMADED,I.PORCDED,
					I.MTODEDMIN,I.BASEDED,I.PORCDESC,I.ORDEN,I.PORCREEMB,I.PORCMINASEG
				);
				COMMIT;
			END IF;
			CLOSE CUR_VIG_COBERT_CERT;
		END LOOP;
		--
		FOR I IN CUR_COBERT_CERT_REC
		LOOP
			OPEN CUR_VIG_COBERT_CERT_REC (I.RAMO_AS,I.POLIZA_AS,I.NUMCERT,I.CODRAMOCERT,I.CODCOBERT,I.NUMREC);
			FETCH CUR_VIG_COBERT_CERT_REC INTO RT_CUR_VIG_COBERT_CERT_REC;
			
			IF CUR_VIG_COBERT_CERT_REC%NOTFOUND THEN
				INSERT INTO ACSMIGRE.VIG_COBERT_CERT_REC@DESA
				VALUES (
					I.RAMO_AS,I.POLIZA_AS,I.NUMCERT,I.CODPLAN,I.REVPLAN,I.CODCOBERT,I.NUMREC,I.SUMAASEG,I.TASA,
					I.PRIMA,I.FECINIVALID,I.FECFINVALID,I.PRIMAANUAL,I.CODRAMOCERT,I.PRIMAMON
				);
				COMMIT;
			END IF;
			CLOSE CUR_VIG_COBERT_CERT_REC;
		END LOOP;
		--
		FOR I IN CUR_ASEGURADO
		LOOP
			OPEN CUR_VIG_ASEGURADO (I.RAMO_AS,I.POLIZA_AS,I.NUMCERT,I.CODRAMOCERT,I.TIPOID,I.NUMID,I.DVID);
			FETCH CUR_VIG_ASEGURADO INTO RT_CUR_VIG_ASEGURADO;

			IF CUR_VIG_ASEGURADO%NOTFOUND THEN
				INSERT INTO ACSMIGRE.VIG_ASEGURADO@DESA
				VALUES (
					I.RAMO_AS,I.POLIZA_AS,I.NUMCERT,I.CODRAMOCERT,I.TIPOID,I.NUMID,I.DVID,I.INDASEGTITULAR,I.MTOTOTRECAMONEDA,
					I.MTOTOTDCTOMONEDA,I.CODMONEDA,I.PRIMA,I.FECING,I.FECEXC,I.CODPLAN,I.REVPLAN,I.CODPARENT,I.FECANTASEG,NULL,NULL
				);
				COMMIT;
			END IF;
			CLOSE CUR_VIG_ASEGURADO;
		END LOOP;
		--
		FOR I IN CUR_ASEGURADO_REC
		LOOP
			OPEN CUR_VIG_ASEGURADO_REC (I.RAMO_AS,I.POLIZA_AS,I.NUMCERT,I.CODRAMOCERT,I.TIPOID,I.NUMID,I.DVID,I.NUMREC);
			FETCH CUR_VIG_ASEGURADO_REC INTO RT_CUR_VIG_ASEGURADO_REC;

			IF CUR_VIG_ASEGURADO_REC%NOTFOUND THEN
				INSERT INTO ACSMIGRE.VIG_ASEGURADO_REC@DESA (RAMO_AS,POLIZA_AS,TIPOID,NUMID,DVID,NUMCERT,CODRAMOCERT,NUMREC)
				VALUES (I.RAMO_AS,I.POLIZA_AS,I.TIPOID,I.NUMID,I.DVID,I.NUMCERT,I.CODRAMOCERT,I.NUMREC);
				COMMIT;
			END IF;
			CLOSE CUR_VIG_ASEGURADO_REC;
		END LOOP;
		--
		FOR I IN CUR_COBERT_ASEG
		LOOP
			OPEN CUR_VIG_COBERT_ASEG (I.RAMO_AS,I.POLIZA_AS,I.NUMCERT,I.CODRAMOCERT,I.TIPOID,I.NUMID,I.DVID,I.CODCOBERT);
			FETCH CUR_VIG_COBERT_ASEG INTO RT_CUR_VIG_COBERT_ASEG;

			IF CUR_VIG_COBERT_ASEG%NOTFOUND THEN
				INSERT INTO ACSMIGRE.VIG_COBERT_ASEG@DESA
				VALUES (
					I.RAMO_AS,I.POLIZA_AS,I.NUMCERT,I.CODRAMOCERT,I.TIPOID,I.NUMID,I.DVID,I.CODPLAN,I.REVPLAN,I.CODCOBERT,
					I.STSCOBERT,I.NUMREC,I.SUMAASEG,I.TASA,I.PRIMA,I.CODMONEDA,I.SUMAASEGMONEDA,I.PRIMAMONEDA,I.FECINIVALID,
					I.FECFINVALID,I.INDINCREN,I.ORDEN,I.PORCREEMB,NULL,NULL,NULL
				);
				COMMIT;
			END IF;
			CLOSE CUR_VIG_COBERT_ASEG;
		END LOOP;
		--
		FOR I IN CUR_COBERT_ASEG_REC
		LOOP
			OPEN CUR_VIG_COBERT_ASEG_REC (I.RAMO_AS,I.POLIZA_AS,I.NUMCERT,I.CODRAMOCERT,I.TIPOID,I.NUMID,I.DVID,I.CODCOBERT,I.NUMREC);
			FETCH CUR_VIG_COBERT_ASEG_REC INTO RT_CUR_VIG_COBERT_ASEG_REC;

			IF CUR_VIG_COBERT_ASEG_REC%NOTFOUND THEN
				INSERT INTO ACSMIGRE.VIG_COBERT_ASEG_REC@DESA
				VALUES (
					I.RAMO_AS,I.POLIZA_AS,I.NUMCERT,I.CODRAMOCERT,I.TIPOID,I.NUMID,I.DVID,I.CODPLAN,I.REVPLAN,
					I.CODCOBERT,I.NUMREC,I.SUMAASEG,I.TASA,I.PRIMA,I.FECINIVALID,I.FECFINVALID,I.PRIMAANUAL
				);
				COMMIT;
			END IF;
			CLOSE CUR_VIG_COBERT_ASEG_REC;
		END LOOP;
		--
		FOR I IN CUR_BIEN_CERT
		LOOP
			OPEN CUR_VIG_BIEN_CERT (I.RAMO_AS,I.POLIZA_AS,I.NUMCERT,I.CODRAMOCERT,I.CODBIEN);
			FETCH CUR_VIG_BIEN_CERT INTO RT_CUR_VIG_BIEN_CERT;

			IF CUR_VIG_BIEN_CERT%NOTFOUND THEN
				INSERT INTO ACSMIGRE.VIG_BIEN_CERT@DESA
				VALUES (
					I.RAMO_AS,I.POLIZA_AS,I.NUMCERT,I.CODRAMOCERT,I.CODMONEDA,I.CLASEBIEN,I.CODBIEN,I.STSBIEN,I.MTOVALBIEN,I.MTOVALBIENMONEDA,
					I.PORCRIESGO,I.TIPO1ERIESGO,I.INDMEGARIESGO,I.DESCBIEN,I.PORCPERIND,I.INDAUMVAL,I.SUMAASEG,I.IDEBIENPLNS,I.IDEBIENCASLO
				);
				COMMIT;
			END IF;
			CLOSE CUR_VIG_BIEN_CERT;
		END LOOP;
		--
		FOR I IN CUR_COBERT_BIEN
		LOOP
			OPEN CUR_VIG_COBERT_BIEN (I.RAMO_AS,I.POLIZA_AS,I.NUMCERT,I.CODRAMOCERT,I.CODBIEN,I.CODCOBERT);
			FETCH CUR_VIG_COBERT_BIEN INTO RT_CUR_VIG_COBERT_BIEN;

			IF CUR_VIG_COBERT_BIEN%NOTFOUND THEN
				INSERT INTO ACSMIGRE.VIG_COBERT_BIEN@DESA
				VALUES (
					I.CODPLAN,I.REVPLAN,I.CODCOBERT,I.RAMO_AS,I.POLIZA_AS,I.NUMCERT,I.CODBIEN,I.CODRAMOCERT,I.STSCOBERT,I.SUMAASEG,
					I.TASA,I.PRIMA,I.CODMONEDA,I.SUMAASEGMONEDA,I.PRIMAMONEDA,I.FECINIVALID,I.FECFINVALID,I.PORCDED,I.MTODEDMIN,
					I.BASEDED,I.PORCDESC,I.INDSUMADED,I.ORDEN,I.PORCREEMB,I.PORCMINASEG,I.TASABRUTA
				);
				COMMIT;
			END IF;
			CLOSE CUR_VIG_COBERT_BIEN;
		END LOOP;
		--
		FOR I IN CUR_COBERT_BIEN_REC
		LOOP
			OPEN CUR_VIG_COBERT_BIEN_REC (I.RAMO_AS,I.POLIZA_AS,I.NUMCERT,I.CODRAMOCERT,I.CODBIEN,I.CODCOBERT,I.NUMREC);
			FETCH CUR_VIG_COBERT_BIEN_REC INTO RT_CUR_VIG_COBERT_BIEN_REC;

			IF CUR_VIG_COBERT_BIEN_REC%NOTFOUND THEN
				INSERT INTO ACSMIGRE.VIG_COBERT_BIEN_REC@DESA
				VALUES (
					I.RAMO_AS,I.POLIZA_AS,I.NUMCERT,I.CODRAMOCERT,I.CODBIEN,I.CODPLAN,I.REVPLAN,I.CODCOBERT,I.NUMREC,I.SUMAASEG,
					I.TASA,I.PRIMA,I.FECINIVALID,I.FECFINVALID,I.PRIMAANUAL,I.PRIMAMON
				);
				COMMIT;
			END IF;
			CLOSE CUR_VIG_COBERT_BIEN_REC;
		END LOOP;
	END INS_TABLAS_EQ;
	--
	PROCEDURE GEN_EQ_REPF14_REN
	IS
		CURSOR CUR_REPF14
		IS
		SELECT DISTINCT * FROM (
			SELECT
				A.RAMO,A.POLIZA,A.STSREC,A.NUMREC,A.TIPCON,A.SUMA,A.PRIMA,A.STSMAN,A.STSSIT,A.TIPMON,A.TIPCAM,
				A.SUMAE,A.PRIMAE,DECODE(GEN_REA.PRIMA,0,0,((A.PRIMA*100)/GEN_REA.PRIMA)) PORCENTAJE
			FROM REPF14_REN A,(
				SELECT RAMO,POLIZA,NUMREC,SUM (PRIMA) PRIMA
				FROM REPF14_REN
				GROUP BY RAMO,POLIZA,NUMREC
			) GEN_REA
			WHERE A.RAMO = GEN_REA.RAMO
			AND A.POLIZA = GEN_REA.POLIZA
			AND A.NUMREC = GEN_REA.NUMREC
		);
	BEGIN
		DELETE FROM EQ_REPF14_REN;
		COMMIT;
		--
		FOR I IN CUR_REPF14
		LOOP
			INSERT INTO EQ_REPF14_REN
			VALUES (
				I.RAMO,I.POLIZA,I.STSREC,I.NUMREC,I.TIPCON,I.SUMA,I.PRIMA,I.STSMAN,
				I.STSSIT,I.TIPMON,I.TIPCAM,I.SUMAE,I.PRIMAE,I.PORCENTAJE
			);
			COMMIT;
		END LOOP;
	END GEN_EQ_REPF14_REN;
	--
	PROCEDURE INSERTAR_DAT_EQ_REASEGURO_R
	IS
		CURSOR REASEGURO
		IS
		SELECT EQ.*,REN.TIPCON,REN.SUMA SUMAREA,REN.PRIMA PRIMAREA,REN.PORCENTAJE
		FROM EQ_SINIESTRO_REN EQ,EQ_REPF14_REN REN
		WHERE EQ.RAMO = REN.RAMO
		AND EQ.POLIZA = REN.POLIZA
		AND EQ.NUMREC = REN.NUMREC
		AND EQ.MIGRA = 'S'
		AND EQ.MIGRAREA = 'S';
		--
		nMes 			NUMBER := 0;
		nSerieREA 		ACSEL.CTTO_REA.Serie@CERT%TYPE;
		cTipoCtto 		ACSEL.CTTO_REA.TipoCtto@CERT%TYPE;
		cIndSerie 		VARCHAR2 (1);
		nIdeCttoRea 	ACSEL.DIST_REA.idecttorea@CERT%TYPE;
		nOrdenCtto 		ACSEL.DIST_REA.ordenctto@CERT%TYPE;
	BEGIN
		EXECUTE IMMEDIATE 'TRUNCATE TABLE EQ_REASEGURO_REN';
		--
		FOR I IN REASEGURO
		LOOP
			nMes := NULL;
			nSerieREA := NULL;
			cTipoCtto := NULL;
			--
			BEGIN
				IF I.CodRamoRea = '0103' OR I.CodRamoRea = '0030' THEN
					nMes := EXTRACT (MONTH FROM I.FECINIVALID);
					--
					IF nMes >= 7 THEN
						nSerieREA := EXTRACT (YEAR FROM I.FECINIVALID);
					ELSE
						nSerieREA := EXTRACT (YEAR FROM I.FECINIVALID) - 1;
					END IF;
					--
					IF nSerieREA = 2010 OR nSerieREA = 2011 THEN
						IF I.TipCon = 2 THEN
							I.TipCon := 1;
						END IF;
					END IF;
				END IF;
				--
				IF I.CodRamoRea = '0101' OR I.CodRamoRea = '0104' THEN
					I.TipCon := 1;
				END IF;
				--
				IF I.CodRamoRea = '0102' OR I.CodRamoRea = '0106' THEN
					I.TipCon := 1;
				END IF;
				--
				IF I.CodRamoRea = '0041' OR I.CodRamoRea = '0043' OR I.CodRamoRea = '0082' THEN
					I.TipCon := 1;
				END IF;
				--
				IF I.CodProd IN ('FIAN','TRCO','TRMO') THEN
					cIndserie := 'E';
					nMes := EXTRACT (MONTH FROM I.FecEmi);

					IF nMes >= 7 THEN
						nSerieREA := EXTRACT (YEAR FROM I.FecEmi);
					ELSE
						nSerieREA := EXTRACT (YEAR FROM I.FecEmi) - 1;
					END IF;
				ELSE
					cIndSerie := 'R';
					nMes := EXTRACT (MONTH FROM I.FecIniValid);

					IF nMes >= 7 THEN
						nSerieREA := EXTRACT (YEAR FROM I.FecIniValid);
					ELSE
						nSerieREA := EXTRACT (YEAR FROM I.FecIniValid) - 1;
					END IF;
				END IF;
				--
				BEGIN
					SELECT TipoCtto INTO cTipoCtto
					FROM EQ_TIPOCTTO
					WHERE TipCon = I.TipCon;
				EXCEPTION WHEN NO_DATA_FOUND THEN
					cTipoCtto := NULL;
				END;
				--
				IF cTipoCtto = 'FOB' AND I.CodProd IN ('AUTI','AUTC') THEN
					cTipoCtto := 'FO1';
				END IF;
				--
				nIdeCttoRea := NULL;
				nOrdenCtto := NULL;
				--
				IF I.tipcon = 19 THEN
					nIdeCttoRea := 99999999999999;
					nOrdenCtto := 999;
				ELSE
					BEGIN
						SELECT IdeCttoRea,NVL (OrdenCtto,999) INTO nIdeCttoRea,nOrdenCtto
						FROM ACSEL.CTTO_REA@CERT
						WHERE CodRamorea = I.CodRamoRea
						AND Serie = NSerieREA
						AND CodMoneda = I.CodMoneda
						AND TipoCtto = cTipoCtto
						AND StsCttorea = 'ACT';
					EXCEPTION WHEN OTHERS THEN
						nIdeCttoRea := NULL;
						nOrdenCtto := NULL;
					END;
				END IF;
				--
				INSERT INTO EQ_REASEGURO_REN
				VALUES (
					I.RAMO,I.POLIZA,I.SERIE,I.RECLAM,I.CODBE,I.CODCOB,I.NUMCERT,I.NUMREC,I.FECEMI,I.FECINIVALID,I.FECFINVALID,
					I.FECINIVIG,I.FECFINVIG,I.FECING,I.MIGRA,I.RAZONMIGRA,I.NUMREN,I.TIPOSUSC,I.CODRAMOCERT,I.CODCOBERT,I.STSCOBERT,
					I.BIECOB,I.CLASEBIEN,I.STSBIEN,I.CODMONEDA,I.CODOFIEMI,I.CODPROD,I.CODPLAN,I.REVPLAN,I.CODPARENT,I.STSCERT,
					I.DESCCERT,I.STSPOL,I.TIPOVIG,I.TIPOPDCION,I.TIPOFACT,I.INDCOA,I.CODFORMFCION,I.CODOFISUSC,I.CODINTER,I.TIPOMOV,
					I.PRIMAMONEDA,I.MONTOPRIMA,I.SUMAASEGMONEDA,I.SUMAASEG,I.TASACAMBIO,I.PORCCOM,I.MTOCOMISION,I.STSREC,I.STSSIT,
					I.CLASERIESGO,I.CODFORMPAGO,I.INDASEGTITULAR,I.TIPOID,I.NUMID,I.DVID,I.CODCLI,I.CODGRP,I.CODRAMOREA,I.MIGRAREA,
					I.TIPOCOBERT,I.INDACUMULASUMA,I.INDACUMULAPRIMA,I.TIPCON,I.SUMAREA,I.PRIMAREA,I.PORCENTAJE,NSerieREA,cTipoCtto,
					nIdeCttoRea,nOrdenCtto
				);
				COMMIT;
			END;
		END LOOP;
		--
		UPDATE EQ_REASEGURO_REN
		SET MIGRA = 'N',RAZONMIGRA = 'Porcentaje en cero de Reaseguro'
		WHERE MIGRA = 'S' AND PORCENTAJE = 0;
		COMMIT;
		--
		UPDATE EQ_REASEGURO_REN
		SET MIGRA = 'N',RAZONMIGRA = 'IdeCttoRea - nOrdenCtto NULO'
		WHERE MIGRA = 'S' AND IdeCttoRea IS NULL;
		COMMIT;
		--
	END INSERTAR_DAT_EQ_REASEGURO_R;
	--
	PROCEDURE MIG_REASEGURO_EG
	IS
		CURSOR CUR_GEN_REA
		IS
		SELECT
			RAMO RAMO_AS,POLIZA POLIZA_AS,NUMCERT,CODRAMOREA,SUM (SUMAASEG) SUMAASEG,SUM (PRIMAMOV) PRIMAMOV,
			FECINIVIG,FECFINVIG,FECEMI FECMOV,'ACT' STSGENREA,CLASERIESGO,1 ORDEN,NULL CODCUMULO,NULL FECANUL,
			'0004' TIPOCODCUMULO,NUMREC,CODRAMOCERT CODRAMO,1 NUMGENREA
		FROM (
			SELECT
				RAMO,POLIZA,NUMCERT,CODRAMOREA,SUM (DECODE (INDACUMULASUMA,'N',0,SUMAREA)) SUMAASEG,
				SUM (DECODE (INDACUMULAPRIMA,'N',0,PRIMAREA)) PRIMAMOV,FECINIVIG,FECFINVIG,FECEMI,
				CLASERIESGO,NUMREC,CODRAMOCERT
			FROM EQ_REASEGURO_REN
			WHERE MIGRA = 'S' AND MIGRAREA = 'S'
			GROUP BY RAMO,POLIZA,NUMCERT,CODRAMOREA,FECINIVIG,FECFINVIG,FECEMI,CLASERIESGO,NUMREC,CODRAMOCERT
		)
		GROUP BY RAMO,POLIZA,NUMCERT,CODRAMOREA,FECINIVIG,FECFINVIG,FECEMI,CLASERIESGO,NUMREC,CODRAMOCERT;
		--
		CURSOR CUR_DIST_REA
		IS
		SELECT
			RAMO RAMO_AS,POLIZA POLIZA_AS,IDECTTOREA IDECTTOREA,1 NUMMODDISTREA,SUM (SUMADISTREA) SUMADISTREA,
			SUM (PRIMADISTREA) PRIMADISTREA,ORDENCTTO ORDENCTTO,NULL IDECIERRE,NULL IDEPOL,SERIEREA SERIE,
			SUM (PORCENTAJE) PORCDISTTIPOCTTO,CLASERIESGO,1 NUMGENREA,CODRAMOREA
		FROM (
			SELECT DISTINCT 
				RAMO,POLIZA,SERIE,RECLAM,NUMREC,CODBE,PORCENTAJE,IDECTTOREA,SERIEREA,ORDENCTTO,
				DECODE (
					PORCENTAJE,100,
					SUM (DECODE (INDACUMULASUMA,'N',0,SUMAREA)),
					ROUND (SUM (DECODE (INDACUMULASUMA,'N',0,SUMAREA))*ROUND((PORCENTAJE/100),2),2)
				) SUMADISTREA,
				DECODE (
					PORCENTAJE,100,
					SUM (DECODE (INDACUMULAPRIMA,'N',0,PRIMAREA)),
					ROUND (SUM (DECODE (INDACUMULAPRIMA,'N',0,PRIMAREA))*ROUND((PORCENTAJE/100),2),2)
				) PRIMADISTREA,
				DECODE (PORCENTAJE,100,PORCENTAJE,ROUND (PORCENTAJE,2)) PORCDISTTIPOCTTO,CLASERIESGO,CODRAMOREA
			FROM EQ_REASEGURO_REN
			WHERE MIGRA = 'S'
			AND MIGRAREA = 'S'
			GROUP BY RAMO,POLIZA,SERIE,RECLAM,NUMREC,CODBE,PORCENTAJE,IDECTTOREA,SERIEREA,ORDENCTTO,CLASERIESGO,CODRAMOREA
		)
		GROUP BY RAMO,POLIZA,IDECTTOREA,SERIE,RECLAM,NUMREC,CODBE,SERIEREA,ORDENCTTO,PORCENTAJE,CLASERIESGO,CODRAMOREA;
		--
		CURSOR CUR_DIST_FACUL
		IS
		SELECT DISTINCT
			A.RAMO RAMO_AS,A.POLIZA POLIZA_AS,NVL (
				(SELECT CodAcepRiesgo FROM EQ_ACEP_RIESGO WHERE codrf = B.Codrf),LPAD (B.Codrf,6,0)
			) CODACEPRIESGO,
			0 NUMMODDISTREA,B.SUMARE SUMACEDIDA,B.PRIMRE PRIMACEDIDA,B.IMPRTA IMPRET,0 IMPREM,'ACT' STSDISTFACULT,
			PM.CONVIERTE_DIAMESANO_FECHA (DIASTS,MESSTS,ANOSTS) FECSTS,B.NUMCES NUMCESION,SERIEREA ANOCESION,NULL PRIMANETACESION,
			NULL PORCCOM,NULL PORCDEP,NULL INTDEP,NULL DIAPAGO,NULL NROCARTAENTREGA,NULL TEXTO,CODINTER,NULL PORIMPMUN,NULL PORAPORSUPER,
			PM.CONVIERTE_DIAMESANO_FECHA (DIAING,MESING,ANOING) FECINIVIG,PM.CONVIERTE_DIAMESANO_FECHA (DIAVEN,MESVEN,ANOVEN) FECFINVIG,
			NULL INDANULACION,NULL IDECTTOREA,NULL STSNUMCESION,NULL FECSTSNUMCESION,NULL NUMOBLIG,NULL NUMACRE,1 NUMGENREA,CODRAMOREA
		FROM EQ_REASEGURO_REN A,REPF15_REN B
		WHERE A.RAMO = B.RAMO
		AND A.POLIZA = B.POLIZA
		AND A.NUMREC = B.NUMREC
		AND A.MIGRA = 'S'
		AND A.MIGRAREA = 'S'
		AND A.TIPCON = 19;
		--
		CURSOR CUR_DIAS_GAR_PAGO
		IS
		SELECT
			A.RAMO RAMO_AS,A.POLIZA POLIZA_AS,1 NUMGENREA,NVL (
				(SELECT CodAcepRiesgo FROM EQ_ACEP_RIESGO WHERE codrf = B.Codrf),LPAD (B.Codrf,6,0)
			) CODACEPRIESGO,0 NUMMODDISTREA,B.NUMCES NUMCESION,0 NROGARANTIA,NULL NNUMDIA,
			NULL FECGARPAGO,NULL PORCCANT,NULL FECPAGO,NULL NUMOBLIG,NULL INDPAGO,SERIEREA ANOCESION
		FROM EQ_REASEGURO_REN A,REPF15_REN B
		WHERE A.RAMO = B.RAMO
		AND A.POLIZA = B.POLIZA
		AND A.NUMREC = B.NUMREC
		AND A.MIGRA = 'S'
		AND A.MIGRAREA = 'S'
		AND A.TIPCON = 19;
		--
		CURSOR CUR_VIG_GEN_REA (
			pRAMO          ACSMIGRE.VIG_GEN_REA.RAMO_AS@DESA%TYPE,
			pPOLIZA        ACSMIGRE.VIG_GEN_REA.POLIZA_AS@DESA%TYPE,
			pNUMCERT       ACSMIGRE.VIG_GEN_REA.NUMCERT@DESA%TYPE,
			pCODRAMO       ACSMIGRE.VIG_GEN_REA.CODRAMO@DESA%TYPE,
			pNUMREC        ACSMIGRE.VIG_GEN_REA.NUMREC@DESA%TYPE,
			pCODRAMOREA    ACSMIGRE.VIG_GEN_REA.CODRAMOREA@DESA%TYPE,
			pNUMGENREA     ACSMIGRE.VIG_GEN_REA.NUMGENREA@DESA%TYPE
		)
		IS
		SELECT * FROM ACSMIGRE.VIG_GEN_REA@DESA
		WHERE RAMO_AS = pRAMO
		AND POLIZA_AS = pPOLIZA
		AND NUMCERT = pNUMCERT
		AND CODRAMO = pCODRAMO
		AND NUMREC = pNUMREC
		AND CODRAMOREA = pCODRAMOREA
		AND NUMGENREA = pNUMGENREA;
		--
		RT_CUR_VIG_GEN_REA	CUR_VIG_GEN_REA%ROWTYPE;
		--
		CURSOR CUR_VIG_DIST_REA (
			pRAMO_AS          ACSMIGRE.VIG_DIST_REA.RAMO_AS@DESA%TYPE,
			pPOLIZA           ACSMIGRE.VIG_DIST_REA.POLIZA_AS@DESA%TYPE,
			pNUMGENREA        ACSMIGRE.VIG_DIST_REA.NUMGENREA@DESA%TYPE,
			pIDECTTOREA       ACSMIGRE.VIG_DIST_REA.IDECTTOREA@DESA%TYPE,
			pNUMMODDISTREA    ACSMIGRE.VIG_DIST_REA.NUMMODDISTREA@DESA%TYPE
		)
		IS
		SELECT * FROM ACSMIGRE.VIG_DIST_REA@DESA
		WHERE RAMO_AS = pRAMO_AS
		AND POLIZA_AS = pPOLIZA
		AND NUMGENREA = pNUMGENREA
		AND IDECTTOREA = pIDECTTOREA
		AND NUMMODDISTREA = pNUMMODDISTREA;
		--
		RT_CUR_VIG_DIST_REA	CUR_VIG_DIST_REA%ROWTYPE;
		--
		CURSOR CUR_VIG_DIST_FACULT (
			pNUMGENREA        ACSMIGRE.VIG_DIST_FACULT.NUMGENREA@DESA%TYPE,
			pCODACEPRIESGO    ACSMIGRE.VIG_DIST_FACULT.CODACEPRIESGO@DESA%TYPE,
			pNUMMODDISTREA    ACSMIGRE.VIG_DIST_FACULT.NUMMODDISTREA@DESA%TYPE,
			pNUMCESION        ACSMIGRE.VIG_DIST_FACULT.NUMCESION@DESA%TYPE,
			pANOCESION        ACSMIGRE.VIG_DIST_FACULT.ANOCESION@DESA%TYPE
		)
		IS
		SELECT * FROM ACSMIGRE.VIG_DIST_FACULT@DESA
		WHERE NUMGENREA = pNUMGENREA
		AND CODACEPRIESGO = pCODACEPRIESGO
		AND NUMMODDISTREA = pNUMMODDISTREA
		AND NUMCESION = pNUMCESION
		AND ANOCESION = pANOCESION;
		--
		RT_CUR_VIG_DIST_FACULT	CUR_VIG_DIST_FACULT%ROWTYPE;
		--
		CURSOR CUR_VIG_DIAS_GAR_PAGO (
			pRAMO             ACSMIGRE.VIG_DIAS_GAR_PAGO.RAMO_AS@DESA%TYPE,
			pPOLIZA           ACSMIGRE.VIG_DIAS_GAR_PAGO.POLIZA_AS@DESA%TYPE,
			pNUMGENREA        ACSMIGRE.VIG_DIAS_GAR_PAGO.NUMGENREA@DESA%TYPE,
			pCODACEPRIESGO    ACSMIGRE.VIG_DIAS_GAR_PAGO.CODACEPRIESGO@DESA%TYPE,
			pNUMMODDISTREA    ACSMIGRE.VIG_DIAS_GAR_PAGO.NUMMODDISTREA@DESA%TYPE,
			pNUMCESION        ACSMIGRE.VIG_DIAS_GAR_PAGO.NUMCESION@DESA%TYPE,
			pNROGARANTIA      ACSMIGRE.VIG_DIAS_GAR_PAGO.NROGARANTIA@DESA%TYPE
		)
		IS
		SELECT * FROM ACSMIGRE.VIG_DIAS_GAR_PAGO@DESA
		WHERE RAMO_AS = pRAMO
		AND POLIZA_AS = pPOLIZA
		AND NUMGENREA = pNUMGENREA
		AND CODACEPRIESGO = pCODACEPRIESGO
		AND NUMMODDISTREA = pNUMMODDISTREA
		AND NUMCESION = pNUMCESION
		AND NROGARANTIA = pNROGARANTIA;
		--
		RT_CUR_VIG_DIAS_GAR_PAGO	CUR_VIG_DIAS_GAR_PAGO%ROWTYPE;
		--
		nIdeCttoRea		ACSEL.DIST_REA.idecttorea@CERT%TYPE;
		nOrdenCtto		ACSEL.DIST_REA.ordenctto@CERT%TYPE;
	BEGIN
		FOR I IN CUR_GEN_REA
		LOOP
			OPEN CUR_VIG_GEN_REA (I.RAMO_AS,I.POLIZA_AS,I.NUMCERT,I.CODRAMO,I.NUMREC,I.CODRAMOREA,I.NUMGENREA);
			FETCH CUR_VIG_GEN_REA INTO RT_CUR_VIG_GEN_REA;

			IF CUR_VIG_GEN_REA%NOTFOUND THEN
				INSERT INTO ACSMIGRE.VIG_GEN_REA@DESA
				VALUES (
					I.RAMO_AS,I.POLIZA_AS,I.NUMCERT,I.CODRAMOREA,I.SUMAASEG,I.PRIMAMOV,I.FECINIVIG,I.FECFINVIG,I.FECMOV,
					I.STSGENREA,I.CLASERIESGO,I.ORDEN,I.CODCUMULO,I.FECANUL,I.TIPOCODCUMULO,I.NUMREC,I.CODRAMO,I.NUMGENREA
				);
				COMMIT;
			END IF;
			CLOSE CUR_VIG_GEN_REA;
		END LOOP;
		--
		FOR I IN CUR_DIST_REA
		LOOP
			OPEN CUR_VIG_DIST_REA (I.RAMO_AS,I.POLIZA_AS,I.NUMGENREA,I.IDECTTOREA,I.NUMMODDISTREA);
			FETCH CUR_VIG_DIST_REA INTO RT_CUR_VIG_DIST_REA;

			IF CUR_VIG_DIST_REA%NOTFOUND THEN
				INSERT INTO ACSMIGRE.VIG_DIST_REA@DESA
				VALUES (
					I.RAMO_AS,I.POLIZA_AS,I.IDECTTOREA,I.NUMMODDISTREA,I.SUMADISTREA,I.PRIMADISTREA,I.ORDENCTTO,
					I.IDECIERRE,I.IDEPOL,I.SERIE,I.PORCDISTTIPOCTTO,I.CLASERIESGO,I.NUMGENREA,I.CODRAMOREA
				);
				COMMIT;
			END IF;
			CLOSE CUR_VIG_DIST_REA;
		END LOOP;
		--
		FOR I IN CUR_DIST_FACUL
		LOOP
			OPEN CUR_VIG_DIST_FACULT (I.NUMGENREA,I.CODACEPRIESGO,I.NUMMODDISTREA,I.NUMCESION,I.ANOCESION);
			FETCH CUR_VIG_DIST_FACULT INTO RT_CUR_VIG_DIST_FACULT;

			IF CUR_VIG_DIST_FACULT%NOTFOUND THEN
				INSERT INTO ACSMIGRE.VIG_DIST_FACULT@DESA
				VALUES (
					I.RAMO_AS,I.POLIZA_AS,I.CODACEPRIESGO,I.NUMMODDISTREA,I.SUMACEDIDA,I.PRIMACEDIDA,I.IMPRET,I.IMPREM,
					I.STSDISTFACULT,I.FECSTS,I.NUMCESION,I.ANOCESION,I.PRIMANETACESION,I.PORCCOM,I.PORCDEP,I.INTDEP,
					I.DIAPAGO,I.NROCARTAENTREGA,I.TEXTO,I.CODINTER,I.PORIMPMUN,I.PORAPORSUPER,I.FECINIVIG,I.FECFINVIG,
					I.INDANULACION,I.IDECTTOREA,I.STSNUMCESION,I.FECSTSNUMCESION,I.NUMOBLIG,I.NUMACRE,I.NUMGENREA,I.CODRAMOREA
				);
				COMMIT;
			END IF;
			CLOSE CUR_VIG_DIST_FACULT;
		END LOOP;
		--
		FOR I IN CUR_DIAS_GAR_PAGO
		LOOP
			OPEN CUR_VIG_DIAS_GAR_PAGO (I.RAMO_AS,I.POLIZA_AS,I.NUMGENREA,I.CODACEPRIESGO,I.NUMMODDISTREA,I.NUMCESION,I.NROGARANTIA);
			FETCH CUR_VIG_DIAS_GAR_PAGO INTO RT_CUR_VIG_DIAS_GAR_PAGO;

			IF CUR_VIG_DIAS_GAR_PAGO%NOTFOUND THEN
				INSERT INTO ACSMIGRE.VIG_DIAS_GAR_PAGO@DESA
				VALUES (
					I.RAMO_AS,I.POLIZA_AS,I.NUMGENREA,I.CODACEPRIESGO,I.NUMMODDISTREA,I.NUMCESION,I.NROGARANTIA,
					I.NNUMDIA,I.FECGARPAGO,I.PORCCANT,I.FECPAGO,I.NUMOBLIG,I.INDPAGO,I.ANOCESION
				);
				COMMIT;
			END IF;
			CLOSE CUR_VIG_DIAS_GAR_PAGO;
		END LOOP;
	END MIG_REASEGURO_EG;
	--
	PROCEDURE CERT_VEH_APEP_MIG
	IS
		CURSOR CUR_VIG_CERT_VEH (
			pRAMO 		ACSMIGRE.VIG_CERT_VEH.RAMO_AS@DESA%TYPE,
			pPOLIZA		ACSMIGRE.VIG_CERT_VEH.POLIZA_AS@DESA%TYPE,
			pNUMCERT 	ACSMIGRE.VIG_CERT_VEH.NUMCERT@DESA%TYPE
		)
		IS
		SELECT * FROM ACSMIGRE.VIG_CERT_VEH@DESA
		WHERE RAMO_AS = pRamo
		AND POLIZA_AS = pPOLIZA
		AND NUMCERT = pNUMCERT;
		--
		RT_CUR_VIG_CERT_VEH		CUR_VIG_CERT_VEH%ROWTYPE;
		--
		CURSOR IND_EG
		IS
		SELECT DISTINCT
			HJ03.RAMO,HJ03.POLIZA,HJ03.NUMREC,HJ03.CLARCV,HJ03.FECADQ,HJ03.DESTIN,HJ03.ENSAMB,HJ03.CODMOD,EQ.NUMCERT NUMCERT,
			DECODE (HJ03.REMOLQ,1,'NOUSA','SIUSA') AS CODREMOLQUE,HJ03.NUMPLA AS NUMPLACA,HJ03.AÑOVEH AS ANOVEH,HJ03.TONELA AS CANTTONELADA,
			HJ03.CANPAS AS NUMPUESTOS,'NOA' AS TIPOVEH,HJ03.COLOR AS COLOR,HJ03.SERCAR AS SERIALCARROCERIA,HJ03.SERMOT AS SERIALMOTOR,
			DECODE (HJ03.STSREC,'3','ANU','ACT') AS STSEXP,'968' AS CODINSPEC,'P' AS INDTIPOPLACA,0 AS CANTKMS,'N' AS INDNUEVO,
			NULL AS TIPOCARGA,'S' AS INDREQREINSP,'024' AS CODPLANEXCESO,LPAD (TO_CHAR (HJ03.ENSAMB),3,'0') || LPAD (TO_CHAR (HJ03.CODMOD),3,'0') ACARGU
		FROM (
			SELECT EQ.RAMO,EQ.POLIZA,EQ.NUMREC,EQ.NUMCERT,EQ.FECING AS FECSTS,EQ.CODOFIEMI,HJ.ENSAMB,HJ.CODMOD,MAX (SUMAASEG) SUMASE
			FROM EQ_SINIESTRO_REN EQ,HJPF03_REN HJ
			WHERE HJ.RAMO = EQ.RAMO
			AND HJ.POLIZA = EQ.POLIZA
			AND HJ.NUMREC = EQ.NUMREC
			AND EQ.MIGRA <> 'N'
			GROUP BY EQ.RAMO,EQ.POLIZA,EQ.NUMREC,EQ.NUMCERT,EQ.FECING,EQ.CODOFIEMI,HJ.ENSAMB,HJ.CODMOD
		) EQ,HJPF03_REN HJ03
		WHERE HJ03.CLARCV <> 0
		AND HJ03.RAMO = EQ.RAMO
		AND HJ03.POLIZA = EQ.POLIZA
		AND HJ03.NUMREC = EQ.NUMREC;
		--
		CURSOR COL_EG
		IS
		SELECT DISTINCT
			A.RAMO,A.POLIZA,A.NUMCERT NUMCERT,B.CLARCV,B.DESTIN,B.NUMPLA,B.AÑOVEH,B.TONELA,B.CANPAS,B.FECADQ,B.COLOR,TRIM (B.SERCAR) SERCAR,
			B.SERMOT,DECODE (B.REMOLQ,1,'NOUSA','SIUSA') AS CODREMOLQUE,'NOA' AS TIPOVEH,'968' AS CODINSPEC,'P' AS INDTIPOPLACA,0 AS CANTKMS,
			'N' AS INDNUEVO,NULL AS TIPOCARGA,'S' AS INDREQREINSP,'024' AS CODPLANEXCESO,TRIM (B.SERMOT) AS SERIALMOTOR,
			TRIM (B.SERCAR) AS SERIALCARROCERIA,B.CANPAS AS NUMPUESTOS,B.TONELA AS CANTTONELADA,B.AÑOVEH AS ANOVEH,B.NUMPLA AS NUMPLACA,
			LPAD (TO_CHAR (B.ENSAMB),3,'0') || LPAD (TO_CHAR (B.CODMOD),3,'0') AS ACARGU,NULL NROCIV,SUMASE
		FROM (
			SELECT EQ.RAMO,EQ.POLIZA,EQ.NUMREC,EQ.NUMCERT,EQ.FECING AS FECSTS,EQ.CODOFIEMI,CL.ENSAMB,CL.CODMOD,MAX (SUMAASEG) SUMASE
			FROM EQ_SINIESTRO_REN EQ,CLPF07_REN CL
			WHERE CL.RAMO = EQ.RAMO
			AND CL.POLIZA = EQ.POLIZA
			AND CL.CERVEH = EQ.NUMCERT
			AND EQ.MIGRA <> 'N'
			GROUP BY EQ.RAMO,EQ.POLIZA,EQ.NUMREC,EQ.NUMCERT,EQ.FECING,EQ.CODOFIEMI,CL.ENSAMB,CL.CODMOD
		) A,CLPF07_REN B
		WHERE A.RAMO = B.RAMO(+)
		AND A.POLIZA = B.POLIZA(+)
		AND A.NUMCERT = B.CERVEH(+)
		AND A.RAMO = 31;
		--
		V_CODDESTINADO 		VARCHAR2 (1);
		V_FECADQ 			DATE;
		V_TIPOVEH 			VARCHAR2 (3);
		V_TIPOVEHACSEL		VARCHAR2 (3);
		V_CLASEVEH 			VARCHAR2 (6);
		V_CLASEVEHACSEL 	VARCHAR2 (6);
		V_CODPLANEXCESOA	VARCHAR2 (3);
		V_INDFABRIC 		VARCHAR2 (1);
		V_CODPLANEXCESO 	VARCHAR2 (3);
		V_VER_NOMBRE 		VARCHAR2 (30);
		V_CODMODELO 		VARCHAR2 (5);
		V_CODMARCA 			VARCHAR2 (5);
		V_CODVERSION 		VARCHAR2 (5);
		V_VER_TRANSM 		ACSMIGRA.CERT_VEH_MIG.TIPOTRANS@DESA%TYPE;
		V_NOMBRE 			VARCHAR2 (30);
		V_EXISTE 			NUMBER;
		V_ACFUNC 			CTRALTAB.ACFUNC%TYPE;
		V_VER_MOTOR 		VVALORES.VER_MOTOR%TYPE;
		V_CODPENAL 			TB_REF_CODPENAL.CODPENAL%TYPE;
		V_CODVER 			VAPF02.CODVER%TYPE;
		v_planapov 			TB_REF_TIPOVEH.PLANAPOV%TYPE;
		V_NUMPLACA 			ACSMIGRA.CERT_VEH_MIG.NUMPLACA@DESA%TYPE;
		V_COLOR 			ACSMIGRA.CERT_VEH_MIG.COLOR@DESA%TYPE;
		V_SERIALCARRO 		ACSMIGRA.CERT_VEH_MIG.SERIALCARROCERIA@DESA%TYPE;
		V_SERIALMOTOR 		ACSMIGRA.CERT_VEH_MIG.SERIALMOTOR@DESA%TYPE;
		NSUMASE 			NUMBER;
	BEGIN	
		FOR I IN (SELECT ROWID FROM ACSMIGRE.VIG_CERT_VEH@DESA)
		LOOP
			DELETE FROM ACSMIGRE.VIG_CERT_VEH@DESA WHERE ROWID = I.ROWID;
			COMMIT;
		END LOOP;
		--
		FOR CO IN COL_EG
		LOOP
			BEGIN
				V_CODDESTINADO := PM.TB_REF_CODDESTINADO (CO.DESTIN);
				V_TIPOVEH := PM.BUSCA_TB_REF_TIPOVEH (CO.CLARCV);
				V_CLASEVEH := PM.BUSCA_TB_REF_CLASEVEH (CO.CLARCV);
				V_NUMPLACA := PM.ELIMINA_ESPACIOS (CO.NUMPLACA);
				V_COLOR := PM.ELIMINA_ESPACIOS (CO.COLOR);
				V_SERIALCARRO := PM.ELIMINA_ESPACIOS (CO.SERIALCARROCERIA);
				V_SERIALMOTOR := PM.ELIMINA_ESPACIOS (CO.SERIALMOTOR);
				NSUMASE := 0;
				--
				IF CO.FECADQ = 0 THEN
					V_FECADQ := NULL;
				ELSE
					V_FECADQ := PM.CONVIERTE_DIAMESANO_FECHA (
						SUBSTR (LPAD (TRIM (TO_CHAR (CO.FECADQ)),8,'0'),1,2),
						SUBSTR (LPAD (TRIM (TO_CHAR (CO.FECADQ)),8,'0'),3,2),
						SUBSTR (LPAD (TRIM (TO_CHAR (CO.FECADQ)),8,'0'),5,4)
					);
				END IF;
				--
				SELECT MAX (CODVER) INTO V_CODVER FROM VAPF02
				WHERE PROCES = 'S';
				--
				BEGIN
					SELECT
						TRIM (SX.VER_NOMBRE),
						TRIM (SUBSTR (LPAD (TRIM (TO_CHAR (SX.VER_CIVI)),8,'0'),4,3)),
						TRIM (SUBSTR (LPAD (TRIM (TO_CHAR (SX.VER_CIVI)),8,'0'),1,3)),
						TRIM (SUBSTR (LPAD (TRIM (TO_CHAR (SX.VER_CIVI)),8,'0'),7,2)),
						DECODE (TRIM (SX.VER_TRANSM),'A','A','S'),TRIM (SX.VER_MOTOR)
					INTO V_VER_NOMBRE,V_CODMODELO,V_CODMARCA,V_CODVERSION,V_VER_TRANSM,V_VER_MOTOR
					FROM VVALORES SX
					WHERE SX.VER_CIVI = CO.NROCIV
					AND SX.ANO = CO.ANOVEH
					AND SX.CODVER = V_CODVER;
					--
					V_NOMBRE := PM.ELIMINA_ESPACIOS (SUBSTR (TRIM (V_ACFUNC) || ' ' || V_VER_NOMBRE,1,30));
				EXCEPTION WHEN OTHERS THEN
					V_VER_TRANSM := 'S';
					V_NOMBRE := PM.ELIMINA_ESPACIOS (SUBSTR (TRIM (V_ACFUNC) || 'SIN VERSION',1,30));
					V_CODMODELO := SUBSTR (LPAD (TRIM (TO_CHAR ('99900101')),8,'0'), 4, 3);
					V_CODMARCA := SUBSTR (LPAD (TRIM (TO_CHAR ('99900101')),8,'0'), 1, 3);
					V_CODVERSION := SUBSTR (LPAD (TRIM (TO_CHAR ('99900101')),8,'0'), 7, 2);
					V_VER_MOTOR := NULL;
				END;
				--
				BEGIN
					SELECT WW.TIPOVEH,WW.CLASEVEH INTO V_TIPOVEHACSEL,V_CLASEVEHACSEL
					FROM EQ_AUTO WW
					WHERE WW.TIPOVEHAS = CO.CLARCV;
				END;
				--
				BEGIN
					SELECT APOV INTO V_PLANAPOV
					FROM EQ_APOV
					WHERE TIPOVEHAS = CO.CLARCV AND SUMASE = CO.SUMASE;
				EXCEPTION WHEN NO_DATA_FOUND THEN
					V_PLANAPOV := '000';
				END;
				--
				BEGIN
					OPEN CUR_VIG_CERT_VEH (CO.RAMO,CO.POLIZA,CO.NUMCERT);
					FETCH CUR_VIG_CERT_VEH INTO RT_CUR_VIG_CERT_VEH;

					IF CUR_VIG_CERT_VEH%NOTFOUND THEN
						INSERT INTO ACSMIGRE.VIG_CERT_VEH@DESA (
							RAMO_AS,POLIZA_AS,NUMCERT,CODMODELO,CODMARCA,CODVERSION,DESCMOTOR,CODDESTINADO,CODREMOLQUE,NUMPLACA,ANOVEH,
							CANTTONELADA,NUMPUESTOS,TIPOVEH,FECADQ,COLOR,SERIALCARROCERIA,SERIALMOTOR,CLASEVEH,CODPLANAPOV,FECREG,
							INDFABRIC,INDTIPOPLACA,CANTKMS,TIPOTRANS,INDNUEVO,TIPOCARGA,CODPLANEXCESO,INDREQREINSP,DESCTIPOVEH,CODPENAL,TIPODES
						)
						VALUES (
							CO.RAMO,CO.POLIZA,CO.NUMCERT,V_CODMODELO,V_CODMARCA,V_CODVERSION,V_VER_MOTOR,V_CODDESTINADO,CO.CODREMOLQUE,V_NUMPLACA,
							CO.ANOVEH,CO.CANTTONELADA,CO.NUMPUESTOS,V_TIPOVEHACSEL,V_FECADQ,V_COLOR,V_SERIALCARRO,V_SERIALMOTOR,V_CLASEVEHACSEL,
							V_PLANAPOV,NULL,'N',CO.INDTIPOPLACA,CO.CANTKMS,V_VER_TRANSM,CO.INDNUEVO,CO.TIPOCARGA,'000',CO.INDREQREINSP,V_NOMBRE,
							'000',CO.DESTIN
						);
						COMMIT;
					END IF;
					CLOSE CUR_VIG_CERT_VEH;
				END;
			END;
		END LOOP;
		--
		v_coddestinado := NULL;
		v_fecadq := NULL;
		v_tipoveh := NULL;
		v_claseveh := NULL;
		v_indfabric := NULL;
		v_codplanexceso := NULL;
		v_ver_nombre := NULL;
		v_codmodelo := NULL;
		v_codmarca := NULL;
		v_codversion := NULL;
		v_ver_transm := NULL;
		v_ver_motor := NULL;
		v_nombre := NULL;
		v_codpenal := NULL;
		v_planapov := NULL;
		v_codver := NULL;
		v_existe := NULL;
		v_numplaca := NULL;
		v_color := NULL;
		v_serialcarro := NULL;
		v_serialmotor := NULL;
		nSumase := NULL;
		--
		FOR CO IN IND_EG
		LOOP
			BEGIN
				v_coddestinado := pm.tb_ref_coddestinado (CO.destin);
				v_tipoveh := pm.busca_tb_ref_tipoveh (CO.clarcv);
				v_claseveh := pm.busca_tb_ref_claseveh (CO.clarcv);
				v_numplaca := pm.elimina_espacios (CO.numplaca);
				v_color := pm.elimina_espacios (CO.color);
				v_serialcarro := pm.elimina_espacios (CO.serialcarroceria);
				v_serialmotor := pm.elimina_espacios (CO.serialmotor);
				nSumase := 0;
				--
				IF CO.fecadq = 0 THEN
					v_fecadq := NULL;
				ELSE
					v_fecadq := pm.convierte_diamesano_fecha (
						SUBSTR (LPAD (TRIM (TO_CHAR (CO.fecadq)),8,'0'),1,2),
						SUBSTR (LPAD (TRIM (TO_CHAR (CO.fecadq)),8,'0'),3,2),
						SUBSTR (LPAD (TRIM (TO_CHAR (CO.fecadq)),8,'0'),5,4)
					);
				END IF;
				--
				BEGIN
					SELECT MAX (SUBSTR (TRIM (acfunc),1,48)) INTO v_acfunc
					FROM CTRALTAB
					WHERE TRIM (acargu) = CO.acargu;
				END;
				--
				SELECT MAX (codver) INTO v_codver FROM vapf02
				WHERE proces = 'S';
				--
				BEGIN
					SELECT DISTINCT
						TRIM (sx.ver_transm),TRIM (sx.ver_motor),TRIM (sx.ver_nombre),
						TRIM (SUBSTR (LPAD (TRIM (TO_CHAR (az.vercih)),8,'0'),4,3)) AS vcodmodelo,
						TRIM (SUBSTR (LPAD (TRIM (TO_CHAR (az.vercih)),8,'0'),1,3)) AS vcodmarca,
						TRIM (SUBSTR (LPAD (TRIM (TO_CHAR (az.vercih)),8,'0'),7,2)) AS vcodversion
					INTO v_ver_transm,v_ver_motor,v_ver_nombre,v_codmodelo,v_codmarca,v_codversion
					FROM HJPF09A az,VVALORES sx
					WHERE az.ramo IN (32,33,34,35)
					AND az.poliza = co.poliza
					AND az.numrec = co.numrec
					AND az.vercih = sx.ver_civi
					AND az.anof = sx.ano
					AND sx.codver = v_codver;
					--
					v_nombre := pm.elimina_espacios(SUBSTR (TRIM (v_acfunc) || ' ' || v_ver_nombre,1,30));
				EXCEPTION WHEN OTHERS THEN
					v_ver_transm := 'S';
					v_nombre := pm.elimina_espacios (SUBSTR (TRIM (v_acfunc) || ' SIN VERSION',1,30));
					v_codmodelo := SUBSTR (LPAD (TRIM (TO_CHAR ('99900101')),8,'0'), 4, 3);
					v_codmarca := SUBSTR (LPAD (TRIM (TO_CHAR ('99900101')),8,'0'), 1, 3);
					v_codversion := SUBSTR (LPAD (TRIM (TO_CHAR ('99900101')),8,'0'), 7, 2);
					v_ver_motor := NULL;
				END;
				--
				BEGIN
					SELECT APOV INTO V_PLANAPOV
					FROM EQ_APOV
					WHERE TIPOVEHAS = CO.CLARCV
					AND SUMASE = CO.SUMASE;
				EXCEPTION WHEN NO_DATA_FOUND THEN
					V_PLANAPOV := '000';
				END;
				--
				BEGIN
					OPEN CUR_VIG_CERT_VEH (CO.RAMO,CO.POLIZA,CO.NUMCERT);
					FETCH CUR_VIG_CERT_VEH INTO RT_CUR_VIG_CERT_VEH;

					IF CUR_VIG_CERT_VEH%NOTFOUND THEN
						INSERT INTO ACSMIGRE.VIG_CERT_VEH@DESA (
							RAMO_AS,POLIZA_AS,numcert,codmodelo,codmarca,codversion,descmotor,coddestinado,codremolque,numplaca,anoveh,
							canttonelada,numpuestos,tipoveh,fecadq,color,serialcarroceria,serialmotor,claseveh,codplanapov,fecreg,indfabric,
							indtipoplaca,cantkms,tipotrans,indnuevo,tipocarga,codplanexceso,indreqreinsp,desctipoveh,codpenal,tipodes
						)
						VALUES (
							CO.RAMO,CO.POLIZA,CO.numcert,v_codmodelo,v_codmarca,v_codversion,v_ver_motor,v_coddestinado,CO.codremolque,
							v_numplaca,CO.anoveh,CO.canttonelada,CO.numpuestos,v_tipoveh,v_fecadq,v_color,v_serialcarro,v_serialmotor,
							v_claseveh,v_planapov,NULL,'N',CO.indtipoplaca,CO.cantkms,v_ver_transm,CO.indnuevo,CO.tipocarga,CO.codplanexceso,
							CO.indreqreinsp,v_nombre,'000',CO.destin
						);
						COMMIT;
					END IF;
					CLOSE CUR_VIG_CERT_VEH;
				END;
			END;
		END LOOP;
	END CERT_VEH_APEP_MIG;
	--
	PROCEDURE COND_VEH_APEP_MIG
	IS
		CURSOR CUR_VIG_COND_VEH (
			pRAMO 		ACSMIGRE.VIG_COND_VEH.RAMO_AS@DESA%TYPE,
			pPOLIZA		ACSMIGRE.VIG_COND_VEH.POLIZA_AS@DESA%TYPE,
			pNUMCERT 	ACSMIGRE.VIG_COND_VEH.NUMCERT@DESA%TYPE
		)
		IS
		SELECT * FROM ACSMIGRE.VIG_COND_VEH@DESA
		WHERE RAMO_AS = pRamo
		AND POLIZA_AS = pPOLIZA
		AND NUMCERT = pNUMCERT;
		--
		RT_CUR_VIG_COND_VEH	CUR_VIG_COND_VEH%ROWTYPE;
		--
		CURSOR CUR_CONDUCTORES_IND
		IS
		WITH EQ AS (
			SELECT DISTINCT RAMO,POLIZA,NUMCERT,TIPOID,NUMID,DVID,CODCLI,STSCERT,FECING,CODPARENT
			FROM EQ_SINIESTRO_REN
			WHERE MIGRA = 'S'
		)
		SELECT DISTINCT
			GG.RAMO,GG.POLIZA,EQ.NUMCERT,EQ.CODCLI,EQ.TIPOID,EQ.NUMID,EQ.DVID,'S' AS VINDCONDPRINC,
			EQ.CODPARENT VCODPARENT,EQ.STSCERT AS VSTSCONDVEH,EQ.FECING AS VFECING,0 AS VNUMLIC,
			GG.GRALIC AS VGRADOLIC,NVL(TO_NUMBER(SUBSTR(GG.AÑOEXP,3,4)),0) AS VANOSEXPER
		FROM HJPF03_REN GG,EQ
		WHERE GG.RAMO = EQ.RAMO
		AND GG.POLIZA = EQ.POLIZA
		AND GG.RAMO IN (32,33,34,35)
		AND GG.GRALIC IN ('0','1','2','3','4','5','6','7','8','9');
		--
		CURSOR cur_conductores_col
		IS
		WITH EQ AS (
			SELECT DISTINCT RAMO,POLIZA,TIPOID,NUMID,DVID,CODCLI,NUMCERT,STSCERT,FECING,CODPARENT
			FROM EQ_SINIESTRO_REN
			WHERE MIGRA = 'S'
		)
		SELECT DISTINCT
			GG.RAMO,GG.POLIZA,EQ.CODCLI,EQ.TIPOID,EQ.NUMID,EQ.DVID,EQ.NUMCERT,TO_NUMBER (EQ.NUMCERT) AS VNUMCERT,
			'S' AS VINDCONDPRINC,EQ.CODPARENT VCODPARENT,EQ.STSCERT AS VSTSCONDVEH,EQ.FECING AS VFECING,0 AS VNUMLIC,
			GG.GRALIC AS VGRADOLIC,NVL(TO_NUMBER(SUBSTR(GG.AÑOEXP,3,4)),0) AS VANOSEXPER
		FROM CLPF07_REN GG,EQ
		WHERE EQ.RAMO = GG.RAMO
		AND EQ.POLIZA = GG.POLIZA
		AND TO_NUMBER (GG.CERVEH) = EQ.NUMCERT
		AND GG.GRALIC IN ('0','1','2','3','4','5','6','7','8','9')
		AND GG.RAMO = 31;
	BEGIN
		BEGIN
			FOR I IN (SELECT ROWID FROM ACSMIGRE.VIG_COND_VEH@DESA)
			LOOP
				DELETE FROM ACSMIGRE.VIG_COND_VEH@DESA
				WHERE ROWID = I.ROWID;
				COMMIT;
			END LOOP;
			--
			FOR MM IN CUR_CONDUCTORES_IND
			LOOP
				BEGIN
					OPEN CUR_VIG_COND_VEH (MM.RAMO,MM.POLIZA,MM.NUMCERt);
					FETCH CUR_VIG_COND_VEH INTO RT_CUR_VIG_COND_VEH;

					IF CUR_VIG_COND_VEH%NOTFOUND THEN
						INSERT INTO ACSMIGRE.VIG_COND_VEH@DESA (
							RAMO_AS,POLIZA_AS,NUMCERT,CODCLI,INDCONDPRINC,CODPARENT,
							STSCONDVEH,FECING,GRADOLIC,ANOSEXPER,TIPOID,NUMID,DVID
						)
						VALUES (
							MM.RAMO,MM.POLIZA,MM.NUMCERt,MM.CODCLI,MM.VINDCONDPRINC,MM.VCODPARENT,MM.VSTSCONDVEH,
							MM.VFECING,MM.VGRADOLIC,MM.VANOSEXPER,MM.TIPOID,MM.NUMID,MM.DVID
						);
						COMMIT;
					END IF;
					CLOSE CUR_VIG_COND_VEH;
				END;
			END LOOP;
			--
			FOR dd IN cur_conductores_col
			LOOP
				BEGIN
					OPEN CUR_VIG_COND_VEH (dd.RAMO,dd.POLIZA,dd.vnumcert);
					FETCH CUR_VIG_COND_VEH INTO RT_CUR_VIG_COND_VEH;

					IF CUR_VIG_COND_VEH%NOTFOUND THEN
						INSERT INTO ACSMIGRe.vig_cond_veh@desa (
							RAMO_AS,POLIZA_AS,numcert,codcli,indcondprinc,codparent,
							stscondveh,fecing,gradolic,anosexper,tipoid,numid,dvid
						)
						VALUES (
							dd.RAMO,dd.POLIZA,dd.vnumcert,dd.codcli,dd.vindcondprinc,dd.vcodparent,dd.vstscondveh,
							dd.vfecing,dd.vgradolic,dd.vanosexper,dd.tipoid,dd.numid,dd.dvid
						);
						COMMIT;
					END IF;
					CLOSE CUR_VIG_COND_VEH;
				END;
			END LOOP;
		END;
	END COND_VEH_APEP_MIG;
	--
	PROCEDURE DIREC_COBROPOLIZA_MIG
	IS
		CURSOR DIREC_POL
		IS
		WITH EQ AS (
			SELECT /*+ FRIST_ROWS*/ Ramo,Poliza
			FROM EQ_SINIESTRO_REN EQ
			WHERE Migra = 'S'
			AND NOT EXISTS (
				SELECT 'X' FROM EQ_POLIZA_NO_MIGRADO
				WHERE MIGRA = 'S'
				AND Ramo = EQ.Ramo
				AND Poliza = EQ.Poliza
				AND CodCob = 6730
				AND CodProd = 'AUTI'
			)
			GROUP BY Ramo,Poliza
		)
		SELECT
			EQ.Ramo,EQ.Poliza,NVL(PM.ELIMINA_ESPACIOS (POL.Dircb1),'POR CONVERSION') Direc,
			DECODE (Telef,0,NULL) Telef1,'001' CodPais,PM.BUSQUEDA_LOCALIDAD(POL.ZonCob,'E') Codestado,
			PM.BUSQUEDA_LOCALIDAD (POL.ZonCob,'C') CodCiudad,PM.BUSQUEDA_LOCALIDAD (POL.ZonCob,'M') CodMunicipio,
			'9999' ZonaPostal,'9999' ZonaCobro,PM.CONVIERTE_DIAMESANO_FECHA (POL.DiaDes,POL.Mesdes,POL.AnoDes) FecSts
		FROM HJPF01_REN POL,EQ
		WHERE EQ.Ramo = POL.Ramo
		AND EQ.Poliza = POL.Poliza;
	BEGIN
		DELETE FROM ACSMIGRE.VIG_DIREC_COBROPOLIZA@DESA;
		COMMIT;
		--
		FOR c IN DIREC_POL
		LOOP
			INSERT INTO ACSMIGRE.VIG_DIREC_COBROPOLIZA@DESA (
				RAMO_AS,POLIZA_AS,Direc,Telef1,Fax,Telef2,Telex,Telef3,CodPais,CodEstado,
				CodCiudad,CodMunicipio,ZonaPostal,ZonaCobro,FecSts
			)
			VALUES (
				c.RAMO,C.POLIZA,c.Direc,c.Telef1,NULL,NULL,NULL,NULL,c.CodPais,c.CodEstado,
				c.CodCiudad,c.CodMunicipio,c.ZonaPostal,c.ZonaCobro,c.FecSts
			);
			COMMIT;
		END LOOP;
	END DIREC_COBROPOLIZA_MIG;
END MIG_POLIZA_REN;