DECLARE
	CURSOR EQ_COBERTURA
	IS
	SELECT
		EQ.RAMO,EQ.POLIZA,EQ.NUMREC,
		EQ.NUMCER,EQ.CODCOB,EQ.CODCLI,
		EQ.COFAAM FROM (
			SELECT
				CODCLI,RAMO,POLIZA,NUMREC,EDAD,
				DECODE(DECODE(ACARGU,99,(
					SELECT DECODE (SEXO,1, 'F',2, 'M','WTF')
					FROM HJPF01 
					WHERE RAMO = EQ_HJPF71.RAMO
					AND POLIZA = EQ_HJPF71.POLIZA
					AND NUMREC = EQ_HJPF71.NUMREC
				),
				SUBSTR (TRIM (ACFUNC), -2, 1)), 'M', 'M','F', 'F','M') SEXO
			FROM EQ_HJPF71, CTRALTAB
			WHERE ACTIAR = 114 
			AND ACARGU = EQ_HJPF71.CODPAR
		) ASEGURADO, EQ_COBERTURAS_IND EQ
	WHERE EQ.RAMO = ASEGURADO.RAMO
	AND EQ.POLIZA = ASEGURADO.POLIZA
	AND EQ.NUMREC = ASEGURADO.NUMREC
	AND EQ.RAMO = 26
	AND EQ.CODCOB = 2643
	AND (SEXO = 'M' OR (EDAD < 14 OR EDAD > 40));
BEGIN
	FOR C IN EQ_COBERTURA
	LOOP
		DELETE FROM EQ_COBERTURAS_IND
		WHERE RAMO = C.RAMO
		AND POLIZA = C.POLIZA
		AND NUMREC = C.NUMREC
		AND NUMCER = C.NUMCER
		AND CODCOB = C.CODCOB
		AND CODCLI = C.CODCLI
		AND COFAAM = C.COFAAM;
		ROLLBACK;
   END LOOP;
END;
--
DECLARE
	CURSOR CUR_CUADRE_PRIMA
	IS
	WITH ASEGURADO AS (
		SELECT NUMREC, RAMO,POLIZA,
		(PRMEXB + PRMBSB + PRMGAB + PRMOTB + PRMEXE + PRMGAE + PRMOTE) PRIMAASEGURADO
		FROM HJPF71
	), 
	COBERTURA AS (
		SELECT NumRec, Ramo, Poliza, SUM (Primar) PRIMACOBERTURA 
		FROM HJPF05
		GROUP BY NumRec, Ramo, Poliza
	),
	EQ AS (
		SELECT NumRec, Ramo, Poliza, SUM (Pricap) PRIMAEQ
		FROM EQ_COBERTURAS_IND
		GROUP BY NumRec, Ramo, Poliza
	),
	COBERTURA_ASEGURADO AS (
		SELECT 	COBERTURA.Ramo,
				Cobertura.Poliza,
				COBERTURA.NumRec,
				MAX (COBERTURA.PRIMACOBERTURA) PRIMACOBERTURA,
				SUM (ASEGURADO.PRIMAASEGURADO) PRIMAASEGURADO
		FROM COBERTURA, ASEGURADO
		WHERE COBERTURA.Ramo = ASEGURADO.Ramo
		AND COBERTURA.Poliza = ASEGURADO.Poliza
		AND COBERTURA.NumRec = ASEGURADO.NumRec
		GROUP BY COBERTURA.Ramo, COBERTURA.Poliza, COBERTURA.NumRec
		ORDER BY COBERTURA.NumRec
	)
	SELECT 	EQ.Ramo,
			EQ.Poliza,
			EQ.NumRec,
			PrimaCobertura,
			PrimaAsegurado,
			(Primacobertura - PrimaAsegurado) Diferencia
	FROM COBERTURA_ASEGURADO, EQ
	WHERE (Primacobertura - PrimaAsegurado) <> 0
	AND COBERTURA_ASEGURADO.Ramo = EQ.Ramo
	AND COBERTURA_ASEGURADO.Poliza = EQ.Poliza
	AND COBERTURA_ASEGURADO.NumRec = EQ.NumRec;

	CURSOR CUR_HJPF71 (P_RAMO EQ_COBERTURAS_IND.RAMO%TYPE)
	IS
	SELECT RAMO FROM HJPF71 WHERE RAMO = P_RAMO;

	RT_CUR_HJPF71 CUR_HJPF71%ROWTYPE;
	DUMMY NUMBER := 0;
BEGIN
	FOR C IN CUR_CUADRE_PRIMA
	LOOP
		OPEN CUR_HJPF71 (C.RAMO);
		FETCH CUR_HJPF71 INTO RT_CUR_HJPF71;

		IF CUR_HJPF71%FOUND THEN
			UPDATE EQ_COBERTURAS_IND
			SET PRIMAR = 99999999999.99
			WHERE RAMO = C.RAMO 
			AND POLIZA = C.POLIZA 
			AND NUMREC = C.NUMREC;
			
			ROLLBACK;
			DUMMY := DUMMY + 1;
		END IF;

		CLOSE CUR_HJPF71;
	END LOOP;
	DBMS_OUTPUT.put_line (DUMMY);
END;