SELECT * FROM (
    SELECT 'EQ_HJPF01' NOMTABLA, COUNT (*) CANTIDAD FROM (
        SELECT TIPOID,NUMID,DVID,CODCLI
        FROM EQ_HJPF01
        GROUP BY TIPOID,NUMID,DVID,CODCLI
    )
    UNION ALL
    SELECT 'EQ_HJPF205', COUNT (*) FROM (
        SELECT TIPOID,NUMID,DVID,CODCLI FROM EQ_HJPF205
        GROUP BY TIPOID,NUMID,DVID,CODCLI
    )
	UNION ALL
	SELECT 'EQ_FNPF01', COUNT (*) FROM (
        SELECT TIPOID,NUMID,DVID,CODCLI FROM EQ_FNPF01
        GROUP BY TIPOID,NUMID,DVID,CODCLI
    )
    UNION ALL
    SELECT 'EQ_ORDENE', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_ORDENE
        GROUP BY TIPOID,NUMID,DVID,CODCLI
    )
    UNION ALL
    SELECT 'EQ_ORPF06', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_ORPF06
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_CLPF07', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_CLPF07
        GROUP BY TIPOID,NUMID,DVID,CODCLI
    )
    UNION ALL
    SELECT 'EQ_HJPF06', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_HJPF06
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_HJPF71', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_HJPF71
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_CLPF05_FAM', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI
        FROM EQ_CLPF05_FAM
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
);
--
SELECT * FROM (
    SELECT 'EQ_HJPF01' NOMTABLA, COUNT (*) CANTIDAD FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_HJPF01
        WHERE TRIM (TIPOID) IS NOT NULL
        AND TRIM (NUMID) IS NOT NULL
        AND TRIM (DVID) IS NOT NULL
        AND TRIM (CODCLI) IS NOT NULL
        AND TRIM (INDNACIONAL) IS NOT NULL
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_HJPF205', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_HJPF205
        WHERE TRIM (TIPOID) IS NOT NULL
        AND TRIM (NUMID) IS NOT NULL
        AND TRIM (DVID) IS NOT NULL
        AND TRIM (CODCLI) IS NOT NULL
        AND TRIM (INDNACIONAL) IS NOT NULL
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_FNPF01', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_FNPF01
        WHERE TRIM (TIPOID) IS NOT NULL
        AND TRIM (NUMID) IS NOT NULL
        AND TRIM (DVID) IS NOT NULL
        AND TRIM (CODCLI) IS NOT NULL
        AND TRIM (INDNACIONAL) IS NOT NULL
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_ORDENE', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_ORDENE
        WHERE TRIM (TIPOID) IS NOT NULL
        AND TRIM (NUMID) IS NOT NULL
        AND TRIM (DVID) IS NOT NULL
        AND TRIM (CODCLI) IS NOT NULL
        AND TRIM (INDNACIONAL) IS NOT NULL
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_ORPF06', COUNT (*) FROM (
        SELECT TIPOID,NUMID, DVID, CODCLI FROM EQ_ORPF06
        WHERE TRIM (TIPOID) IS NOT NULL
        AND TRIM (NUMID) IS NOT NULL
        AND TRIM (DVID) IS NOT NULL
        AND TRIM (CODCLI) IS NOT NULL
        AND TRIM (INDNACIONAL) IS NOT NULL
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_CLPF07', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_CLPF07
        WHERE TRIM (TIPOID) IS NOT NULL
        AND TRIM (NUMID) IS NOT NULL
        AND TRIM (DVID) IS NOT NULL
        AND TRIM (CODCLI) IS NOT NULL
        AND TRIM (INDNACIONAL) IS NOT NULL
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_HJPF06', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_HJPF06
        WHERE TRIM (TIPOID) IS NOT NULL
        AND TRIM (NUMID) IS NOT NULL
        AND TRIM (DVID) IS NOT NULL
        AND TRIM (CODCLI) IS NOT NULL
        AND TRIM (INDNACIONAL) IS NOT NULL
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_HJPF71', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_HJPF71
        WHERE TRIM (TIPOID) IS NOT NULL
        AND TRIM (NUMID) IS NOT NULL
        AND TRIM (DVID) IS NOT NULL
        AND TRIM (CODCLI) IS NOT NULL
        AND TRIM (INDNACIONAL) IS NOT NULL
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_CLPF05_FAM', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_CLPF05_FAM
        WHERE TRIM (TIPOID) IS NOT NULL
        AND TRIM (NUMID) IS NOT NULL
        AND TRIM (DVID) IS NOT NULL
        AND TRIM (CODCLI) IS NOT NULL
        AND TRIM (INDNACIONAL) IS NOT NULL
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
);
--
SELECT * FROM (
    SELECT 'EQ_HJPF01' NOMTABLA, COUNT (*) CANTIDAD FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_HJPF01
        WHERE TRIM (TIPOID) IS NULL
        OR TRIM (NUMID) IS NULL
        OR TRIM (DVID) IS NULL
        OR TRIM (CODCLI) IS NULL
        OR TRIM (INDNACIONAL) IS NULL
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_HJPF205', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_HJPF205
        WHERE TRIM (TIPOID) IS NULL
        OR TRIM (NUMID) IS NULL
        OR TRIM (DVID) IS NULL
        OR TRIM (CODCLI) IS NULL
        OR TRIM (INDNACIONAL) IS NULL
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_FNPF01', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_FNPF01
        WHERE TRIM (TIPOID) IS NULL
        OR TRIM (NUMID) IS NULL
        OR TRIM (DVID) IS NULL
        OR TRIM (CODCLI) IS NULL
        OR TRIM (INDNACIONAL) IS NULL
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_ORDENE', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_ORDENE
        WHERE TRIM (TIPOID) IS NULL
        OR TRIM (NUMID) IS NULL
        OR TRIM (DVID) IS NULL
        OR TRIM (CODCLI) IS NULL
        OR TRIM (INDNACIONAL) IS NULL
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_ORPF06', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_ORPF06
        WHERE TRIM (TIPOID) IS NULL
        OR TRIM (NUMID) IS NULL
        OR TRIM (DVID) IS NULL
        OR TRIM (CODCLI) IS NULL
        OR TRIM (INDNACIONAL) IS NULL
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_CLPF07', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_CLPF07
        WHERE TRIM (TIPOID) IS NULL
        OR TRIM (NUMID) IS NULL
        OR TRIM (DVID) IS NULL
        OR TRIM (CODCLI) IS NULL
        OR TRIM (INDNACIONAL) IS NULL
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_HJPF06', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_HJPF06
        WHERE TRIM (TIPOID) IS NULL
        OR TRIM (NUMID) IS NULL
        OR TRIM (DVID) IS NULL
        OR TRIM (CODCLI) IS NULL
        OR TRIM (INDNACIONAL) IS NULL
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_HJPF71', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_HJPF71
        WHERE TRIM (TIPOID) IS NULL
        OR TRIM (NUMID) IS NULL
        OR TRIM (DVID) IS NULL
        OR TRIM (CODCLI) IS NULL
        OR TRIM (INDNACIONAL) IS NULL
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_CLPF05_FAM', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_CLPF05_FAM
        WHERE TRIM (TIPOID) IS NULL
        OR TRIM (NUMID) IS NULL
        OR TRIM (DVID) IS NULL
        OR TRIM (CODCLI) IS NULL
        OR TRIM (INDNACIONAL) IS NULL
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
);
--
SELECT * FROM (
    SELECT 'EQ_HJPF01' NOMTABLA, COUNT (*) CANTIDAD FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_HJPF01 A
        WHERE TRIM (A.TIPOID) IS NOT NULL
        AND TRIM (A.NUMID) IS NOT NULL
        AND TRIM (A.DVID) IS NOT NULL
        AND TRIM (A.CODCLI) IS NOT NULL
        AND TRIM (A.INDNACIONAL) IS NOT NULL
        AND EXISTS (
            SELECT * FROM TERCERO_MIG_PRUEBA B
            WHERE B.TIPOID = A.TIPOID
            AND B.NUMID = A.NUMID
            AND B.DVID = A.DVID
        )
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_HJPF205', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_HJPF205 A
        WHERE TRIM (A.TIPOID) IS NOT NULL
        AND TRIM (A.NUMID) IS NOT NULL
        AND TRIM (A.DVID) IS NOT NULL
        AND TRIM (A.CODCLI) IS NOT NULL
        AND TRIM (A.INDNACIONAL) IS NOT NULL
        AND EXISTS (
            SELECT * FROM TERCERO_MIG_PRUEBA B
            WHERE B.TIPOID = A.TIPOID
            AND B.NUMID = A.NUMID
            AND B.DVID = A.DVID
        )
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_FNPF01', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_FNPF01 A
        WHERE TRIM (A.TIPOID) IS NOT NULL
        AND TRIM (A.NUMID) IS NOT NULL
        AND TRIM (A.DVID) IS NOT NULL
        AND TRIM (A.CODCLI) IS NOT NULL
        AND TRIM (A.INDNACIONAL) IS NOT NULL
        AND EXISTS (
            SELECT * FROM TERCERO_MIG_PRUEBA B
            WHERE B.TIPOID = A.TIPOID
            AND B.NUMID = A.NUMID
            AND B.DVID = A.DVID
        )
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_ORDENE', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_ORDENE A
        WHERE TRIM (A.TIPOID) IS NOT NULL
        AND TRIM (A.NUMID) IS NOT NULL
        AND TRIM (A.DVID) IS NOT NULL
        AND TRIM (A.CODCLI) IS NOT NULL
        AND TRIM (A.INDNACIONAL) IS NOT NULL
        AND EXISTS (
            SELECT * FROM TERCERO_MIG_PRUEBA B
            WHERE B.TIPOID = A.TIPOID
            AND B.NUMID = A.NUMID
            AND B.DVID = A.DVID
        )
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_ORPF06', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_ORPF06 A
        WHERE TRIM (A.TIPOID) IS NOT NULL
        AND TRIM (A.NUMID) IS NOT NULL
        AND TRIM (A.DVID) IS NOT NULL
        AND TRIM (A.CODCLI) IS NOT NULL
        AND TRIM (A.INDNACIONAL) IS NOT NULL
        AND EXISTS (
            SELECT * FROM TERCERO_MIG_PRUEBA B
            WHERE B.TIPOID = A.TIPOID
            AND B.NUMID = A.NUMID
            AND B.DVID = A.DVID
        )
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_CLPF07', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_CLPF07 A
        WHERE TRIM (A.TIPOID) IS NOT NULL
        AND TRIM (A.NUMID) IS NOT NULL
        AND TRIM (A.DVID) IS NOT NULL
        AND TRIM (A.CODCLI) IS NOT NULL
        AND TRIM (A.INDNACIONAL) IS NOT NULL
        AND EXISTS (
            SELECT * FROM TERCERO_MIG_PRUEBA B
            WHERE B.TIPOID = A.TIPOID
            AND B.NUMID = A.NUMID
            AND B.DVID = A.DVID
        )
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_HJPF06', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_HJPF06 A
        WHERE TRIM (A.TIPOID) IS NOT NULL
        AND TRIM (A.NUMID) IS NOT NULL
        AND TRIM (A.DVID) IS NOT NULL
        AND TRIM (A.CODCLI) IS NOT NULL
        AND TRIM (A.INDNACIONAL) IS NOT NULL
        AND EXISTS (
            SELECT * FROM TERCERO_MIG_PRUEBA B
            WHERE B.TIPOID = A.TIPOID
            AND B.NUMID = A.NUMID
            AND B.DVID = A.DVID
        )
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_HJPF71', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_HJPF71 A
        WHERE TRIM (A.TIPOID) IS NOT NULL
        AND TRIM (A.NUMID) IS NOT NULL
        AND TRIM (A.DVID) IS NOT NULL
        AND TRIM (A.CODCLI) IS NOT NULL
        AND TRIM (A.INDNACIONAL) IS NOT NULL
        AND EXISTS (
            SELECT * FROM TERCERO_MIG_PRUEBA B
            WHERE B.TIPOID = A.TIPOID
            AND B.NUMID = A.NUMID
            AND B.DVID = A.DVID
        )
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_CLPF05_FAM', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_CLPF05_FAM A
        WHERE TRIM (A.TIPOID) IS NOT NULL
        AND TRIM (A.NUMID) IS NOT NULL
        AND TRIM (A.DVID) IS NOT NULL
        AND TRIM (A.CODCLI) IS NOT NULL
        AND TRIM (A.INDNACIONAL) IS NOT NULL
        AND EXISTS (
            SELECT * FROM TERCERO_MIG_PRUEBA B
            WHERE B.TIPOID = A.TIPOID
            AND B.NUMID = A.NUMID
            AND B.DVID = A.DVID
        )
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
);
--
SELECT * FROM (
    SELECT 'EQ_HJPF01' NOMTABLA, COUNT (*) CANTIDAD FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_HJPF01 A
        WHERE TRIM (A.TIPOID) IS NOT NULL
        AND TRIM (A.NUMID) IS NOT NULL
        AND TRIM (A.DVID) IS NOT NULL
        AND TRIM (A.CODCLI) IS NOT NULL
        AND TRIM (A.INDNACIONAL) IS NOT NULL
        AND NOT EXISTS (
            SELECT * FROM TERCERO_MIG_PRUEBA B
            WHERE B.TIPOID = A.TIPOID
            AND B.NUMID = A.NUMID
            AND B.DVID = A.DVID
        )
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_HJPF205', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_HJPF205 A
        WHERE TRIM (A.TIPOID) IS NOT NULL
        AND TRIM (A.NUMID) IS NOT NULL
        AND TRIM (A.DVID) IS NOT NULL
        AND TRIM (A.CODCLI) IS NOT NULL
        AND TRIM (A.INDNACIONAL) IS NOT NULL
        AND NOT EXISTS (
            SELECT * FROM TERCERO_MIG_PRUEBA B
            WHERE B.TIPOID = A.TIPOID
            AND B.NUMID = A.NUMID
            AND B.DVID = A.DVID
        )
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_FNPF01', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_FNPF01 A
        WHERE TRIM (A.TIPOID) IS NOT NULL
        AND TRIM (A.NUMID) IS NOT NULL
        AND TRIM (A.DVID) IS NOT NULL
        AND TRIM (A.CODCLI) IS NOT NULL
        AND TRIM (A.INDNACIONAL) IS NOT NULL
        AND NOT EXISTS (
            SELECT * FROM TERCERO_MIG_PRUEBA B
            WHERE B.TIPOID = A.TIPOID
            AND B.NUMID = A.NUMID
            AND B.DVID = A.DVID
        )
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_ORDENE', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_ORDENE A
        WHERE TRIM (A.TIPOID) IS NOT NULL
        AND TRIM (A.NUMID) IS NOT NULL
        AND TRIM (A.DVID) IS NOT NULL
        AND TRIM (A.CODCLI) IS NOT NULL
        AND TRIM (A.INDNACIONAL) IS NOT NULL
        AND NOT EXISTS (
            SELECT * FROM TERCERO_MIG_PRUEBA B
            WHERE B.TIPOID = A.TIPOID
            AND B.NUMID = A.NUMID
            AND B.DVID = A.DVID
        )
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_ORPF06', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_ORPF06 A
        WHERE TRIM (A.TIPOID) IS NOT NULL
        AND TRIM (A.NUMID) IS NOT NULL
        AND TRIM (A.DVID) IS NOT NULL
        AND TRIM (A.CODCLI) IS NOT NULL
        AND TRIM (A.INDNACIONAL) IS NOT NULL
        AND NOT EXISTS (
            SELECT * FROM TERCERO_MIG_PRUEBA B
            WHERE B.TIPOID = A.TIPOID
            AND B.NUMID = A.NUMID
            AND B.DVID = A.DVID
        )
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_CLPF07', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_CLPF07 A
        WHERE TRIM (A.TIPOID) IS NOT NULL
        AND TRIM (A.NUMID) IS NOT NULL
        AND TRIM (A.DVID) IS NOT NULL
        AND TRIM (A.CODCLI) IS NOT NULL
        AND TRIM (A.INDNACIONAL) IS NOT NULL
        AND NOT EXISTS (
            SELECT * FROM TERCERO_MIG_PRUEBA B
            WHERE B.TIPOID = A.TIPOID
            AND B.NUMID = A.NUMID
            AND B.DVID = A.DVID
        )
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_HJPF06', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_HJPF06 A
        WHERE TRIM (A.TIPOID) IS NOT NULL
        AND TRIM (A.NUMID) IS NOT NULL
        AND TRIM (A.DVID) IS NOT NULL
        AND TRIM (A.CODCLI) IS NOT NULL
        AND TRIM (A.INDNACIONAL) IS NOT NULL
        AND NOT EXISTS (
            SELECT * FROM TERCERO_MIG_PRUEBA B
            WHERE B.TIPOID = A.TIPOID
            AND B.NUMID = A.NUMID
            AND B.DVID = A.DVID
        )
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_HJPF71', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_HJPF71 A
        WHERE TRIM (A.TIPOID) IS NOT NULL
        AND TRIM (A.NUMID) IS NOT NULL
        AND TRIM (A.DVID) IS NOT NULL
        AND TRIM (A.CODCLI) IS NOT NULL
        AND TRIM (A.INDNACIONAL) IS NOT NULL
        AND NOT EXISTS (
            SELECT * FROM TERCERO_MIG_PRUEBA B
            WHERE B.TIPOID = A.TIPOID
            AND B.NUMID = A.NUMID
            AND B.DVID = A.DVID
        )
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
    UNION ALL
    SELECT 'EQ_CLPF05_FAM', COUNT (*) FROM (
        SELECT TIPOID, NUMID, DVID, CODCLI FROM EQ_CLPF05_FAM A
        WHERE TRIM (A.TIPOID) IS NOT NULL
        AND TRIM (A.NUMID) IS NOT NULL
        AND TRIM (A.DVID) IS NOT NULL
        AND TRIM (A.CODCLI) IS NOT NULL
        AND TRIM (A.INDNACIONAL) IS NOT NULL
        AND NOT EXISTS (
            SELECT * FROM TERCERO_MIG_PRUEBA B
            WHERE B.TIPOID = A.TIPOID
            AND B.NUMID = A.NUMID
            AND B.DVID = A.DVID
        )
        GROUP BY TIPOID, NUMID, DVID, CODCLI
    )
);