SELECT APTO, RAZONAPTO, COUNT (*)
FROM SINIESTROS_MIGRA_REN
GROUP BY APTO, RAZONAPTO
ORDER BY COUNT (*) DESC;
--
SELECT MIGRA, RAZONMIGRA, COUNT (*)
FROM EQ_SINIESTRO_REN
GROUP BY MIGRA, RAZONMIGRA
ORDER BY COUNT (*) DESC;
--
SELECT MIGRA, MIGRAREA, COUNT (*)
FROM EQ_SINIESTRO_REN
GROUP BY MIGRA, MIGRAREA;
--
SELECT CODFORMFCION, COUNT (*)
FROM EQ_SINIESTRO_REN
WHERE MIGRA = 'S'
GROUP BY CODFORMFCION
ORDER BY COUNT (*) DESC;
--
SELECT TASACAMBIO, COUNT (*)
FROM EQ_SINIESTRO_REN
WHERE MIGRA = 'S'
GROUP BY TASACAMBIO
ORDER BY COUNT (*) DESC;
--
SELECT SUMAASEGMONEDA, COUNT (*)
FROM EQ_SINIESTRO_REN
WHERE MIGRA = 'S'
GROUP BY SUMAASEGMONEDA
ORDER BY COUNT (*) DESC;
--
SELECT TIPOMOV, COUNT (*)
FROM EQ_SINIESTRO_REN
WHERE MIGRA = 'S'
GROUP BY TIPOMOV
ORDER BY COUNT (*) DESC;
--
SELECT APTO, RAZONAPTO, COUNT (*) FROM SINIESTROS_MIGRA_REN
GROUP BY APTO, RAZONAPTO
ORDER BY COUNT (*) DESC;
--
SELECT MIGRA, RAZONMIGRA, COUNT (*) FROM EQ_SINIESTRO_REN
GROUP BY MIGRA, RAZONMIGRA
ORDER BY COUNT (*) DESC;
--
SELECT MIGRA, MIGRAREA, COUNT (*) FROM EQ_SINIESTRO_REN
GROUP BY MIGRA, MIGRAREA;
--
SELECT CODFORMFCION, COUNT (*) FROM EQ_SINIESTRO_REN
WHERE MIGRA = 'S'
GROUP BY CODFORMFCION
ORDER BY COUNT (*) DESC;
--
SELECT TASACAMBIO, COUNT (*) FROM EQ_SINIESTRO_REN
WHERE MIGRA = 'S'
GROUP BY TASACAMBIO
ORDER BY COUNT (*) DESC;
--
SELECT SUMAASEGMONEDA, COUNT (*) FROM EQ_SINIESTRO_REN
WHERE MIGRA = 'S'
GROUP BY SUMAASEGMONEDA
ORDER BY COUNT (*) DESC;
--
SELECT TIPOMOV, COUNT (*) FROM EQ_SINIESTRO_REN
WHERE MIGRA = 'S'
GROUP BY TIPOMOV
ORDER BY COUNT (*) DESC;