SELECT * FROM (
    SELECT 'EQ_HJPF01', COUNT (*) TOTAL FROM EQ_HJPF01
    WHERE TRIM (TIPOID) IS NULL
    OR TRIM (NUMID) IS NULL
    OR TRIM (DVID) IS NULL
    OR TRIM (CODCLI) IS NULL
    OR TRIM (INDNACIONAL) IS NULL
    UNION ALL
    SELECT 'EQ_HJPF205', COUNT (*) FROM EQ_HJPF205
    WHERE TRIM (TIPOID) IS NULL
    OR TRIM (NUMID) IS NULL
    OR TRIM (DVID) IS NULL
    OR TRIM (CODCLI) IS NULL
    OR TRIM (INDNACIONAL) IS NULL
    UNION ALL
    SELECT 'EQ_FNPF01', COUNT (*) FROM EQ_FNPF01
    WHERE TRIM (TIPOID) IS NULL
    OR TRIM (NUMID) IS NULL
    OR TRIM (DVID) IS NULL
    OR TRIM (CODCLI) IS NULL
    OR TRIM (INDNACIONAL) IS NULL
    UNION ALL
    SELECT 'EQ_ORDENE', COUNT (*) FROM EQ_ORDENE
    WHERE TRIM (TIPOID) IS NULL
    OR TRIM (NUMID) IS NULL
    OR TRIM (DVID) IS NULL
    OR TRIM (CODCLI) IS NULL
    OR TRIM (INDNACIONAL) IS NULL
    UNION ALL
    SELECT 'EQ_ORPF06', COUNT (*) FROM EQ_ORPF06
    WHERE TRIM (TIPOID) IS NULL
    OR TRIM (NUMID) IS NULL
    OR TRIM (DVID) IS NULL
    OR TRIM (CODCLI) IS NULL
    OR TRIM (INDNACIONAL) IS NULL
    UNION ALL
    SELECT 'EQ_CLPF07', COUNT (*) FROM EQ_CLPF07
    WHERE TRIM (TIPOID) IS NULL
    OR TRIM (NUMID) IS NULL
    OR TRIM (DVID) IS NULL
    OR TRIM (CODCLI) IS NULL
    OR TRIM (INDNACIONAL) IS NULL
    UNION ALL
    SELECT 'EQ_HJPF06', COUNT (*) FROM EQ_HJPF06
    WHERE TRIM (TIPOID) IS NULL
    OR TRIM (NUMID) IS NULL
    OR TRIM (DVID) IS NULL
    OR TRIM (CODCLI) IS NULL
    OR TRIM (INDNACIONAL) IS NULL
)