SELECT COUNT (*) FROM EQ_SINIESTRO
UNION ALL
SELECT COUNT (*) FROM LOG_SINIESTRO_MIG
UNION ALL
SELECT COUNT (*) FROM ERR_MIG_SINIESTRO;
--
SELECT OBSERVACIONES, COUNT (*) FROM ERR_MIG_SINIESTRO
WHERE TIPOERROR = 'ERR-SIN-CARGA-BASE'
GROUP BY OBSERVACIONES
ORDER BY COUNT (*) DESC;
--
SELECT RAMOAS, COUNT (*) FROM EQ_SINIESTRO
WHERE NUMCERTAS IS NULL
GROUP BY RAMOAS
ORDER BY COUNT (*) DESC;