DROP TABLE HJPF01_REN;
CREATE TABLE HJPF01_REN AS (SELECT * FROM HJPF01_REN@SQLDESARROLLODSN);
--
DROP TABLE HJPF02_REN;
CREATE TABLE HJPF02_REN AS (SELECT * FROM HJPF02_REN@SQLDESARROLLODSN);
--
DROP TABLE HJPF03_REN;
CREATE TABLE HJPF03_REN AS (SELECT * FROM HJPF03_REN@SQLDESARROLLODSN);
--
DROP TABLE HJPF05_REN;
CREATE TABLE HJPF05_REN AS (SELECT * FROM HJPF05_REN@SQLDESARROLLODSN);
--
DROP TABLE REPF14_REN;
CREATE TABLE REPF14_REN AS (SELECT * FROM REPF14_REN@SQLDESARROLLODSN);
--
DROP TABLE REPF15_REN;
CREATE TABLE REPF15_REN AS (SELECT * FROM REPF15_REN@SQLDESARROLLODSN);
--
DROP TABLE HJPF25_REN;
CREATE TABLE HJPF25_REN AS (SELECT * FROM HJPF25_REN@SQLDESARROLLODSN);
--
DROP TABLE HJPF26_REN;
CREATE TABLE HJPF26_REN AS (SELECT * FROM HJPF26_REN@SQLDESARROLLODSN);
--
DROP TABLE HJPF27_REN;
CREATE TABLE HJPF27_REN AS (SELECT * FROM HJPF27_REN@SQLDESARROLLODSN);
--
DROP TABLE HJPF29_REN;
CREATE TABLE HJPF29_REN AS (SELECT * FROM HJPF29_REN@SQLDESARROLLODSN);
--
DROP TABLE FNPF05_REN;
CREATE TABLE FNPF05_REN AS (SELECT * FROM FNPF05_REN@SQLDESARROLLODSN);
--
DROP TABLE HJPF71_REN;
CREATE TABLE HJPF71_REN AS (SELECT * FROM HJPF71_REN@SQLDESARROLLODSN);
--
DROP TABLE HJPF75_REN;
CREATE TABLE HJPF75_REN AS (SELECT * FROM HJPF75_REN@SQLDESARROLLODSN);