SELECT TO_NUMBER (ACARGU) FROM CTRALTAB WHERE ACTIAR = 4852 AND TRIM (ACARGU) <> '**';
SELECT TO_NUMBER (ACARGU) FROM CTRALTAB WHERE ACTIAR = 4853 AND TRIM (ACARGU) <> '**';
SELECT TO_NUMBER (ACARGU) FROM CTRALTAB WHERE ACTIAR = 4854 AND TRIM (ACARGU) <> '**';
SELECT TO_NUMBER (ACARGU) FROM CTRALTAB WHERE ACTIAR = 4855 AND TRIM (ACARGU) <> '**';
--
SELECT * FROM AF_CTRL_CAUSAS A
WHERE NOT EXISTS(
	SELECT 1 FROM CART_RAMOS_POLIZAS B
	WHERE A.AF_SICS_CARP_CD_RAMO = B.CARP_CD_RAMO
);
--
SELECT * FROM AF_CTRL_CAUSAS A
WHERE NOT EXISTS(
	SELECT 1 FROM SINT_CAUSA_SINIESTROS B
	WHERE A.AF_SICS_CARP_CD_RAMO = B.SICS_CARP_CD_RAMO
	AND A.AF_SICS_CD_CAUSA_SINIESTRO = B.SICS_CD_CAUSA_SINIESTRO
);
--
SELECT * FROM AF_CTRL_SUCURSALES A
WHERE NOT EXISTS(
	SELECT 1 FROM CART_RAMOS_POLIZAS B
	WHERE A.CD_RAMO = B.CARP_CD_RAMO
);
--
SELECT * FROM AF_CTRL_SUCURSALES A
WHERE NOT EXISTS(
	SELECT 1 FROM CART_RAMOS_POLIZAS B
	WHERE A.CD_RAMO_C = B.CARP_CD_RAMO
);
--
SELECT * FROM AF_CTRL_SUCURSALES A
WHERE NOT EXISTS(
	SELECT 1 FROM CART_SUCURSALES B
	WHERE A.CASU_CD_SUCURSAL = B.CASU_CD_SUCURSAL
);
--
SELECT * FROM AF_POLIZAS A
WHERE NOT EXISTS(
	SELECT 1 FROM AF_CLIENTES B
	WHERE A.CD_NACIONALIDAD = B.CD_NACIONALIDAD
	AND A.NU_CEDULA_RIF = B.NU_CEDULA_RIF
);
--
SELECT * FROM CART_USUARIOS_PROVEEDORES A
WHERE NOT EXISTS(
	SELECT 1 FROM CART_PROVEEDORES_SERVICIOS B
	WHERE A.CAUZ_CATP_TP_PROVEEDOR = B.CAPS_CATP_TP_PROVEEDOR
	AND A.CAUZ_CAPS_CD_PROVEEDOR = B.CAPS_CD_PROVEEDOR
);
--
SELECT * FROM TF_SYS_PROVEEDORES A
WHERE NOT EXISTS(
	SELECT 1 FROM CART_PROVEEDORES_SERVICIOS B
	WHERE A.TSPS_TP_PROVEEDOR = B.CAPS_CATP_TP_PROVEEDOR
	AND A.TSPS_CD_PROVEEDOR = B.CAPS_CD_PROVEEDOR
);
--
SELECT * FROM TF_SYS_PROVEEDORES_MVTOS A
WHERE NOT EXISTS(
	SELECT 1 FROM CART_PROVEEDORES_SERVICIOS B
	WHERE A.TSPM_TP_PROVEEDOR = B.CAPS_CATP_TP_PROVEEDOR
	AND A.TSPM_CD_PROVEEDOR = B.CAPS_CD_PROVEEDOR
);
--
SELECT * FROM TF_SYS_PROVEEDORES_SERVICIOS A
WHERE NOT EXISTS(
	SELECT 1 FROM CART_PROVEEDORES_SERVICIOS B
	WHERE A.TSPS_TP_PROVEEDOR = B.CAPS_CATP_TP_PROVEEDOR
	AND A.TSPS_CD_PROVEEDOR = B.CAPS_CD_PROVEEDOR
);