SELECT DISTINCT RECIBO, SUCRECIBO, CD_SUCURSAL, CD_RAMO, NU_POLIZA, NU_CERTIFICADO
FROM AF_RECIBOS C
WHERE NOT EXISTS(
	SELECT 1 FROM AF_RIESGOS_CUBIERTOS E
	WHERE E.COD_PRODUCTO = 'AUTC'
	AND C.CD_SUCURSAL = E.CD_SUCURSAL
	AND C.CD_RAMO = E.CD_RAMO
	AND C.NU_POLIZA = E.NU_POLIZA
	AND C.RECIBO = E.RECIBO
)
AND EXISTS(
	SELECT 1 FROM POLIZA P, RECIBO R
	WHERE P.IDEPOL = R.IDEPOL
	AND STSREC <> 'MIG'
	AND P.CODPOL = 'AUTC'
	AND R.CODOFIEMI = C.CD_SUCURSAL
	AND R.CODRAMOCERT = CD_RAMO
	AND P.NUMPOL = C.NU_POLIZA
	AND R.NUMREC = C.RECIBO
);
--
SELECT B.* FROM (
	SELECT DISTINCT IDEPOL, IDEOP, NUMREC FROM RECIBO
) A, POLIZAS_A_TRANSF_TOTALFAST B
WHERE A.NUMREC IN(
	SELECT DISTINCT RECIBO FROM AF_RECIBOS C
	WHERE EXISTS(
		SELECT 1 FROM AF_POLIZAS D
		WHERE C.CD_SUCURSAL = D.CD_SUCURSAL
		AND C.CD_RAMO = D.CD_RAMO
		AND C.NU_POLIZA = D.NU_POLIZA
		AND C.NU_CERTIFICADO = D.NU_CERTIFICADO
		AND D.COD_PRODUCTO = 'AUTI'
	)
	AND NOT EXISTS(
		SELECT 1 FROM AF_RIESGOS_CUBIERTOS E
		WHERE C.CD_SUCURSAL = E.CD_SUCURSAL
		AND C.CD_RAMO = E.CD_RAMO
		AND C.NU_POLIZA = E.NU_POLIZA
		AND C.NU_CERTIFICADO = E.NU_CERTIFICADO
		AND C.RECIBO = E.RECIBO
	)
)
AND A.IDEPOL = B.IDEPOL
AND A.IDEOP = B.IDEOP
AND B.INDPOLTRANSF = 'S'
ORDER BY 3;
---
SELECT DISTINCT B.NUMCERT, A.IDEPOL,A.IDEOP,A.INDPOLTRANSF, B.TIPOOPE,B.STSREC,B.NUMREC,B.CODOFIEMI
FROM POLIZAS_A_TRANSF_TOTALFAST A, RECIBO B
WHERE A.IDEPOL = B.IDEPOL 
AND A.IDEOP = B.IDEOP 
AND A.INDPOLTRANSF = 'S'
AND B.NUMREC IN(
	SELECT DISTINCT RECIBO FROM AF_RECIBOS C
	WHERE EXISTS(
		SELECT 1 FROM AF_POLIZAS D
		WHERE C.CD_SUCURSAL = D.CD_SUCURSAL
		AND C.CD_RAMO = D.CD_RAMO
		AND C.NU_POLIZA = D.NU_POLIZA
		AND C.NU_CERTIFICADO = D.NU_CERTIFICADO
	)
	AND NOT EXISTS(
		SELECT 1 FROM AF_RIESGOS_CUBIERTOS E
		WHERE C.CD_SUCURSAL = E.CD_SUCURSAL
		AND C.CD_RAMO = E.CD_RAMO
		AND C.NU_POLIZA = E.NU_POLIZA
		AND C.NU_CERTIFICADO = E.NU_CERTIFICADO
		AND C.RECIBO = E.RECIBO
	)
);
--
SELECT * FROM POLIZAS_A_TRANSF_TOTALFAST WHERE INDPOLTRANSF = 'N';