SELECT RAZONAPTO DESCRIPCION, COUNT (*) CANTIDAD, 'SINIESTROS_MIGRA_REN' TABLA
FROM SINIESTROS_MIGRA_REN
WHERE APTO <> 'S'
GROUP BY RAZONAPTO;
--
SELECT RAZONMIGRA DESCRIPCION, COUNT (*) CANTIDAD, 'EQ_SINIESTRO_REN' TABLA
FROM EQ_SINIESTRO_REN
WHERE MIGRA <> 'S'
GROUP BY RAZONMIGRA;
--
SELECT RAZONMIGRA DESCRIPCION, COUNT (*) CANTIDAD, 'EQ_REASEGURO_REN' TABLA
FROM EQ_REASEGURO_REN
WHERE MIGRA <> 'S'
GROUP BY RAZONMIGRA;
--
SELECT RAZONMIGRA DESCRIPCION, COUNT (*) CANTIDAD, 'SINIESTROS_MIGRA_REN' TABLA
FROM EQ_POLIZA_NO_MIGRADO
WHERE MIGRA <> 'S'
GROUP BY RAZONMIGRA
UNION ALL
SELECT RAZONMIGRA DESCRIPCION, COUNT (*) CANTIDAD, 'EQ_SINIESTRO_REN' TABLA
FROM EQ_REASEGURO_NM
WHERE MIGRA <> 'S'
GROUP BY RAZONMIGRA;
--
DECLARE
	CURSOR cur
	IS
	SELECT * FROM INV_TEMP_ING;
BEGIN
	FOR i IN cur
	LOOP
		PR_INV_REL_ING.ANULAR (i.INGRESO, i.IDEFACT);
	END LOOP;
END;