SELECT CODPROD,NUMPOL,A.NUMREC,STSREC,CODOFIEMI,DESCRIP,RAMO,
       POLIZA,B.NUMREC,STSSIT,ZONCOB
FROM TAB_ASCEL A,(
	SELECT * FROM TAB_AS WHERE STSSIT = 1
) B
WHERE PM.BUSCAR_PRODUCTO (RAMO, POLIZA) = CODPROD
AND TO_NUMBER (SUBSTR (A.NUMPOL, 2, 10)) = B.POLIZA
AND A.NUMREC = B.NUMREC
AND A.CODOFIEMI = PM.CONVIERTE_ZONCOB_CODOFI (B.ZONCOB)
AND A.CODPROD = 'FIAN'
AND A.STSREC <> 'COB';
--
SELECT 	CODPROD, NUMPOL, A.NUMREC, STSREC,CODOFIEMI, 
		DESCRIP, RAMO, POLIZA,B.NUMREC, STSSIT, ZONCOB
FROM TAB_ASCEL A,(
	SELECT * FROM TAB_AS
	WHERE STSSIT = 1
) B
WHERE PM.BUSCAR_PRODUCTO (RAMO, POLIZA) = CODPROD
AND A.NUMPOL = B.POLIZA
AND A.NUMREC = B.NUMREC
AND A.CODOFIEMI = PM.CONVIERTE_ZONCOB_CODOFI (B.ZONCOB)
AND A.CODPROD <> 'FIAN'
AND A.STSREC = 'ACT';