SELECT DISTINCT 
    C.CODPOL, C.NUMPOL, B.NUMCERT, A.IDEPOL,A.IDEOP, 
    A.INDPOLTRANSF,B.TIPOOPE,B.STSREC,C.STSPOL,B.NUMREC
FROM POLIZAS_A_TRANSF_TOTALFAST A, RECIBO B, POLIZA C
WHERE A.IDEPOL = B.IDEPOL
AND A.IDEOP = B.IDEOP
AND A.IDEPOL = C.IDEPOL
AND A.INDPOLTRANSF NOT IN ('W', 'R', 'T', 'Z')
AND B.TIPOOPE IN ('REN', 'EMI', 'ADI')
AND C.STSPOL = 'REN'
AND B.STSREC != 'MIG'
AND C.NUMPOL = 1000402
AND EXISTS (
    SELECT 1 FROM AF_RECIBOS D
    WHERE D.CD_SUCURSAL = B.CODOFIEMI
    AND D.cd_ramo = B.codramocert
    AND D.nu_poliza = C.numpol
    AND D.nu_certificado = B.numcert
    AND D.recibo = B.numrec
)
AND NOT EXISTS (
    SELECT 1 FROM AF_RIESGOS_CUBIERTOS D
    WHERE D.CD_SUCURSAL = B.CODOFIEMI
    AND D.cd_ramo = B.codramocert
    AND D.nu_poliza = C.numpol
    AND D.nu_certificado = B.numcert
    AND D.recibo = B.numrec
)
AND C.CODPOL = 'AUTI';
--
DELETE FROM af_recibos
WHERE RECIBO IN (
    13916047, 13769230, 13973040,
    13619151, 14856328, 14080221
);
--
UPDATE POLIZAS_A_TRANSF_TOTALFAST SET INDPOLTRANSF = 'N' WHERE IDEPOL = 194523 AND IDEOP = 8057063;
UPDATE POLIZAS_A_TRANSF_TOTALFAST SET INDPOLTRANSF = 'N' WHERE IDEPOL = 194015 AND IDEOP = 8056407;
UPDATE POLIZAS_A_TRANSF_TOTALFAST SET INDPOLTRANSF = 'N' WHERE IDEPOL = 199468 AND IDEOP = 8058255;
UPDATE POLIZAS_A_TRANSF_TOTALFAST SET INDPOLTRANSF = 'N' WHERE IDEPOL = 196546 AND IDEOP = 8053792;
UPDATE POLIZAS_A_TRANSF_TOTALFAST SET INDPOLTRANSF = 'N' WHERE IDEPOL = 195381 AND IDEOP = 8058946;
UPDATE POLIZAS_A_TRANSF_TOTALFAST SET INDPOLTRANSF = 'N' WHERE IDEPOL = 195381 AND IDEOP = 8058948;
--
SELECT * FROM POLIZA WHERE numpol = 1247031;
SELECT * FROM RECIBO WHERE IDEPOL = 128424 AND ideop = 4340865;
SELECT * FROM POLIZAS_A_TRANSF_TOTALFAST WHERE IDEPOL = 128424 AND ideop = 4340865;
SELECT * FROM af_polizas WHERE nu_poliza = 1247031;
SELECT * FROM af_recibos WHERE nu_poliza = 1247031 AND RECIBO = 1548;
SELECT * FROM AF_RIESGOS_CUBIERTOS WHERE nu_poliza = 1247031 AND RECIBO = 1548;