DECLARE
	CURSOR BIENES
	IS
	SELECT Ramo,CodRamo,CodCobert,TipoCobert
	FROM BIENES_MIG@PROD;

	cTipoCobert 	VARCHAR2 (1);
BEGIN
	FOR C IN BIENES
	LOOP
		cTipoCobert := NULL;

		BEGIN
			SELECT TipoCobert INTO cTipoCobert
			FROM ACSEL.COBERT_RAMO@CERT
			WHERE CodRamo = C.CodRamo 
			AND CodCobert = C.CodCobert;
		EXCEPTION WHEN OTHERS THEN
			cTipoCobert := NULL;
		END;

		IF cTipocobert != C.TipoCobert THEN
			UPDATE BIENES_MIG@PROD
			SET TipoCobert = cTipoCobert
			WHERE CodRamo = C.CodRamo 
			AND CodCobert = C.CodCobert;
		END IF;
	END LOOP;
	COMMIT;
EXCEPTION WHEN OTHERS THEN
	PM.GENERA_ERROR_CARTERA (
		cTipoError		=> 'ERR-GENERAL',
		cCodError		=> '003',
		cNomProceso		=> 'MIG_TABLAS_BASICAS.MIGRAR_COBERTURAS_INDIVIDUALES',
		cNomTabla		=> 'ACSEL.BIENES_MIG@PROD',
		cOraError		=> SQLERRM,
		cObservaciones	=> 'Error al actualizar TipoCobert en bienes_mig',
		lActualizar		=> FALSE
	);
	COMMIT;
END;
--
SELECT DISTINCT RAMO, CODCOB, DESCOB, COMPAN, TO_CHAR (MIGRAR) MIGRAR,
	NVL (CODRAMO, '0000') CODRAMO,
	NVL (DESCRAMO, 'SIN DESCRIPCION') DESCRAMO,
	NVL (CODCOBERT, '0000') CODCOBERT,
	NVL (DESCCOBERT, 'SIN DESCRIPCION') DESCCOBERT
FROM ACSEL.RAMOS_MIG@CERT;
--
SELECT DISTINCT RAMO, TO_NUMBER(BIEN) BIEN, DESBIEN, CODCOB, DESCOB,
	NVL (CODRAMO, '0000') CODRAMO,
	NVL (CODCOBERT, '0000') CODCOBERT,
	NVL (CODBIEN, '000') CODBIEN,
	NVL (USO, '0') USO,
	NVL (INDTASA, '0') INDTASA,
	NVL (TIPOCOBERT, '0') TIPOCOBERT
FROM ACSEL.BIENES_MIG@CERT;
--
SELECT 	CODPRD,
		TO_CHAR (MAX (SUC)) SUC,
		NVL (MAX (NACION), 'V') NACION,
		MAX (CEDPRO) CEDPROD,
		NVL (MAX (CODPRDN), '000000') CODPRDN,
		RPAD (TO_CHAR (MAX (SUC)), 6, '0') OFICINA,
		NVL (MAX (IND), '0') IND
FROM ACSEL.TEM_HJPF10@CERT
GROUP BY CODPRD;