DECLARE
	CURSOR CUR_RECIBOS
	IS
	SELECT DISTINCT C.CODPOL, C.NUMPOL, B.NUMCERT, A.IDEPOL, A.IDEOP, A.INDPOLTRANSF, 
					B.TIPOOPE, B.STSREC, C.STSPOL, B.NUMREC, B.CODOFIEMI
	FROM POLIZAS_A_TRANSF_TOTALFAST A, RECIBO B, POLIZA C
	WHERE A.IDEPOL = B.IDEPOL
	AND A.IDEOP = B.IDEOP
	AND A.IDEPOL = C.IDEPOL
	AND A.INDPOLTRANSF NOT IN ('W', 'R', 'T', 'Z')
	AND B.TIPOOPE IN ('REN', 'EMI', 'ADI')
	AND C.STSPOL = 'REN'
	AND B.STSREC != 'MIG'
	AND EXISTS (
		SELECT 1 FROM AF_RECIBOS D 
		WHERE D.CD_SUCURSAL = B.CODOFIEMI
		AND D.cd_ramo = B.codramocert
		AND D.nu_poliza = C.numpol
		AND D.nu_certificado = B.numcert
		AND D.recibo = B.numrec
	)
	AND NOT EXISTS (
		SELECT 1
		FROM AF_RIESGOS_CUBIERTOS D
		WHERE D.CD_SUCURSAL = B.CODOFIEMI
		AND D.cd_ramo = B.codramocert
		AND D.nu_poliza = C.numpol
		AND D.nu_certificado = B.numcert
		AND D.recibo = B.numrec
	)
	AND C.CODPOL = 'AUTI';
BEGIN
	FOR I IN CUR_RECIBOS
	LOOP
		UPDATE POLIZAS_A_TRANSF_TOTALFAST
		SET INDPOLTRANSF = 'N'
		WHERE IDEPOL = I.IDEPOL AND IDEOP = I.IDEOP;

		DELETE FROM af_recibos 
		WHERE CD_SUCURSAL = I.CODOFIEMI
		AND NU_POLIZA = I.NUMPOL
		AND NU_CERTIFICADO = I.NUMCERT
		AND RECIBO = I.NUMREC;

		COMMIT;
   END LOOP;
END;