SELECT DISTINCT descerror, referencia 
FROM ERROR_TRANSFERENCIA_TOTALFAST 
WHERE coderror = 'NOFOUND-0013'
--
SELECT DISTINCT 
	E.cd_siniestro,
	E.nu_siniestro,
	TO_DATE (SS.SISI_FE_OCURRENCIA) FECHA_OCU,
	E.cod_producto,
	SCS.SICE_CACE_CASU_CD_SUCURSAL CD_POLIZA,
	E.nu_poliza,
	SCS.SICE_CACE_NU_CERTIFICADO NU_CERTIFICADO,
	P.FECINIVIG,
	P.FECFINVIG,
	P.codofisusc,
	P.STSPOL
FROM SINT_SINIESTROS SS, SINT_CERTIFICADOS_SINIESTROS SCS,(
	SELECT DISTINCT referencia,
			SUBSTR (referencia, 15, 6) cd_siniestro,
			SUBSTR (referencia, 22, 8) nu_siniestro,
			SUBSTR (referencia, 42, 5) nu_poliza,
			SUBSTR (referencia, 61, 4) cod_producto
	FROM ERROR_TRANSFERENCIA_TOTALFAST
	WHERE coderror = 'NOFOUND-0044' AND LENGTH (referencia) = 64
) E,
POLIZA P
WHERE SS.SISI_CASU_CD_SUCURSAL = SCS.SICE_SISI_CASU_CD_SUCURSAL
AND SS.SISI_NU_SINIESTRO = SCS.SICE_SISI_NU_SINIESTRO
AND SS.SISI_CASU_CD_SUCURSAL = E.CD_SINIESTRO
AND SS.SISI_NU_SINIESTRO = E.NU_SINIESTRO
AND SCS.SICE_CACE_CASU_CD_SUCURSAL = P.CODOFISUSC
AND E.nu_poliza = P.NUMPOL
AND E.cod_producto = P.CODPOL
AND TO_DATE (SS.SISI_FE_OCURRENCIA) >= FECINIVIG
AND TO_DATE (SS.SISI_FE_OCURRENCIA) <= FECFINVIG
ORDER BY 1,2,3,8,9;
--
SELECT DISTINCT 
	E.cd_siniestro,
	E.nu_siniestro,
	TO_DATE (SS.SISI_FE_OCURRENCIA) FECHA_OCU,
	E.cod_producto,
	SCS.SICE_CACE_CASU_CD_SUCURSAL CD_POLIZA,
	E.nu_poliza,
	SCS.SICE_CACE_NU_CERTIFICADO NU_CERTIFICADO,
	P.FECINIVIG,
	P.FECFINVIG,
	P.codofisusc,
	P.STSPOL
FROM SINT_SINIESTROS SS, SINT_CERTIFICADOS_SINIESTROS SCS,(
	SELECT DISTINCT
		referencia,
		SUBSTR (referencia, 15, 6) cd_siniestro,
		SUBSTR (referencia, 22, 8) nu_siniestro,
		SUBSTR (referencia, 42, 6) nu_poliza,
		SUBSTR (referencia, 62, 4) cod_producto
	FROM ERROR_TRANSFERENCIA_TOTALFAST
	WHERE coderror = 'NOFOUND-0044' 
	AND LENGTH (referencia) = 65
) E, POLIZA P
WHERE SS.SISI_CASU_CD_SUCURSAL = SCS.SICE_SISI_CASU_CD_SUCURSAL
AND SS.SISI_NU_SINIESTRO = SCS.SICE_SISI_NU_SINIESTRO
AND SS.SISI_CASU_CD_SUCURSAL = E.CD_SINIESTRO
AND SS.SISI_NU_SINIESTRO = E.NU_SINIESTRO
AND SCS.SICE_CACE_CASU_CD_SUCURSAL = P.CODOFISUSC
AND E.nu_poliza = P.NUMPOL
AND E.cod_producto = P.CODPOL
AND TO_DATE (SS.SISI_FE_OCURRENCIA) >= FECINIVIG
AND TO_DATE (SS.SISI_FE_OCURRENCIA) <= FECFINVIG
ORDER BY 1,2,3,8,9;