SELECT COUNT(*) FROM HJPF01;
SELECT COUNT(*) FROM EQ_HJPF01;
SELECT * FROM EQ_HJPF01 WHERE NVL(TipoId, 'X') NOT IN ('V', 'E', 'J', 'G');
SELECT * FROM EQ_HJPF01;
--
SELECT Ccli1,Ccli2, TipoId, NumId, DvId FROM EQ_HJPF01
WHERE UPPER(Ccli1) <> TipoId
AND UPPER(Ccli1)   IN ('V', 'E', 'J', 'G', 'P');
--
SELECT COUNT(*) FROM HJPF71;
SELECT COUNT(*) FROM EQ_HJPF71;
SELECT Ramo, Poliza, NumRec, CedBen, TipoId, NumId, DvID
FROM EQ_HJPF71
WHERE NVL(TipoId, 'X') NOT IN ('V', 'E', 'J', 'G', 'M');
--
SELECT * FROM EQ_HJPF71;
--
WITH
TITULAR AS (
	SELECT DISTINCT Poliza, cedBen FROM EQ_HJPF71
	WHERE Ramo = 26 AND CoFaam IN (0, 99)
),
FAMILIAR AS (
	SELECT * FROM EQ_HJPF71
	WHERE Ramo= 26
	AND CoFaam NOT IN (0, 99)
	AND CedBen LIKE '9%'
)
SELECT FAMILIAR. * FROM TITULAR, FAMILIAR
WHERE FAMILIAR.CedBen LIKE '%' || TITULAR.CedBen
AND TITULAR.CedBen <> FAMILIAR.CedBen
AND TITULAR.Poliza = FAMILIAR.Poliza
AND FAMILIAR.CodPar IN (7, 8, 11, 12, 13, 14, 21, 22, 43, 44)
ORDER BY FAMILIAR.CedBen;
--
WITH
TITULAR AS (
	SELECT DISTINCT Poliza, cedBen FROM EQ_HJPF71
	WHERE Ramo = 26 AND CoFaam IN (0, 99)
),
FAMILIAR AS (
	SELECT * FROM EQ_HJPF71
	WHERE Ramo= 26 AND CoFaam NOT IN (0, 99) AND CedBen LIKE '9%'
)
SELECT FAMILIAR. * FROM TITULAR, FAMILIAR
WHERE FAMILIAR.CedBen LIKE '%' || TITULAR.CedBen
AND TITULAR.CedBen <> FAMILIAR.CedBen
AND TITULAR.Poliza = FAMILIAR.Poliza
AND FAMILIAR.CodPar IN (7, 8, 11, 12, 13, 14, 21, 22, 43, 44)
AND TipoId <> 'M'
ORDER BY FAMILIAR.CedBen;
--
SELECT Ramo, Poliza, NumRec, CedBen, TipoId, NumId, DvId FROM EQ_HJPF71 EQ
WHERE TipoId = 'M'
AND NOT EXISTS (
	SELECT * FROM (
		WITH
		TITULAR AS (
			SELECT DISTINCT Poliza, cedBen FROM EQ_HJPF71
			WHERE Ramo = 26 AND CoFaam IN (0, 99)
		),
		FAMILIAR AS (
			SELECT * FROM EQ_HJPF71
			WHERE Ramo= 26
			AND CoFaam NOT IN (0, 99)
			AND CedBen LIKE '9%'
		)
		SELECT FAMILIAR. * FROM TITULAR, FAMILIAR
		WHERE FAMILIAR.CedBen LIKE '%' || TITULAR.CedBen
		AND TITULAR.CedBen <> FAMILIAR.CedBen
		AND TITULAR.Poliza = FAMILIAR.Poliza
		AND FAMILIAR.CodPar IN (7, 8, 11, 12, 13, 14, 21, 22, 43, 44)
		ORDER BY FAMILIAR.CedBen
	)
	WHERE Ramo = EQ.Ramo
	AND Poliza = EQ.Poliza
	AND NumRec = EQ.NumRec
	AND CedBen = EQ.CedBen
);
--
WITH
TITULAR AS (
	SELECT DISTINCT Poliza, cedBen
	FROM EQ_HJPF71
	WHERE Ramo = 26 AND CoFaam IN (0, 99)
),
FAMILIAR AS (
	SELECT * FROM EQ_HJPF71
	WHERE Ramo= 26 AND CoFaam NOT IN (0, 99) AND CedBen LIKE '9%'
)
SELECT FAMILIAR. *, TITULAR.CedBen
FROM TITULAR, FAMILIAR
WHERE FAMILIAR.CedBen LIKE '%' || TITULAR.CedBen
AND TITULAR.CedBen <> FAMILIAR.CedBen
AND TITULAR.Poliza = FAMILIAR.Poliza
AND FAMILIAR.CodPar IN (7, 8, 11, 12, 13, 14, 21, 22, 43, 44)
AND TITULAR.CedBen <> NumId
AND TipoId = 'M'
ORDER BY FAMILIAR.CedBen;
--
SELECT COUNT(*) FROM HJPF205;
SELECT COUNT(*) FROM EQ_HJPF205;
--
SELECT * FROM EQ_HJPF205
WHERE NVL(TipoId, 'X') NOT IN ('V', 'E', 'J', 'G') ;
--
SELECT UPPER(Ccli1) Ccli1,Ccli2, TipoId, NumId, DvId
FROM EQ_HJPF205
WHERE UPPER(Ccli1) <> TipoId
AND UPPER(Ccli1) IN ('V', 'E', 'J', 'G', 'P');
--
SELECT * FROM EQ_HJPF205;
--
SELECT COUNT(*) FROM FNPF01;
SELECT COUNT(*) FROM EQ_FNPF01;
--
SELECT * FROM EQ_FNPF01
WHERE NVL(TipoId, 'X') NOT IN ('V', 'E', 'J', 'G', 'P') ;
--
SELECT Ccli1,Ccli2, TipoId, NumId, DvId FROM EQ_FNPF01
WHERE UPPER(Ccli1) <> TipoId
AND UPPER(Ccli1)   IN ('V', 'E', 'J', 'G', 'P');
--
SELECT * FROM EQ_FNPF01 ;
SELECT COUNT(*) FROM ORDENE;
SELECT COUNT(*) FROM EQ_ORDENE;
--
SELECT * FROM EQ_ORDENE
WHERE NVL(TipoId, 'X') NOT IN ('V', 'E', 'J', 'G', 'P');
--
SELECT UPPER(TipIde),Rif, TipoId, NumId, DvId FROM EQ_ORDENE
WHERE UPPER(TipIde) <> TipoId
AND UPPER(TipIde) IN ('V', 'E', 'J', 'G', 'P');
--
SELECT * FROM EQ_ORDENE;
--
SELECT COUNT(*) FROM ORPF06;
SELECT COUNT(*) FROM EQ_ORPF06;
SELECT * FROM EQ_ORPF06
WHERE NVL(TipoId, 'X') NOT IN ('V', 'E', 'J', 'G', 'P');
--
SELECT UPPER(TipIde),Rif, TipoId, NumId, DvId FROM EQ_ORPF06
WHERE UPPER(TipIde) <> TipoId
AND UPPER(TipIde)   IN ('V', 'E', 'J', 'G', 'P');
--
SELECT * FROM EQ_ORPF06;
SELECT COUNT(*) FROM CLPF05;
SELECT COUNT(*) FROM EQ_CLPF05_FAM;
SELECT * FROM EQ_CLPF05_FAM
WHERE NVL(TipoId, 'X') NOT IN ('V', 'E', 'J', 'G', 'P', 'N');
--
SELECT UPPER(Nacion) Nacion, CedCol, TipoId, NumId, DvId
FROM EQ_CLPF05_FAM
WHERE UPPER(Nacion) <> TipoId 
AND UPPER(Nacion) IN ('V', 'E', 'J', 'G', 'P');
--
SELECT * FROM EQ_CLPF05_FAM;
SELECT * FROM EQ_CLPF05_FAM CLI
WHERE Ramo = 27
AND TipoId = 'N'
AND NOT EXISTS (
	SELECT 'X' FROM HJPF01
	WHERE Ramo = CLI.Ramo
	AND Poliza = CLI.Poliza
	AND Cdtcbr = '71'
); 
--
SELECT COUNT(*) FROM CLPF07;
SELECT COUNT(*) FROM EQ_CLPF07;
--
SELECT * FROM EQ_CLPF07
WHERE NVL(TipoId, 'X') NOT IN ('V', 'E', 'J', 'G', 'P');
--
SELECT * FROM EQ_CLPF07;
SELECT COUNT(*) FROM HJPF06;
SELECT COUNT(*) FROM EQ_HJPF06;
--
SELECT * FROM EQ_HJPF06
WHERE NVL(TipoId, 'X') NOT IN ('V', 'E', 'J', 'G', 'P', 'N');
--
SELECT * FROM EQ_HJPF06;
--
SELECT DISTINCT TipoId, NumId, DvId, CodCli FROM (
	SELECT TipoId, NumId, DvId, CodCli FROM EQ_HJPF01
	UNION
	SELECT TipoId, NumId, DvId, CodCli FROM EQ_HJPF71
	UNION
	SELECT TipoId, NumId, DvId, CodCli FROM EQ_HJPF205
	UNION
	SELECT TipoId, NumId, DvId, CodCli FROM EQ_FNPF01
	UNION
	SELECT TipoId, NumId, DvId, CodCli FROM EQ_ORDENE
	UNION
	SELECT TipoId, NumId, DvId, CodCli FROM EQ_ORPF06
	UNION
	SELECT TipoId, NumId, DvId, CodCli FROM EQ_CLPF05_FAM
	UNION
	SELECT TipoId, NumId, DvId, CodCli FROM EQ_CLPF07
	UNION
	SELECT TipoId, NumId,DvId, CodCli FROM EQ_HJPF06
) MIG
WHERE NOT EXISTS (
	SELECT 'X' FROM ACSEL.TERCERO@CERT
	WHERE TipoId = MIG.TipoId
	AND NumId = MIG.NumId
	AND DvId = MIG.DvId
);
--
SELECT DISTINCT TipoId, NumId, DvId, CodCli FROM (
	SELECT TipoId, NumId, DvId, CodCli FROM EQ_HJPF01
	UNION
	SELECT TipoId, NumId, DvId, CodCli FROM EQ_HJPF71
	UNION
	SELECT TipoId, NumId, DvId, CodCli FROM EQ_HJPF205
	UNION
	SELECT TipoId, NumId, DvId, CodCli FROM EQ_FNPF01
	UNION
	SELECT TipoId, NumId, DvId, CodCli FROM EQ_ORDENE
	UNION
	SELECT TipoId, NumId, DvId, CodCli FROM EQ_ORPF06
	UNION
	SELECT TipoId, NumId, DvId,CodCli FROM EQ_CLPF05_FAM
	UNION
	SELECT TipoId, NumId, DvId, CodCli FROM EQ_CLPF07
	UNION
	SELECT TipoId, NumId, DvId, CodCli FROM EQ_HJPF06
) MIG
WHERE NOT EXISTS (
	SELECT 'X' FROM ACSEL.TERCERO@CERT
	WHERE TipoId = MIG.TipoId
	AND NumId = MIG.NumId
	AND DvId = MIG.DvId
)
AND EXISTS (
	SELECT 'X' FROM ACSMIGRA.TERCERO_MIG@DESA
	WHERE TipoId = MIG.TipoId
	AND NumId = MIG.NumId
	AND DvId = MIG.DvId
);
--
SELECT * FROM ACSMIGRA.TERCERO_MIG@DESA TER
WHERE Migra <> 'N'
AND NOT EXISTS (
	SELECT 'X' FROM ACSMIGRA.TERCERO_ROL_MIG@DESA
	WHERE TipoId = TER.TipoId
	AND NumId = TER.NumId
	AND DvId = TER.DvId
	AND TipoTer = 'CI'
)
--
SELECT * FROM ACSMIGRA.TERCERO_MIG@DESA TER
WHERE Migra <> 'N'
AND NOT EXISTS (
	SELECT 'X' FROM ACSMIGRA.CLIENTE_MIG@DESA
	WHERE TipoId = TER.TipoId
	AND NumId = TER.NumId
	AND DvId = TER.DvId
)
--
SELECT * FROM ACSMIGRA.CLIENTE_MIG@DESA CLI
WHERE CodCli NOT LIKE '%'||NumId||'%' 
AND TipoId NOT IN ('M', 'N') 
AND EXISTS (
	SELECT 'X' FROM ACSMIGRA.TERCERO_MIG@DESA
	WHERE TipoId = CLI.TipoId
	AND NumId = CLI.NumId
	AND DvId = CLI.DvId
	AND NVL(Migra, 'S') = 'S'
)