-- TAMAÑO OCUPADO POR UNA TABLA CONCRETA
SELECT
	SEGMENT_NAME,
	SEGMENT_TYPE,
	(BYTES/1024/1024) TAMAÑO_MB 
FROM DBA_SEGMENTS
WHERE OWNER='OPENCARD'
AND SEGMENT_TYPE='TABLE'
AND SEGMENT_NAME='KE_HISTORIC_FLOW';
