--TODOS LOS FICHEROS DE DATOS Y SU UBICACIÓN
SELECT * FROM V$DATAFILE;

--FICHEROS TEMPORALES
SELECT * FROM V$TEMPFILE;

--FICHEROS DE REDO LOG
SELECT member FROM v$logfile;

--FICHEROS DE ARCHIVE LOG
SHOW parameters archive_dest