-- INFORMACIÓN DE COLUMNAS DE UNA TABLA
SELECT
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    DATA_LENGTH,
    DATA_PRECISION,
    NULLABLE
FROM ALL_TAB_COLUMNS
WHERE OWNER = 'SIEBEL'
AND TABLE_NAME = 'MI_TABLA'
ORDER BY TABLE_NAME, COLUMN_ID;