-- OBJETOS MODIFICADOS EN LA ÚLTIMA HORA
SELECT
    OBJECT_NAME,
    OBJECT_TYPE,
    LAST_DDL_TIME,
    CREATED,
    TIMESTAMP,
    STATUS
FROM all_objects
WHERE OWNER = 'SIEBEL'
AND TIMESTAMP > sysdate - 1;