DECLARE @PhysicalRID VARCHAR(15)
DECLARE @var INT SET @var = 0
--
DECLARE cur_Auditorias CURSOR FOR
SELECT TOP 100000 %%physloc%%
FROM [fisdb].[dbo].[Auditorias_Taquilla] WITH (NOLOCK)
WHERE DATEDIFF(MONTH, [Fecha_Hora], GETDATE()) > 12
--
OPEN cur_Auditorias
FETCH NEXT FROM cur_Auditorias INTO @PhysicalRID
WHILE @@FETCH_STATUS = 0
BEGIN
	DELETE TOP (1) FROM [fisdb].[dbo].[Auditorias_Taquilla]
	WHERE %%physloc%% = @PhysicalRID
	--SET @var = @var - 1
	FETCH NEXT FROM cur_Auditorias INTO @PhysicalRID
END
CLOSE cur_Auditorias
DEALLOCATE cur_Auditorias
--
-- Cambios
SELECT
	C.[NUMBER],
	T.[ASSIGNED_TO],
	C.[CURRENT_PHASE],
	C.[REQUESTED_BY],
	C.[PLANNED_START],
	C.[PLANNED_END],
	T.[NUMBER],
	DATENAME(DW,C.[PLANNED_END]) [SUBMIT_DAYS],
	DATEDIFF(DAY,C.[PLANNED_END] - CAST('04:30' AS DATETIME), GETDATE()) [DAYS],
	CONVERT(VARCHAR(10), ((DATEDIFF(MS, C.[PLANNED_END] - CAST('04:30' AS DATETIME), GETDATE())%86400000)/3600000)) + ':'+ -- HOURS	
	CONVERT(VARCHAR(10), (((DATEDIFF(MS, C.[PLANNED_END] - CAST('04:30' AS DATETIME), GETDATE())%86400000)%3600000)/60000)) + ':'+ -- MINUTES
	CONVERT(VARCHAR(10), ((((DATEDIFF(MS, C.[PLANNED_END] - CAST('04:30' AS DATETIME), GETDATE())%86400000)%3600000)%60000)/1000)) -- SECONDS
	[TIME],
	T.[DESCRIPTION]
FROM [SMBODSA2].[dbo].[CM3TM1] T
INNER JOIN [SMBODSA2].[dbo].[CM3RM1] C ON C.NUMBER = T.PARENT_CHANGE
WHERE T.[STATUS] = 'initial' 
AND C.[CURRENT_PHASE] IN (
	'Evaluación & Cierre del Cambio',
	'Implementación del Cambio',
	'Distribución del Cambio'
)
AND T.[ASSIGN_DEPT] = ('ADM BASES DE DATOS DISTRIBUIDA')
AND T.[COMPLETION_CODE] IS NULL
ORDER BY c.[PLANNED_END];
-- Peticiones
SELECT
	[NUMBER],
	[ASSIGNED_TO],
	[REQUESTED_FOR],
	[SUBMIT_DATE],
	DATENAME(DW,[SUBMIT_DATE]) [SUBMIT_DAYS],
	DATEDIFF(DAY,[SUBMIT_DATE] - CAST('04:30' AS DATETIME), GETDATE()) [DAYS],
	CONVERT(VARCHAR(10), ((DATEDIFF(MS, [SUBMIT_DATE] - CAST('04:30' AS DATETIME), GETDATE())%86400000)/3600000)) + ':'+ -- HOURS
	CONVERT(VARCHAR(10), (((DATEDIFF(MS, [SUBMIT_DATE] - CAST('04:30' AS DATETIME), GETDATE())%86400000)%3600000)/60000)) + ':'+ -- MINUTES
	CONVERT(VARCHAR(10), ((((DATEDIFF(MS, [SUBMIT_DATE] - CAST('04:30' AS DATETIME), GETDATE())%86400000)%3600000)%60000)/1000)) -- SECONDS
	[TIME],
	[DESCRIPTION]
FROM [SMBODSA2].[dbo].[OCMQM1]
WHERE [ASSIGNED_DEPT] = 'ADM BASES DE DATOS DISTRIBUIDA'
AND [CURRENT_PHASE] <> 'CIERRE'
AND [OPEN] = 'T'
ORDER BY [SUBMIT_DATE];
-- Incidentes
SELECT
	[NUMBER],
	[OPEN_TIME],
	DATENAME(DW,[OPEN_TIME]) [SUBMIT_DAYS],
	DATEDIFF(DAY,[OPEN_TIME] - CAST('04:30' AS DATETIME), GETDATE()) [DAYS],
	CONVERT(VARCHAR(10), ((DATEDIFF(MS, [OPEN_TIME] - CAST('04:30' AS DATETIME), GETDATE())%86400000)/3600000)) + ':'+ -- HOURS
	CONVERT(VARCHAR(10), (((DATEDIFF(MS, [OPEN_TIME] - CAST('04:30' AS DATETIME), GETDATE())%86400000)%3600000)/60000)) + ':'+ -- MINUTES
	CONVERT(VARCHAR(10), ((((DATEDIFF(MS, [OPEN_TIME] - CAST('04:30' AS DATETIME), GETDATE())%86400000)%3600000)%60000)/1000)) -- SECONDS
	[TIME],
	[ACTION],
	[ASSIGNEE_NAME],
	[BRIEF_DESCRIPTION]
FROM [SMBODSA2].[dbo].[PROBSUMMARYM1]
WHERE [ASSIGNMENT] = 'ADM BASES DE DATOS DISTRIBUIDA'
AND [STATUS] <> 'CLOSED'
ORDER BY [OPEN_TIME];