SELECT * FROM sys.databases
--
SELECT
'ALTER DATABASE ['+ name +'] SET RECOVERY SIMPLE'
FROM sys.databases
WHERE recovery_model_desc <> 'SIMPLE'
ORDER BY 1
--
ALTER DATABASE [ARCOWELD_C] SET RECOVERY SIMPLE
ALTER DATABASE [ARCOWELD_N] SET RECOVERY SIMPLE
ALTER DATABASE [BioStar] SET RECOVERY SIMPLE
ALTER DATABASE [BLUESTAR] SET RECOVERY SIMPLE
ALTER DATABASE [BLUESTAR_C] SET RECOVERY SIMPLE
ALTER DATABASE [BLUESTAR_N] SET RECOVERY SIMPLE
ALTER DATABASE [DEKASA] SET RECOVERY SIMPLE
ALTER DATABASE [DEKASA_C] SET RECOVERY SIMPLE
ALTER DATABASE [DEKASA_N] SET RECOVERY SIMPLE
ALTER DATABASE [DEMOA] SET RECOVERY SIMPLE
ALTER DATABASE [DEMOC] SET RECOVERY SIMPLE
ALTER DATABASE [DEMON] SET RECOVERY SIMPLE
ALTER DATABASE [ELZYRA] SET RECOVERY SIMPLE
ALTER DATABASE [K2W] SET RECOVERY SIMPLE
ALTER DATABASE [KELARA] SET RECOVERY SIMPLE
ALTER DATABASE [KELARA_C] SET RECOVERY SIMPLE
ALTER DATABASE [KELARA_N] SET RECOVERY SIMPLE
ALTER DATABASE [MasterProfitPro] SET RECOVERY SIMPLE
ALTER DATABASE [MasterProfitPro2K12] SET RECOVERY SIMPLE
ALTER DATABASE [OVL] SET RECOVERY SIMPLE
ALTER DATABASE [PICARI] SET RECOVERY SIMPLE
ALTER DATABASE [PICARI_C] SET RECOVERY SIMPLE
ALTER DATABASE [Profit_RG] SET RECOVERY SIMPLE
ALTER DATABASE [PSUPPLY_N] SET RECOVERY SIMPLE
ALTER DATABASE [QUALITY_N] SET RECOVERY SIMPLE
ALTER DATABASE [TRACO] SET RECOVERY SIMPLE
ALTER DATABASE [TRACO_C] SET RECOVERY SIMPLE
ALTER DATABASE [TRACO_N] SET RECOVERY SIMPLE
--
sp_configure 'show advanced options', 1;  
GO  
RECONFIGURE;  
GO  
sp_configure 'Database Mail XPs', 1;  
GO  
RECONFIGURE  
GO
--
SELECT * FROM ELZYRA.dbo.Notificacion_email
--
EXEC ELZYRA.dbo.pJOB_ELZYRA_Email_Meta_Vta_GerenciaMix @pGrupo ='Stargas';
EXEC ELZYRA.dbo.pJOB_ELZYRA_Email_Meta_Vta_GerenciaMix @pGrupo ='Overland';
--
SELECT co_empresa FROM ELZYRA.dbo.Emp_asoc WHERE asociada=co_empresa and grupo='Stargas'
--
USE master
--
ALTER DATABASE [ARCOWELD_C] SET RECOVERY SIMPLE
ALTER DATABASE [ARCOWELD_N] SET RECOVERY SIMPLE
ALTER DATABASE [BioStar] SET RECOVERY SIMPLE
ALTER DATABASE [BLUESTAR] SET RECOVERY SIMPLE
ALTER DATABASE [BLUESTAR_C] SET RECOVERY SIMPLE
ALTER DATABASE [BLUESTAR_N] SET RECOVERY SIMPLE
ALTER DATABASE [DEKASA] SET RECOVERY SIMPLE
ALTER DATABASE [DEKASA_C] SET RECOVERY SIMPLE
ALTER DATABASE [DEKASA_N] SET RECOVERY SIMPLE
ALTER DATABASE [DEMOA] SET RECOVERY SIMPLE
ALTER DATABASE [DEMOC] SET RECOVERY SIMPLE
ALTER DATABASE [DEMON] SET RECOVERY SIMPLE
ALTER DATABASE [ELZYRA] SET RECOVERY SIMPLE
ALTER DATABASE [K2W] SET RECOVERY SIMPLE
ALTER DATABASE [KELARA] SET RECOVERY SIMPLE
ALTER DATABASE [KELARA_C] SET RECOVERY SIMPLE
ALTER DATABASE [KELARA_N] SET RECOVERY SIMPLE
ALTER DATABASE [MasterProfitPro] SET RECOVERY SIMPLE
ALTER DATABASE [MasterProfitPro2K12] SET RECOVERY SIMPLE
ALTER DATABASE [OVL] SET RECOVERY SIMPLE
ALTER DATABASE [PICARI] SET RECOVERY SIMPLE
ALTER DATABASE [PICARI_C] SET RECOVERY SIMPLE
ALTER DATABASE [Profit_RG] SET RECOVERY SIMPLE
ALTER DATABASE [PSUPPLY_N] SET RECOVERY SIMPLE
ALTER DATABASE [QUALITY_N] SET RECOVERY SIMPLE
ALTER DATABASE [TRACO] SET RECOVERY SIMPLE
ALTER DATABASE [TRACO_C] SET RECOVERY SIMPLE
ALTER DATABASE [TRACO_N] SET RECOVERY SIMPLE
--
--ARCOWELD
ALTER DATABASE ARCOWELD SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE ARCOWELD FROM DISK = 'C:\db_bks\ARCOWELD_backup_2017_04_12_060012_6511051.bak'
GO
ALTER DATABASE ARCOWELD SET MULTI_USER
GO
--ARCOWELD_C
ALTER DATABASE ARCOWELD_C SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE ARCOWELD_C FROM DISK = 'C:\db_bks\ARCOWELD_C_backup_2017_04_12_060012_6667284.bak'
GO
ALTER DATABASE ARCOWELD_C SET MULTI_USER
GO
--ARCOWELD_N
ALTER DATABASE ARCOWELD_N SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE ARCOWELD_N FROM DISK = 'C:\db_bks\ARCOWELD_N_backup_2017_04_12_060012_6823544.bak'
GO
ALTER DATABASE ARCOWELD_N SET MULTI_USER
GO
--ARCO
ALTER DATABASE ARCO SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE ARCO FROM DISK = 'C:\db_bks\ARCO_backup_2017_04_12_060012_6511051.bak'
GO
ALTER DATABASE ARCO SET MULTI_USER
GO
--Bioprofit
ALTER DATABASE Bioprofit SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE Bioprofit FROM DISK = 'C:\db_bks\Bioprofit_backup_2017_04_12_060012_6823544.bak'
GO
ALTER DATABASE Bioprofit SET MULTI_USER
GO
--BioStar
ALTER DATABASE BioStar SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE BioStar FROM DISK = 'C:\db_bks\BioStar_backup_2017_04_12_060012_6979870.bak'
GO
ALTER DATABASE BioStar SET MULTI_USER
GO
--BLUESTAR
ALTER DATABASE BLUESTAR SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE BLUESTAR FROM DISK = 'C:\db_bks\BLUESTAR_backup_2017_04_12_060012_6979870.bak'
GO
ALTER DATABASE BLUESTAR SET MULTI_USER
GO
--BLUESTAR_C
ALTER DATABASE BLUESTAR_C SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE BLUESTAR_C FROM DISK = 'C:\db_bks\BLUESTAR_C_backup_2017_04_12_060012_7136057.bak'
GO
ALTER DATABASE BLUESTAR_C SET MULTI_USER
GO
--BLUESTAR_N
ALTER DATABASE BLUESTAR_N SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE BLUESTAR_N FROM DISK = 'C:\db_bks\BLUESTAR_N_backup_2017_04_12_060012_7136057.bak'
GO
ALTER DATABASE BLUESTAR_N SET MULTI_USER
GO
--DEKASA
ALTER DATABASE DEKASA SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE DEKASA FROM DISK = 'C:\db_bks\DEKASA_backup_2017_04_12_060012_7292281.bak'
GO
ALTER DATABASE DEKASA SET MULTI_USER
GO
--DEKASA_C
ALTER DATABASE DEKASA_C SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE DEKASA_C FROM DISK = 'C:\db_bks\DEKASA_C_backup_2017_04_12_060012_7292281.bak'
GO
ALTER DATABASE DEKASA_C SET MULTI_USER
GO
--DEKASA_N
ALTER DATABASE DEKASA_N SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE DEKASA_N FROM DISK = 'C:\db_bks\DEKASA_N_backup_2017_04_12_060012_7448601.bak'
GO
ALTER DATABASE DEKASA_N SET MULTI_USER
GO
--DEMOA
ALTER DATABASE DEMOA SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE DEMOA FROM DISK = 'C:\db_bks\DEMOA_backup_2017_04_12_060012_7604661.bak'
GO
ALTER DATABASE DEMOA SET MULTI_USER
GO
--DEMOC
ALTER DATABASE DEMOC SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE DEMOC FROM DISK = 'C:\db_bks\DEMOC_backup_2017_04_12_060012_7763071.bak'
GO
ALTER DATABASE DEMOC SET MULTI_USER
GO
--DEMON
ALTER DATABASE DEMON SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE DEMON FROM DISK = 'C:\db_bks\DEMON_backup_2017_04_12_060012_7763071.bak'
GO
ALTER DATABASE DEMON SET MULTI_USER
GO
--demo
ALTER DATABASE demo SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE demo FROM DISK = 'C:\db_bks\demo_backup_2017_04_12_060012_7448601.bak'
GO
ALTER DATABASE demo SET MULTI_USER
GO
--ELZYRA
ALTER DATABASE ELZYRA SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE ELZYRA FROM DISK = 'C:\db_bks\ELZYRA_backup_2017_04_12_060012_7917333.bak'
GO
ALTER DATABASE ELZYRA SET MULTI_USER
GO
--FerreNomi
ALTER DATABASE FerreNomi SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE FerreNomi FROM DISK = 'C:\db_bks\FerreNomi_backup_2017_04_12_060012_7917333.bak'
GO
ALTER DATABASE FerreNomi SET MULTI_USER
GO
--GLOBAL
ALTER DATABASE GLOBAL SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE GLOBAL FROM DISK = 'C:\db_bks\GLOBAL_backup_2017_04_12_060012_8074391.bak'
GO
ALTER DATABASE GLOBAL SET MULTI_USER
GO
--
ALTER DATABASE GLOBAL_C SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE GLOBAL_C FROM DISK = 'C:\db_bks\GLOBAL_C_backup_2017_04_12_060012_8074391.bak'
GO
ALTER DATABASE GLOBAL_C SET MULTI_USER
GO
--GROUPTA
ALTER DATABASE GROUPTA SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE GROUPTA FROM DISK = 'C:\db_bks\GROUPTA_backup_2017_04_12_060012_8229913.bak'
GO
ALTER DATABASE GROUPTA SET MULTI_USER
GO
--GROUP_C
ALTER DATABASE GROUP_C SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE GROUP_C FROM DISK = 'C:\db_bks\GROUP_C_backup_2017_04_12_060012_8229913.bak'
GO
ALTER DATABASE GROUP_C SET MULTI_USER
GO
--INDUSUCA
ALTER DATABASE INDUSUCA SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE INDUSUCA FROM DISK = 'C:\db_bks\INDUSUCA_backup_2017_04_12_060012_8386203.bak'
GO
ALTER DATABASE INDUSUCA SET MULTI_USER
GO
--K2W
ALTER DATABASE K2W SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE K2W FROM DISK = 'C:\db_bks\K2W_backup_2017_04_12_060012_8386203.bak'
GO
ALTER DATABASE K2W SET MULTI_USER
GO
--KELARA
ALTER DATABASE KELARA SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE KELARA FROM DISK = 'C:\db_bks\KELARA_backup_2017_04_12_060012_8542560.bak'
GO
ALTER DATABASE KELARA SET MULTI_USER
GO
--KELARA_C
ALTER DATABASE KELARA_C SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE KELARA_C FROM DISK = 'C:\db_bks\KELARA_C_backup_2017_04_12_060012_8542560.bak'
GO
ALTER DATABASE KELARA_C SET MULTI_USER
GO
--KELARA_N
ALTER DATABASE KELARA_N SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE KELARA_N FROM DISK = 'C:\db_bks\KELARA_N_backup_2017_04_12_060012_8698542.bak'
GO
ALTER DATABASE KELARA_N SET MULTI_USER
GO
--LYDPLOT
ALTER DATABASE LYDPLOT SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE LYDPLOT FROM DISK = 'C:\db_bks\LYDPLOT_backup_2017_04_12_060012_8698542.bak'
GO
ALTER DATABASE LYDPLOT SET MULTI_USER
GO
--LYDPLOT_C
ALTER DATABASE LYDPLOT_C SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE LYDPLOT_C FROM DISK = 'C:\db_bks\LYDPLOT_C_backup_2017_04_12_060012_8854930.bak'
GO
ALTER DATABASE LYDPLOT_C SET MULTI_USER
GO
--MasterProfitPro2K12
ALTER DATABASE MasterProfitPro2K12 SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE MasterProfitPro2K12 FROM DISK = 'C:\db_bks\MasterProfitPro2K12_backup_2017_04_12_060012_9167356.bak'
GO
ALTER DATABASE MasterProfitPro2K12 SET MULTI_USER
GO
--MasterProfitPro
ALTER DATABASE MasterProfitPro SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE MasterProfitPro FROM DISK = 'C:\db_bks\MasterProfitPro_backup_2017_04_12_060012_9167356.bak'
GO
ALTER DATABASE MasterProfitPro SET MULTI_USER
GO
--MasterProfit
ALTER DATABASE MasterProfit SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE MasterProfit FROM DISK = 'C:\db_bks\MasterProfit_backup_2017_04_12_060012_9011133.bak'
GO
ALTER DATABASE MasterProfit SET MULTI_USER
GO
--MEDICAL
ALTER DATABASE MEDICAL SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE MEDICAL FROM DISK = 'C:\db_bks\MEDICAL_backup_2017_04_12_060012_9324962.bak'
GO
ALTER DATABASE MEDICAL SET MULTI_USER
GO
--MEDICAL_C
ALTER DATABASE MEDICAL_C SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE MEDICAL_C FROM DISK = 'C:\db_bks\MEDICAL_C_backup_2017_04_12_060012_9324962.bak'
GO
ALTER DATABASE MEDICAL_C SET MULTI_USER
GO
--MEDICAL_N
ALTER DATABASE MEDICAL_N SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE MEDICAL_N FROM DISK = 'C:\db_bks\MEDICAL_N_backup_2017_04_12_060012_9324962.bak'
GO
ALTER DATABASE MEDICAL_N SET MULTI_USER
GO
--MICHI01
ALTER DATABASE MICHI01 SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE MICHI01 FROM DISK = 'C:\db_bks\MICHI01_backup_2017_04_12_060012_9636170.bak'
GO
ALTER DATABASE MICHI01 SET MULTI_USER
GO
--MICHI_C
ALTER DATABASE MICHI_C SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE MICHI_C FROM DISK = 'C:\db_bks\MICHI_C_backup_2017_04_12_060012_9479905.bak'
GO
ALTER DATABASE MICHI_C SET MULTI_USER
GO
--MICH_N
ALTER DATABASE MICH_N SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE MICH_N FROM DISK = 'C:\db_bks\MICH_N_backup_2017_04_12_060012_9479905.bak'
GO
ALTER DATABASE MICH_N SET MULTI_USER
GO
--mobiliza-2.7
ALTER DATABASE [mobiliza-2.7] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE [mobiliza-2.7] FROM DISK = 'C:\db_bks\mobiliza-2.7_backup_2017_04_12_060012_9636170.bak'
GO
ALTER DATABASE [mobiliza-2.7] SET MULTI_USER
GO
--mobiliza-3.1
ALTER DATABASE [mobiliza-3.1] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE [mobiliza-3.1] FROM DISK = 'C:\db_bks\mobiliza-3.1_backup_2017_04_12_060012_9792337.bak'
GO
ALTER DATABASE [mobiliza-3.1] SET MULTI_USER
GO
--NORDICOS
ALTER DATABASE NORDICOS SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE NORDICOS FROM DISK = 'C:\db_bks\NORDICOS_backup_2017_04_12_060013_0105076.bak'
GO
ALTER DATABASE NORDICOS SET MULTI_USER
GO
--NORDIC_N
ALTER DATABASE NORDIC_N SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE NORDIC_N FROM DISK = 'C:\db_bks\NORDIC_N_backup_2017_04_12_060013_0105076.bak'
GO
ALTER DATABASE NORDIC_N SET MULTI_USER
GO
--NORDI_C
ALTER DATABASE NORDI_C SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE NORDI_C FROM DISK = 'C:\db_bks\NORDI_C_backup_2017_04_12_060012_9948606.bak'
GO
ALTER DATABASE NORDI_C SET MULTI_USER
GO
--OVERLAND
ALTER DATABASE OVERLAND SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE OVERLAND FROM DISK = 'C:\db_bks\OVERLAND_backup_2017_04_12_060013_0418920.bak'
GO
ALTER DATABASE OVERLAND SET MULTI_USER
GO
--OVER_C
ALTER DATABASE OVER_C SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE OVER_C FROM DISK = 'C:\db_bks\OVER_C_backup_2017_04_12_060013_0260895.bak'
GO
ALTER DATABASE OVER_C SET MULTI_USER
GO
--OVER_N
ALTER DATABASE OVER_N SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE OVER_N FROM DISK = 'C:\db_bks\OVER_N_backup_2017_04_12_060013_0418920.bak'
GO
ALTER DATABASE OVER_N SET MULTI_USER
GO
--OVL
ALTER DATABASE OVL SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE OVL FROM DISK = 'C:\db_bks\OVL_backup_2017_04_12_060013_0573761.bak'
GO
ALTER DATABASE OVL SET MULTI_USER
GO
--OXILAGO
ALTER DATABASE OXILAGO SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE OXILAGO FROM DISK = 'C:\db_bks\OXILAGO_backup_2017_04_12_060013_0886085.bak'
GO
ALTER DATABASE OXILAGO SET MULTI_USER
GO
--OXIL_N
ALTER DATABASE OXIL_N SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE OXIL_N FROM DISK = 'C:\db_bks\OXIL_N_backup_2017_04_12_060013_0886085.bak'
GO
ALTER DATABASE OXIL_N SET MULTI_USER
GO
--OXI_C
ALTER DATABASE OXI_C SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE OXI_C FROM DISK = 'C:\db_bks\OXI_C_backup_2017_04_12_060013_0730164.bak'
GO
ALTER DATABASE OXI_C SET MULTI_USER
GO
--PICARI
ALTER DATABASE PICARI SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE PICARI FROM DISK = 'C:\db_bks\PICARI_backup_2017_04_12_060013_1042329.bak'
GO
ALTER DATABASE PICARI SET MULTI_USER
GO
--PICARI_C
ALTER DATABASE PICARI_C SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE PICARI_C FROM DISK = 'C:\db_bks\PICARI_C_backup_2017_04_12_060013_1198527.bak'
GO
ALTER DATABASE PICARI_C SET MULTI_USER
GO
--Profit_RG
ALTER DATABASE Profit_RG SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE Profit_RG FROM DISK = 'C:\db_bks\Profit_RG_backup_2017_04_12_060013_1354858.bak'
GO
ALTER DATABASE Profit_RG SET MULTI_USER
GO
--Profit_XLS
ALTER DATABASE Profit_XLS SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE Profit_XLS FROM DISK = 'C:\db_bks\Profit_XLS_backup_2017_04_12_060013_1354858.bak'
GO
ALTER DATABASE Profit_XLS SET MULTI_USER
GO
--PSUPPLY
ALTER DATABASE PSUPPLY SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE PSUPPLY FROM DISK = 'C:\db_bks\PSUPPLY_backup_2017_04_12_060013_1511158.bak'
GO
ALTER DATABASE PSUPPLY SET MULTI_USER
GO
--PSUPPLY_C
ALTER DATABASE PSUPPLY_C SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE PSUPPLY_C FROM DISK = 'C:\db_bks\PSUPPLY_C_backup_2017_04_12_060013_1667371.bak'
GO
ALTER DATABASE PSUPPLY_C SET MULTI_USER
GO
--PSUPPLY_N
ALTER DATABASE PSUPPLY_N SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE PSUPPLY_N FROM DISK = 'C:\db_bks\PSUPPLY_N_backup_2017_04_12_060013_1667371.bak'
GO
ALTER DATABASE PSUPPLY_N SET MULTI_USER
GO
--QUALITY
ALTER DATABASE QUALITY SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE QUALITY FROM DISK = 'C:\db_bks\QUALITY_backup_2017_04_12_060013_1823610.bak'
GO
ALTER DATABASE QUALITY SET MULTI_USER
GO
--QUALITY_C
ALTER DATABASE QUALITY_C SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE QUALITY_C FROM DISK = 'C:\db_bks\QUALITY_C_backup_2017_04_12_060013_1979977.bak'
GO
ALTER DATABASE QUALITY_C SET MULTI_USER
GO
--QUALITY_N
ALTER DATABASE QUALITY_N SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE QUALITY_N FROM DISK = 'C:\db_bks\QUALITY_N_backup_2017_04_12_060013_2136098.bak'
GO
ALTER DATABASE QUALITY_N SET MULTI_USER
GO
--SERVICE
ALTER DATABASE SERVICE SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE SERVICE FROM DISK = 'C:\db_bks\SERVICE_backup_2017_04_12_060013_2448530.bak'
GO
ALTER DATABASE SERVICE SET MULTI_USER
GO
--SERV_C
ALTER DATABASE SERV_C SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE SERV_C FROM DISK = 'C:\db_bks\SERV_C_backup_2017_04_12_060013_2136098.bak'
GO
ALTER DATABASE SERV_C SET MULTI_USER
GO
--SERV_N
ALTER DATABASE SERV_N SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE SERV_N FROM DISK = 'C:\db_bks\SERV_N_backup_2017_04_12_060013_2292173.bak'
GO
ALTER DATABASE SERV_N SET MULTI_USER
GO
--STAR01
ALTER DATABASE STAR01 SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE STAR01 FROM DISK = 'C:\db_bks\STAR01_backup_2017_04_12_060013_2604917.bak'
GO
ALTER DATABASE STAR01 SET MULTI_USER
GO
--Star01_C
ALTER DATABASE Star01_C SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE Star01_C FROM DISK = 'C:\db_bks\Star01_C_backup_2017_04_12_060013_2761017.bak'
GO
ALTER DATABASE Star01_C SET MULTI_USER
GO
--STAR01_N
ALTER DATABASE STAR01_N SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE STAR01_N FROM DISK = 'C:\db_bks\STAR01_N_backup_2017_04_12_060013_2917359.bak'
GO
ALTER DATABASE STAR01_N SET MULTI_USER
GO
--TRACO
ALTER DATABASE TRACO SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE TRACO FROM DISK = 'C:\db_bks\TRACO_backup_2017_04_12_060013_3073521.bak'
GO
ALTER DATABASE TRACO SET MULTI_USER
GO
--TRACO_C
ALTER DATABASE TRACO_C SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE TRACO_C FROM DISK = 'C:\db_bks\TRACO_C_backup_2017_04_12_060013_3073521.bak'
GO
ALTER DATABASE TRACO_C SET MULTI_USER
GO
--TRACO_N
ALTER DATABASE TRACO_N SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE TRACO_N FROM DISK = 'C:\db_bks\TRACO_N_backup_2017_04_12_060013_3229862.bak'
GO
ALTER DATABASE TRACO_N SET MULTI_USER
GO
--ZEGNA
ALTER DATABASE ZEGNA SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE ZEGNA FROM DISK = 'C:\db_bks\ZEGNA_backup_2017_04_12_060013_3386121.bak'
GO
ALTER DATABASE ZEGNA SET MULTI_USER
GO
--ZEGNA_C
ALTER DATABASE ZEGNA_C SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE ZEGNA_C FROM DISK = 'C:\db_bks\ZEGNA_C_backup_2017_04_12_060013_3542288.bak'
GO
ALTER DATABASE ZEGNA_C SET MULTI_USER
GO
--ZEGNA_N
ALTER DATABASE ZEGNA_N SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE ZEGNA_N FROM DISK = 'C:\db_bks\ZEGNA_N_backup_2017_04_12_060013_3698573.bak'
GO
ALTER DATABASE ZEGNA_N SET MULTI_USER
GO