SELECT * FROM sys.databases WHERE name IN ('STAR01','ELZYRA','Profit_RG')
--
SELECT * from ELZYRA.dbo.Usuarios WHERE 'A' = 'a'
SELECT ELZYRA.dbo.func_ValidaEmpresa('STAR01')
--
USE master;    
ALTER DATABASE ELZYRA  COLLATE SQL_Latin1_General_CP1_CI_AS;
--
USE ELZYRA
DROP FUNCTION dbo.func_ConsultarRifCliente
DROP FUNCTION dbo.func_MetasVentasSG
DROP FUNCTION dbo.func_MixVentasSG
DROP FUNCTION dbo.func_EmpresasCA
--
USE master
ALTER DATABASE ELZYRA SET SINGLE_USER WITH ROLLBACK IMMEDIATE
ALTER DATABASE ELZYRA SET RESTRICTED_USER
ALTER DATABASE ELZYRA SET MULTI_USER