SELECT * FROM ELZYRA.INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME LIKE '%empresa%'
AND DATA_TYPE = 'nchar'
AND CHARACTER_MAXIMUM_LENGTH = 20
ORDER BY TABLE_NAME
--
SELECT * FROM ELZYRA.dbo.Reclamo_Razon_Email
SELECT * FROM ELZYRA.dbo.Art_min
SELECT * FROM ELZYRA.dbo.Articulos_CertificaSResultado
SELECT * FROM ELZYRA.dbo.Empresas
SELECT * FROM ELZYRA.dbo.Comision_Genera
SELECT * FROM ELZYRA.dbo.Emp_asoc
SELECT * FROM ELZYRA.dbo.GrupoPorEmpresas
SELECT * FROM ELZYRA.dbo.Notificacion_email
--
ALTER TABLE ELZYRA.dbo.Reclamo_Razon_Email ALTER COLUMN empresa nchar(20) NOT NULL
ALTER TABLE ELZYRA.dbo.Art_min ALTER COLUMN empresa nchar(20) NOT NULL
ALTER TABLE ELZYRA.dbo.Empresas ALTER COLUMN base_dato nchar(20) NOT NULL
ALTER TABLE ELZYRA.dbo.Emp_asoc ALTER COLUMN co_empresa nchar(20) NOT NULL
ALTER TABLE ELZYRA.dbo.Reclamo_Cliente ALTER COLUMN empresa nchar(20) NOT NULL
ALTER TABLE ELZYRA.dbo.Notificacion_email ALTER COLUMN empresa nchar(20) NOT NULL
ALTER TABLE ELZYRA.dbo.UMF ALTER COLUMN empresa nchar(20) NOT NULL
ALTER TABLE ELZYRA.dbo.Usu_Emp ALTER COLUMN co_empresa nchar(20) NOT NULL